Sitecore/jss

samples/advanced-sample-angular/internals/build/prebuild.js
samples/advanced-sample-angular/src/environments/environment.connected.ts.template
samples/advanced-sample-angular/src/environments/environment.prod.ts.template
samples/advanced-sample-angular/src/environments/environment.server.ts.template
samples/advanced-sample-angular/src/environments/environment.ts.template

making sure advanced angular app doesn't require `jss setup` before `jss start`

dx optimization for jss start

---

samples/sitecore-embedded-jss-app/sitecore/definitions/components/components.sitecore.js
samples/sitecore-embedded-jss-app/sitecore/definitions/config.js
samples/sitecore-embedded-jss-app/src/app/components/Step.js
samples/sitecore-embedded-jss-app/src/app/index.js

This fixes the following problems:
- `config.js` missing from `/sitecore` (just copied from React project)
- `graphql` files cannot be `import`ed with the webpack config (copied fix from React project)
- placeholder `main` was renamed to `jss-main` but not in JS components
There is still an error after this lands: in the manifest, two `jss-main` placeholders are added. Until this is fixed, you need to remove one of them from `sitecore-import.json` and run with `--skipManifest`.

Make the embedded example work again

---

README.md

Fix React documentation link in README and make [markdownlint](https://github.com/markdownlint/markdownlint) happy. 😄

Fix React Documentation Link in README

---

docs/data/routes/docs/techniques/working-disconnected/customizing-disconnected/en.md
samples/angular/scripts/disconnected-mode-proxy.ts
samples/react/scripts/disconnected-mode-proxy.js
samples/vue/scripts/disconnected-mode-proxy.js

...that you can steal code from and customize.
Fixes #79 by documenting that you can tweak the conventions by expanding the middleware yourself.

Clarify that createDefaultDisconnectedServer is an API

---

packages/sitecore-jss/src/dataModels.ts

Fixes #78
@jantimon can you take a look at this? The sandbox on #78 was a 404.
This does not break the compilation of downstream consumers in TS (angular sample app, react lib, angular lib)

Alter typing to enable strong typed placeholder names

---

packages/sitecore-jss-dev-tools/src/disconnected-server/create-default-disconnected-server.ts
samples/angular/scripts/disconnected-mode-proxy.ts
samples/react/scripts/disconnected-mode-proxy.js
samples/vue/scripts/disconnected-mode-proxy.js

Per #80 the appRoot of the proxy actually meant "/config", which makes no sense.
This commit causes the behaviour of appRoot to expect the actual app root path, in such a way that existing JSS apps will continue to work unchanged as well (each sample app was tested with old and tweaked configs in disconnected-mode-proxy)
Removes principle of least surprise violation
Ran each sample app with old and new proxy config to verify backwards compatibility.

Make disconnected appRoot mean appRoot not scriptsRoot

---

docs/data/routes/docs/techniques/extending-layout-service/extending-layout-service-overview/en.md

Documentation change. Provided information about adding custom layout service named configurations to the `renderJsonRendering` pipeline `AllowedConfigurations` list.
People using custom LS configurations in TP4 or earlier were encountering unexpected changes in LS output due to a change in how `PlaceholderTransformer` was invoked in GA release.

Docs update for adding custom layout service named configurations

---

azure-pipelines.yml
packages/sitecore-jss-angular/karma.conf.js

will codeship finally be gone?

Azure pipelines #3

---

docs/sitecore/definitions/routes.sitecore.js
docs/src/app/components/Article.js

This makes it super easy to PR documentation fixes and clarifications! 🎉 
It's too much work to fix a simple typo in the docs. This makes it a single click and you can open the PR right within GitHub.

Adds an 'Edit this on GitHub' link to documentation pages

---

docs/data/routes/docs/getting-started/app-deployment/en.md

Minor update to the documentation, adding a comment about needing to publish the API key item in Sitecore 9.1 and above. 
see above
Following the "Getting started" guide, I noticed that the API key item needed to be published in Sitecore 9.1 (as it moved to the master database). 
n/a
Documentation only 
- [n/a] My code follows the code style of this project.
- [n/a] My change requires a change to the documentation.

added a note to publish the API key item

---

docs/data/routes/docs/techniques/graphql/graphql-overview/en.md

The config for endpoints gained additional simplification and security options that were not properly documented.

Fix typo in GraphQL docs

---

docs/data/routes/docs/client-frameworks/angular/angular-tips/en.md
packages/sitecore-jss-angular/src/lib.module.ts
packages/sitecore-jss-angular/src/public_api.ts

Fix the issue with the Angular AOT compiler connect with static JssModule method forChild().
Revert changes in forChild() static method and make DYNAMIC_COMPONENT provider exportable. Now we can make the configuration directly in lazy loading module without using static method.
Fix issue which prevent using the lazy loading for JSS in production mode.
You can test with production build.

Fix AOT compile for lazy loading modules

---

packages/sitecore-jss-dev-tools/src/disconnected-server/DisconnectedLayoutServiceOptions.ts
packages/sitecore-jss-dev-tools/src/disconnected-server/layout-service.ts

Add `currentManifest`, `request`, and `response` parameters to `customizeRendering` method.
The Layout Service `customizeRendering` method does not expose the `currentManifest`, `request`, or `response`, so if you want to customize your renderings based on data from either of these sources, you have to use `customizeRoute` and a mountain of extra code to pull the renderings from the route.
For example, with this new method you can now customize renderings based on manifest data:
```javascript
export default function(manifest) {
manifest.addComponent({
name: 'ContentBlock',
displayName: 'Content Block',
icon: SitecoreIcon.DocumentTag,
fields: [
{ name: 'heading', type: CommonFieldTypes.SingleLineText },
{ name: 'content', type: CommonFieldTypes.RichText },
],
addCoolStuff: true
});
}
``` …

Add extra parameters to customizeRendering method

---

samples/angular/src/app/routing/jss-route-resolver.service.ts

Fixes #132 - previously the change of the hash would change the route URL but the comparison to refresh the page was not including the current location hash in its comparison. `state.url` would have the hash added, but `currentLocation` would not. 
This meant it was treated as a page refresh situation - but it would never match the current location without the hash so it went into a loop instead attempting to get the location to match.
Issue affected angular links with _anchors_ in _EE only_. It has been tested in this state.
cc @AlexKasaku

Prevent reloading Angular route when only hash changes

---

packages/sitecore-jss-cli/src/micro-manifest.ts
packages/sitecore-jss-cli/src/scripts/deploy.component.ts
packages/sitecore-jss-manifest/src/generator/manifest.ts
packages/sitecore-jss-manifest/src/generator/pipelines/generateManifest/generateTemplates.ts
packages/sitecore-jss-manifest/src/generator/validators.ts

- Fixes `jss deploy component` having invalid casing on `<Name>` param, which broke it because the code expected `<name>` instead (maybe a new thing in a yargs update, used to work fine)
- Fixes `jss deploy component` creating a datasource template even if `--fields` was not passed. It should be usable to create datasource-less components as well. This is a breaking change but breaks it in the direction of sanity.
- `jss manifest` will now stop if a template fails validation, instead of ignoring it and continuing without that template

Sitecore-first component deployment fixes

---

docs/data/routes/docs/techniques/working-disconnected/manifest-api/en.md
packages/sitecore-jss-manifest/src/generator/manifest.types.ts

+ Updated docs to make them more reflective of reality.
Fixes #120
Added explicit placeholder allow to Angular manifest (being already in TS, also validated the typings):
```ts
export default function(manifest: Manifest) {
manifest.addComponent({
name: 'ContentBlock',
allowedPlaceholders: ['foo', 'jss-bar']
});
// also needed since allowing does not register the placeholder itself with the manifest
manifest.addPlaceholder({ name: 'foo'}, { name: 'jss-bar'});
}
```

Add missing typing for explicitly defining placeholders

---

packages/sitecore-jss-angular/package.json
packages/sitecore-jss-angular/src/components/link.directive.ts
packages/sitecore-jss-angular/src/components/router-link.directive.spec.ts
packages/sitecore-jss-angular/src/components/router-link.directive.ts
packages/sitecore-jss-angular/src/lib.module.ts
packages/sitecore-jss-angular/src/public_api.ts

Add new link directive (scRouterLink) which work with angular route. This will prevent refresh the whole page and lost of state of app after refresh.
Extended the LinkDirective class and overwrited only one method renderTemplate(). New directive has access to Router Service and on click make navigation using navigate() method of Route service.
Prevent refresh of whole page and lost of state of app after refresh. 
Can be test in sample app after change one of *scLink with *scRouterLink. Open the DevTool and check the network tab, In the tab need to see, after click over navigation link,  only one call to Layout Service without call for main.js, vendor.js and other and also the loader for browser tab need to missing.

Add new link directive which work with angular route

---

packages/sitecore-jss-proxy/src/index.ts

Readd !noDebug to jss-proxy console logging to allow disabling of logging. 
Readd !noDebug to jss-proxy console logging to allow disabling of logging.
Since the last upgrade we have debug logging on production. This merge request solves it.
Tested this by reproducing it and adding this line to our local npm package.

 Only log pathRewriteExcludePredicate in debug env

---

docs/package.json

(and thus building twice) when it deploys docs
See https://help.heroku.com/P5IMU3MP/heroku-node-js-build-script-change-faq

Adds faux script to prevent Heroku from running 'build' script

---

packages/sitecore-jss-react/src/components/PlaceholderCommon.tsx

Changed proptypes of `missingComponentComponent` and `errorComponent` to `PropTypes.func` in 
`packages/sitecore-jss-react/src/components/PlaceholderCommon.tsx`
Whenever the following JSX is used:
```
<Placeholder 
missingComponentComponent={MissingComponentComponent} 
errorComponent={ErrorComponent}  {...placeholderProps} 
/>
```
The following warning will occur:
```
Warning: Failed prop type: Invalid prop `missingComponentComponent` of type `function` supplied to `PlaceholderComponent`, expected `object`.
```
This PR will stop that warning from showing
I've changed the proptypes and made sure the warning did not show up in my browser-console.
Browser: Chrome Version 73.0.3683.86 (Official Build) (64-bit) 
OS: OSX

Changed proptypes in PlaceholderCommon

---

packages/sitecore-jss-manifest/src/generator/pipelines/generateMedia/utils.ts

Added ability for manifest media to be extracted from inherited template fields.

---

.gitattributes

When working on a mac or linux with git config for autocrlf all the line endings in the repo are set to lf which fails eslint. This should fix that
When working on a mac or linux with git config for autocrlf all the line endings in the repo are set to lf which fails eslint. This should fix that

Added .gitattributes file with settings for `crlf`

---

README.md

The links to the relevant markdown files in the README.md are case-sensitive and so were giving 404s. This resolves them to the correct url.
I have committed this to my fork and clicked on the links in the readme
- [] My change requires a change to the documentation.

Fixed case-sensitive markdown links

---

packages/sitecore-jss-angular/package-lock.json
packages/sitecore-jss-angular/src/components/generic-link.directive.spec.ts
packages/sitecore-jss-angular/src/components/generic-link.directive.ts
packages/sitecore-jss-angular/src/lib.module.ts
packages/sitecore-jss-angular/src/public_api.ts
samples/angular/src/app/components/styleguide-field-usage-link/styleguide-field-usage-link.component.html

Add angular directive for general links that can be both internal and external.
This allows Content Editors to not be limited to one type of predefined linkfield while maintaining angular routerlinks
Add angular directive for general links that can be both internal and external.
This allows Content Editors to not be limited to one type of predefined linkfield while maintaining angular routerlinks
Currently the implementation of a link is limited by developers. Either they choose *scLink which doesn't use angular routerlinks, or *scRouterLink which solely uses routerlinks. This directive decides whether the link has a protocol and is therefor an external link.
Added unit tests and tested it on our application.

[Angular] Add directive for general links that can be both internal and external

---

packages/sitecore-jss-react/src/enhancers/withSitecoreContext.tsx

This takes the props type from the original component and uses it to form the prop types for the HOC.
The component prop types were getting lost when wrapped in `withSitecoreContext`
`npm run test-packages`
I've also packed the package and pulled it into our repo and built it successfully.

Pass through component types when using `withSitecoreContext`

---

packages/sitecore-jss/src/dataModels.ts
packages/sitecore-jss/src/layoutDataUtils.ts

This change makes two changes that improve typing around `Field.value` and the return value of `getFieldValue()`. This should be backwards compatible so long as users of `getFieldValue<T>()` were treating its output as `T | undefined`.
1. Redefines `Field` as `Field<T = GenericFieldValue>`, where `T` refers to the type of the `.value` property in the field. The original value type is maintained as `GenericFieldValue`, so this change is backwards compatible.
1. Updates `getFieldValue<T>(...)` to use this new type parameter in `Field` to produce predictably typed results. Thus, `getFieldValue<string>` will return a `string | undefined` instead of `any`.
https://github.com/Sitecore/jss/issues/156
I modified the code locally and used the following snippet in a TypeScript enabled editor to …

Add type strength to Field and getFieldValue

---

packages/sitecore-jss-dev-tools/src/package-deploy.ts

Implemented issue #261 .
Currently, using the `--acceptCertificate` option requires the certificate thumbprint be in a specific format. This change expands support to other common formats.
Local testing and building.

implemented issue #261

---

samples/vue/server/server.vue.config.js

I've not added in 
```
config.module.rules.push({
test: /\.(ts|tsx)?$/,
loader: 'ts-loader',
exclude: /node_modules/,
options: {
appendTsSuffixTo: [/\.vue$/],
}
});
```
as I figured people probably wanted to opt into that. 
If adding ^ we'd need to update package.json / package-lock.json with **ts-loader** and **typescript** and also add to webpack override: `config.resolve.extensions.push('.ts');`

Added support for TypeScript when 'jss build'ing

---

packages/sitecore-jss-vue/package-lock.json
packages/sitecore-jss-vue/package.json
packages/sitecore-jss-vue/src/components/Date.test.ts
packages/sitecore-jss-vue/src/components/Image.test.ts
packages/sitecore-jss-vue/src/components/Link.test.ts
packages/sitecore-jss-vue/src/components/Placeholder.test.ts
packages/sitecore-jss-vue/src/components/RichText.test.ts
packages/sitecore-jss-vue/src/components/Text.test.ts
packages/sitecore-jss-vue/src/components/__snapshots__/MissingComponent.test.ts.snap
packages/sitecore-jss-vue/src/components/__snapshots__/Placeholder.test.ts.snap
packages/sitecore-jss-vue/tsconfig.json

1) Added babel-core dependency, cause vue-jest have `peerDependency` babel-core
https://github.com/Sitecore/jss/compare/feature/356384?expand=1#diff-2be57abd432f87f7aafe80e047aea9a9R30
2) Fixed typescript errors
3) In snapshots was added `background` style, by jest, i think before update was a bug, that `background` style wasn't added (because we have this style in our component)
https://github.com/Sitecore/jss/compare/feature/356384?expand=1#diff-893ef5b8f65badc50ec0d301e4f6184eR4
4) Ran e2e - everything is passed, manually opened vue sample app - and everything is working

update dependencies and fix ts errors

---

docs/data/routes/docs/getting-started/jss-server-install/en.md

The manual step was missing in the CD server setup

Extended a CD server setup instructions

---

samples/node-headless-ssr-proxy/config.js

At the moment, setting the `SITECORE_ENABLE_DEBUG` environment variable to anything will enable debug, even if we set it to "false".
This ensures that we only enable debug if `SITECORE_ENABLE_DEBUG` is set to "true" (independently of case)
Ensures that users can set `SITECORE_ENABLE_DEBUG` to "false" to disable SSR debug.
In our local implementation

Correctly evaluates the value of SITECORE_ENABLE_DEBUG

---

packages/sitecore-jss-manifest/src/generator/pipelines/generateMedia/utils.ts

This change makes sure you also consider fields of type `Droptree` and `Multilist`.
Currently only `Treelist` content definitions are traversed recursively to look for media items. If you add a field of type `Multilist` or `Droptree` its media items will not be included in the JSS import.
Tested locally and is a minor change.

[sitecore-jss-manifest] Include media from Droptree and Multilist content

---

samples/react/src/index.js

Set i18n initial language based on SSR language or static config defaultLanguage to prevent re-renders in multi-lingual apps during the hydration process. 
To fix the flicker after initial page load issue when using the React sample. (This issue may exist in the other samples as well.)
I have tested local Sitecore 9.3 instance with a JSS 13.0 site and debug via chrome dev tools. 
My change simply initializes the language for i18ninit by pulling the SSR language from JSS_STATE, or using the config defaultLanguage setting.  
The comments in code seem to support this, but I feel this could be introduced to prevent others from experiencing this issue OOTB.

React sample - set i18n init lang to prevent SSR hydration from re-rendering app

---

samples/vue/src/components/Styleguide/Styleguide-Specimen.vue

Vue sample Specimen component was displaying an incorrect implementation path.
Example:
**Single-Line Text**
Implementation: `/src/components/Styleguide-FieldUsage-Text/index.js`
But the actual path to this component src should be: 
Implementation: `/src/components/Styleguide/Styleguide-FieldUsage-Text.vue`

Vue sample Specimen component updated with correct implementation path

---

packages/sitecore-jss-react/src/components/Image.test.tsx
packages/sitecore-jss-react/src/components/Image.tsx

Adding `srcSet` to \<Image> Component removes the `src` Attribute.
This PR will always output the `src` Attribute, even when a `srcSet` Object is passed.
This will improve the support for older Browsers, since they might don't support `srcSet` (like IE11). Using the Progressive Enhancement Approach newer Browsers can benefit from the `srcSet` and will ignore the `src` Attribute.
Improve Support for older Browsers without the need for a `srcSet` Polyfill - which is difficult to implement when using Jss <Link> or Router Links.
Tests for Image updated to test for `srcSet` / `sizes` Attributes output.
I used the same values as in the Styleguide Image Example.
Running `npm run test` inside `root` or `/packages/sitecore-jss-react` will run the new test

Responsive image srcset fallback with src output

---

packages/sitecore-jss-react/src/components/Placeholder.test.tsx
packages/sitecore-jss-react/src/components/Placeholder.tsx
packages/sitecore-jss-react/src/components/PlaceholderCommon.tsx
packages/sitecore-jss-react/src/enhancers/withPlaceholder.tsx

- #349 Fix
- Added unit tests for `render, renderEach, renderEmpty` Placeholder functions
Fixes issue #349 
I replaced the version of sitecore-jss-react in my sitecore project with the build output of this branch and I am not getting the typing error that I used to.

Fix bug #349 typings for Placeholder prop functions

---

packages/sitecore-jss-react/src/components/SitecoreContext.test.tsx
packages/sitecore-jss-react/src/enhancers/withSitecoreContext.tsx

The current typescript definition is forcing the component to have props of type `ComponentConsumerProps` instead of just forcing to extend that type.
Components should be able use more properties that the ones just on `ComponentConsumerProps`, this fixes that
Typescript doesn't complain any more and tests pass. Assuming that users are actually including the context properties in their component props, there should be no impact.

Fixes withSitecoreContext typescript definition

---

docs/data/component-content/content-tiles/js-support-tile/en.yml

Fixed a broken link on the JSS docs home page/
This has been tested by running the docs site in disconnected mode on my local machine.

Doc - Fix broken react-native link on homepage

---

samples/vue/server/server.js
samples/vue/src/AppRoot.vue

When the server is rendering the template the id="root" element should be the first element of the AppRoot.vue element but it was set on a div enclosing the rendered app.
when the ssr rendered app was mounted in the client there was a dom-tree mismatch that forced an hydration bailout and complete dom refresh.
Also did a fix on a replace that caused two head tag terminations to be present on a server rendered page
Improves website loading performance when using ssr 
It was tested in sitecore 9.1 with jss 11.0, compiling in development to check the vue hydration bailout messages and running in integrated mode.
I patched the 11.0 version changes to this version

Vue sample - SSR - fixed hydration bailouts

---

samples/react/package.json

Fixed package.json script -> start:connected-ssr
"start:connected-ssr": "scjss-verify-setup && npm-run-all --serial bootstrap:connected --parallel start:react start:watch-components **start:http-renderer**"
start:http-renderer: doesn't exist in scripts
it should be start:http-renderer-holygrail
jss start:connected-ssr gives error as it can't find start:http-renderer in scripts.
tested by running jss start:connected-ssr. It ran successfully start:react and holygrail in parallel.

Updated react sample scripts

---

samples/react/server/server.js

Fixes issue #141: when working in XP editor in the react version, after adding a rendering with a placeholder, another rendering cannot be added in the freshly loaded placeholder but save and refresh of the page is required
The issue is caused by the fact that the very important key attribute of the `<code>` DOM element that represents the placeholder is missing after SSR. Because it is a react special prop it cannot be set directly as a prop and then transferred as an attribute and that's why in the sitecore jss library for react this problem is solved by adding the key attribute by directly modifying the DOM on the client side. But after a rendering is freshly added through SSR, it is not hydrated and the lifecycle methods are not running, so the key attribute is never added. 
The fix …

Fix bug (#141) XP editor for react requires save and refresh before adding new renderings

---

samples/vue/src/RouteHandler.vue

When the route changes to a new url including a new path and a new hash the new page isn't being retrieved because the all route changes are being ignored when then contain a hash. This should only happen when the path of the newRoute equals the path of the old route.
Manually, locally connected dev mode

[Vue Sample] Fix  route changes with path and a hash

---

docs/data/routes/docs/techniques/extending-layout-service/layoutservice-extending-context/en.md

Added suggested documentation tweak around how you need to be careful of the performance of Context Extensions as OTB cache options aren't available.

Updated context extension docs around caching

---

packages/sitecore-jss-angular/src/components/link.directive.ts

This change prevents classes from being wiped on anchor elements using the scLink directive.
For Angular JSS projects, classes are preserved on anchor elements that use **external** Sitecore links:
```
<a class="foo bar" *scLink="externalLinkData"></a> 
<a class="foo bar" href="" alt=""></a> 
```
... However when using **internal** Sitecore links, the classes are wiped:
```
<a class="foo bar" *scLink="internalLinkData"></a> 
<a href="" alt=""></a> 
```
[https://github.com/Sitecore/jss/issues/378](https://github.com/Sitecore/jss/issues/378)
First, I ran `npm run test-packages`. Next, I packaged a local version of the npm package (.tgz file) and added it to our project. Then I confirmed that the CSS class wipe issue was fixed.

Preserve classes on internal links using the scLink directive

---

packages/sitecore-jss-angular/src/components/image.directive.spec.ts
packages/sitecore-jss-angular/src/components/image.directive.ts
packages/sitecore-jss-react/src/components/Image.test.tsx
packages/sitecore-jss-react/src/components/Image.tsx
packages/sitecore-jss-vue/src/components/Image.test.ts
packages/sitecore-jss-vue/src/components/Image.ts
packages/sitecore-jss/src/mediaApi.test.ts
packages/sitecore-jss/src/mediaApi.ts

Provide ability to configure mediaUrlPrefix in mediaApi

---

packages/sitecore-jss-proxy/src/index.ts

* ensure proper connection close and behavior
* rewrite HEAD to a Layout Service GET
* don't return body content for a HEAD request

[#CS0195052] changes to HEAD request handling

---

samples/sitecore-embedded-jss-app/src/boot/Root.js
samples/sitecore-embedded-jss-app/src/boot/SitecoreContextFactory.js
samples/sitecore-embedded-jss-app/src/client.js
samples/sitecore-embedded-jss-app/src/server.js

Remove usage of SitecoreContextFactory

[sitecore-embedded-jss-app] Remove usage of SitecoreContextFactory

---

docs/data/routes/docs/getting-started/quick-start/en.md
docs/data/routes/docs/techniques/mvc-integration/javascript-rendering/en.md
docs/data/routes/help/en.md
samples/sitecore-javascript-renderings/README.md

Updated docs to flag the JavaScript Renderings feature as deprecated.
Tested on local instance.
- Added README to the JavaScript Rendering sample

[Docs] Mark javascript renderings as deprecated

---

packages/sitecore-jss/src/mediaApi.test.ts
packages/sitecore-jss/src/mediaApi.ts

Merge specific params from layout service into query string: rev, db, la, vs, ts

[sitecore-jss] Merge specific params from layout service into query string

---

packages/sitecore-jss-proxy/src/index.ts

* ensure proper connection close and behavior
* rewrite HEAD to a Layout Service GET
* don't return body content for a HEAD request

[sitecore-jss-proxy] [#CS0195052] changes to HEAD request handling

---

packages/sitecore-jss-cli/src/micro-manifest.ts
packages/sitecore-jss-cli/src/scripts/deploy.config.ts
packages/sitecore-jss-cli/src/scripts/deploy.files.ts
packages/sitecore-jss-cli/src/scripts/deploy.items.ts
packages/sitecore-jss-cli/src/scripts/deploy.template.ts
packages/sitecore-jss-dev-tools/src/resolve-scjssconfig.ts

[JSS CLI] Add --config key in order to specify path to scjssconfig.json file
Related to #420

[JSS CLI] Add --config key in order to specify path to scjssconfig.json file

---

packages/sitecore-jss-nextjs/package-lock.json
packages/sitecore-jss-nextjs/package.json
samples/nextjs/package-lock.json
samples/nextjs/package.json
samples/vue/package-lock.json

Inconsistent jss package versions prevents local symlinking from working properly.
This updates packages/nextjs to 15.0.1, and sets the dependency from samples/nextjs to * so that we don't have to update it while this is in development.
1. Deleted node folder and lock file from both nextjs packages
2. Ran reset command from repo root and verified that symlinks for all jss dependencies in the nextjs sample (including the unpublished nextjs core package) are getting added
3. Started nextjs sample in disconnected mode 
Non-breaking fix for new feature
No docs required

Clean up dependency versions

---

packages/sitecore-jss-react/src/components/VisitorIdentification.tsx
samples/nextjs/src/components/Layout.tsx

- Fixes an issue with `VisitorIdentification` React control on Next.js by moving everything (script and meta tag addition) to purely client-side 
- A pageEditing check has also been added within the control which avoids having to check in consuming app

Fix issue with VisitorIdentification control on Next.js

---

packages/sitecore-jss-react/src/components/Placeholder.test.tsx
packages/sitecore-jss-react/src/components/PlaceholderCommon.tsx
packages/sitecore-jss-react/src/components/sharedTypes.ts

Fix the typing for `ComponentFactory` to support a component type instead of an instantiated component
Change the return type of the `ComponentFactory` function type to `ComponentType` instead of just `Component` which assumes an instantiated component
This incorrect type is causing typing issues when `componentFactory` prop is passed to `SitecoreContext`. The test that is changed in this PR will result into an error if ran with the old typing. The error would be something like this `Type '(componentName: string) => React.FC<{}>' is not assignable to type 'ComponentFactory'.`
The incorrect type is causing an error in the Placeholder.test.tsx file while with the updated type the error disappears.

Fix return type of ComponentFactory to allow a component definition instead of an instantiated component

---

packages/sitecore-jss-react/src/components/MissingComponent.tsx
packages/sitecore-jss-react/src/components/Placeholder.test.tsx
packages/sitecore-jss-react/src/components/PlaceholderCommon.tsx

* Add a unit test in `Placeholder.test.tsx` that checks the case when an unknown component is requested for rendering -> then the passed `missingComponentComponent` prop of the `Placeholder` should be used.
* Fix prop-types for `missingComponentComponent` prop as it currently allows only objects while it should allow a function
When a custom `MissingComponent` implementation is passed to the `missingComponentComponent` prop there is a runtime error saying `Failed prop type: Invalid prop missingComponentComponent supplied to PlaceholderComponent.`
This is because the prop-types are incorrect and don't allow a function.
I have added a test case that is using the missingComponentComponent prop and when this test is ran with the old prop-types then the runtime error is reproduced.
When …

Fix prop-types for missingComponentComponent to allow a functional component

---

docs/data/routes/release-notes/en.md
samples/react/src/RouteHandler.js

[React sample] `Cannot read property 'sitecore' of null`, when 404 and routeData is null

---

samples/nextjs/next.config.js

* Allow specifying a distinct distDir when concurrently running app in a container
If the Next.js app is running concurrently in a container, ensures there are no concurrency issues with the .next directory.
* Implemented changes in my containerized environment
* Set the env var
* Saw the new distDir created

[NextJs] Override distDir with an environment variable

---

packages/sitecore-jss-nextjs/src/middleware/editing-data-middleware.test.ts
packages/sitecore-jss-nextjs/src/middleware/editing-data-middleware.ts
packages/sitecore-jss-nextjs/src/middleware/editing-render-middleware.test.ts
packages/sitecore-jss-nextjs/src/middleware/editing-render-middleware.ts
packages/sitecore-jss-nextjs/src/services/editing-data-service.test.ts
packages/sitecore-jss-nextjs/src/services/editing-data-service.ts
packages/sitecore-jss-nextjs/src/utils.test.ts
packages/sitecore-jss-nextjs/src/utils.ts
samples/nextjs/.env
samples/nextjs/sitecore/config/JssNextWeb.config

This is a follow-up to #529, which finalizes the editing secret now that JSS.Server implementation is complete. 
Updated names (SITECORE_SECURITY_TOKEN > JSS_EDITING_SECRET and SecurityToken > JssEditingSecret) and added doc comments.

[Next.js] [EE] Finalize editing secret following JSS.Server implementation

---

docs/data/routes/docs/fundamentals/cli/en.md
docs/data/routes/release-notes/en.md
packages/sitecore-jss-cli/package-lock.json
packages/sitecore-jss-cli/package.json
packages/sitecore-jss-cli/src/bin/jss.ts
packages/sitecore-jss-cli/src/process-env.test.ts
packages/sitecore-jss-cli/src/process-env.ts
packages/sitecore-jss-cli/src/scripts/environment.ts
packages/sitecore-jss-cli/src/scripts/index.ts

* primarily to support NODE_EXTRA_CA_CERTS
* with behavior and capabilities close to those of Next.js
* includes hidden `jss environment --name FOO` command for debugging
Primarily to support NODE_EXTRA_CA_CERTS. In the Next.js getting started template, I want to populate this in `.env.local` with the mkcert root.
* Unit tests
* Newly added (hidden) CLI command

[Feature/459416] [sitecore-jss-cli] implemented .env handling for CLI

---

packages/sitecore-jss-nextjs/src/middleware/editing-render-middleware.test.ts
packages/sitecore-jss-nextjs/src/middleware/editing-render-middleware.ts
packages/sitecore-jss-nextjs/src/services/editing-data-service.test.ts
packages/sitecore-jss-nextjs/src/services/editing-data-service.ts

Use relative URLs for internal editing API requests instead of PUBLIC_URL which isn't always resolvable within containerized environments.

[NextJs] [EE] Use relative URLs for internal editing API calls

---

packages/sitecore-jss-nextjs/src/services/component-props-service.test.ts
packages/sitecore-jss-nextjs/src/services/component-props-service.ts

We should handle component props service errors correctly. Nextjs doesn't accept instance of Error in `getStaticProps`
1. Setup a Next.js environment with a deployed Styleguide app
1. Change the `url` on the GraphQL endpoint in Sitecore config, so that the URL which the app will request will be wrong
1. Deploy config
1. Attempt to load /graphql
**EXPECTED**
I see the ApolloError or other message indicating what's wrong with the GraphQL call
**ACTUAL**
I get a serialization error

[NextJs] Unhelpful error message when GraphQL query fails

---

packages/sitecore-jss-nextjs/src/middleware/editing-render-middleware.test.ts
packages/sitecore-jss-nextjs/src/middleware/editing-render-middleware.ts
packages/sitecore-jss-nextjs/src/services/editing-data-service.test.ts
packages/sitecore-jss-nextjs/src/services/editing-data-service.ts
packages/sitecore-jss-nextjs/src/sharedTypes/editing-data.ts

Root server URL detection/handling for internal editing API calls. Server URL is determined based on original `/api/editing/render` request host header, and presence of `VERCEL` for https protocol usage (http otherwise). This is then used for all subsequent page and data API calls.
The previous 2 attempts (using PUBLIC_URL and then relative requests) failed to provide stability across all necessary environments, configurations, and platforms by default. This aims to cover our "planned" scenarios, with the ability to override if necessary.

[NextJs] [EE] Root server URL detection/handling for internal editing API calls (take 2)

---

docs/data/routes/release-notes/en.md
packages/sitecore-jss-dev-tools/src/package-deploy.test.ts
packages/sitecore-jss-dev-tools/src/package-deploy.ts

When we run jss deploy items we check result from Sitecore using words from response string:
https://github.com/Sitecore/jss/blob/master/packages/sitecore-jss-dev-tools/src/package-deploy.ts#L130
but we should not depend on words, language - need to add a key, like: success, which will help us to indicate whether deploy items completed successfully or not.
Requires work on backend side and check key on frontend side
https://github.com/Sitecore/jss/issues/502
Implemented additional unit tests

[sitecore-jss-dev-tools] `jss deploy` doesn't exit on success

---

docs/data/routes/docs/client-frameworks/nextjs/nextjs-static-export/en.md
samples/nextjs/src/pages/[[...path]].tsx

Allow ISG (incremental static generation) for production by default. 
This is helpful when sitemap generation returns empty results. i.e. it removes dependency on Sitecore/server-side GraphQL query stability. This is also currently necessary for Experience Editor support on Vercel due to an [open issue with Next.js Preview Mode compatibility (on Vercel only)](https://github.com/vercel/next.js/issues/16681). In general, this seems like a more sensible default for folks starting out vs the more restrictive `fallback: false`.
This change has been tested locally (using `npm run start:production`) and on Vercel.

[NextJs] Switch sample to ISG by default for production mode

---

packages/sitecore-jss-nextjs/src/utils.ts
samples/nextjs/src/pages_examples/[[...path]].SSR.tsx

Fast Refresh fixes:
1. only run our EE handler in development, and
2. Add to `[[…path]].SSR.tsx`

[NextJs] Fast Refresh fixes

---

samples/nextjs/src/components/Layout.tsx
samples/nextjs/src/pages/[[...path]].tsx
samples/nextjs/src/pages_examples/[[...path]].SSR.tsx

Switched (back) to direct return for `SitecorePage`, as opposed to intermediary `PageLayout` function component. This was originally the fix for an issue with the `SitecoreContext` not being properly updated (see PR #491, PBI 446949). To resolve this issue, the `Layout.tsx` is now responsible for calling `setSitecoreContext` when layout data changes (which is a similar approach that React sample app takes). 
These changes fix the "Cannot read property 'parent' of null" issues that are seen in the Sitecore Experience Editor.
Tested locally in JSS disconnected, connected modes, and Next.js dev and production modes - both in Experience Editor and out.

[NextJs] [EE] Fix for "Cannot read property 'parent' of null" issues seen in the Sitecore Experience Editor

---

samples/nextjs/src/components/NotFound.tsx
samples/nextjs/src/lib/page-props-factory.ts
samples/nextjs/src/lib/page-props.ts
samples/nextjs/src/pages/[[...path]].tsx
samples/nextjs/src/pages_examples/[[...path]].SSR.tsx

Return `notFound` from getStatic/ServerSideProps. This will use the custom 404 page. Since we're now always using the custom 404 page, there's no use sending along layoutData.sitecore.context to the `NotFound` component in `SitecorePagePropsFactory` (not to mention this won't be possible with GraphQL/Edge once implemented).
This is necessary to properly return 404 status codes and also required in SSG for Next.js to delete ISR cached pages. 
Locally in both dev and prod modes.

[Next.js] Return notFound from getStatic/ServerSideProps

---

docs/data/routes/docs/client-frameworks/nextjs/nextjs-static-export/en.md
samples/nextjs/sitecore/config/JssNextWeb.config

Media URLs currently target CM/CD directly. Our configuration patch should configure the Layout Service by default to not include server URLs in media output, like the headless proxy:
https://jss.sitecore.com/docs/techniques/ssr/headless-mode-ssr#media-urls-in-headless-mode

[NextJS] Media should proxy through Next.js when using hosted Next

---

docs/data/routes/docs/nextjs/deploying-to-production/deployment-options/en.md

Overview of deployment options, mirroring [official Next.js docs](https://nextjs.org/docs/deployment) and including links to relevant off-site tutorials and discussions for likely common use cases / questions by Sitecore developers.

[doc] [NextJs] added doc w/ deployment options overview

---

docs/assets/css/jss-docs.css
docs/assets/css/sidenav.css
docs/sitecore/definitions/routes.sitecore.js
docs/src/app/components/SideNav.js

* ensure markdown sublists indent
* remove extra top/bottom padding on sublists
* expand clickable sidenav area to full sidenav width
* hide arrows while nav animates to avoid jumping

[doc] some UX improvements

---

samples/nextjs/src/pages/[[...path]].tsx
samples/nextjs/src/pages_examples/[[...path]].SSR.tsx

This fixes an issue with returning `notFound: false` from `getServerSideProps`, which is used in our SSR example route.
See related issue in Next.js [here](https://github.com/vercel/next.js/issues/22472).

[NextJs] Fix issue with returning notFound: false from getServerSideProps in SSR example

---

packages/sitecore-jss-cli/src/scripts/deploy.files.ts
samples/nextjs/package.json

As a JSS developer, I'd like to know that `jss deploy files` and `jss deploy app` are not relevant for Next.js, so that I have the correct expectations about capabilities and behavior of the SDK.
Next.js SDK does not support the 'node' view engine of Integrated mode, you must use the HTTP view engine and the Next.js API endpoints.
* The CLI should output an error such as "The current project does not support file deployment into the Sitecore instance. You should use an HTTP POST based integration for Experience Editor support. See SDK documentation for details."
* `deploy config` should still be supported.

[JSS] Disallow file deploy for Next.js solutions

---

samples/nextjs/src/Layout.tsx
samples/nextjs/src/pages/[[...path]].SSR.tsx
samples/nextjs/src/pages/[[...path]].tsx

The type of `route` was recently changed from `RouteData` to `RouteData | null`
Even though we never tried to render <Layout> when route is null, the possibility of null made TypeScript complain. My workaround is to rely on [[...path]] to build the `context` object since it is aware of whether `route` is null or not

470753 Fix type errors related to Route | null type in the Next.js sample app

---

docs/data/routes/docs/fundamentals/troubleshooting/debug-logging/en.md
packages/sitecore-jss/src/debug.ts

Added `DEBUG_MULTILINE` environment variable to allow switching from our default `%o` (pretty-print single line) to `%O` (pretty-print multiple line) formatting.
This is a follow-up to #645.
In some cases it could be preferred to use multiline formatting. This provides that option.

[JSS] [NextJs] Debug logging multi line toggle

---

packages/sitecore-jss-angular/package-lock.json
packages/sitecore-jss-angular/package.json
packages/sitecore-jss-angular/src/components/image.directive.spec.ts
packages/sitecore-jss-cli/package-lock.json
packages/sitecore-jss-dev-tools/package-lock.json
packages/sitecore-jss-forms/package-lock.json
packages/sitecore-jss-forms/package.json
packages/sitecore-jss-manifest/package-lock.json
packages/sitecore-jss-proxy/package-lock.json
packages/sitecore-jss-react-forms/package-lock.json
packages/sitecore-jss-react-native/package-lock.json
packages/sitecore-jss-react/package-lock.json
packages/sitecore-jss-react/package.json
packages/sitecore-jss-react/src/components/Image.test.tsx
packages/sitecore-jss-rendering-host/package-lock.json
packages/sitecore-jss-tracking/package-lock.json
packages/sitecore-jss-tracking/package.json
packages/sitecore-jss-update-package/package-lock.json
packages/sitecore-jss-vue/package-lock.json
packages/sitecore-jss-vue/package.json
packages/sitecore-jss-vue/src/components/Image.test.ts
packages/sitecore-jss/package-lock.json
packages/sitecore-jss/package.json
packages/sitecore-pipelines/package-lock.json
samples/angular/package-lock.json
samples/react/package-lock.json
samples/vue/package-lock.json

This address 2 npm dependencies with known vulnerabilities:
1. **url-parse** - url-parse@1.4.7 has the following vulnerability: https://nvd.nist.gov/vuln/detail/CVE-2021-27515. It is fixed in 1.5.0+. Where possible, this dependency was removed completely from packages (only being used for testing - node [URL](https://nodejs.org/api/url.html) used instead).
2. **y18n** - y18n@4.0.0 has the following vulnerability: https://www.npmjs.com/advisories/1654. It is fixed in 4.0.1+.

NPM package security update: 'url-parse' and 'y18n'

---

CONTRIBUTING.md

CONTRIBUTING.md brought up to speed with latest node/npm version and default branch

---

docs/data/routes/release-notes/en.md
packages/sitecore-jss-nextjs/src/components/RichText.tsx

If you click a link inside a RichText control, the target page will be loaded twice.
The cause of issue was that `useEffect` was called twice, because `dependencies` argument wasn't provided, so `removeEventListeners` can be removed.

[sitecore-jss-nextjs] Links inside RichText control cause page to be loaded twice

---

docs/data/routes/release-notes/en.md
samples/node-headless-ssr-proxy/config.js
samples/node-headless-ssr-proxy/index.js

When you refresh /graphql page, angular sample doesn't provide `accept-encoding` header, but before fix we setup it on every request. If request contains `accept-encoding` we should setup it, if not - just skip.
Interesting that when you refresh another page, request will contain `accept-encoding` header with value `gzip, deflate, br`.
The issue is coming from PR #461, when we started to setup `accept-encoding` on every request

[node-headless-ssr-proxy + Angular sample] Error in console when refresh /graphql page

---

docs/data/routes/release-notes/en.md
packages/sitecore-jss-forms/src/JssFormData.test.ts
packages/sitecore-jss-forms/src/JssFormData.ts

Fixes an issue where pre-filled (default) form data isn't removed for multi-valued fields when user de-selects values.
1. Create a JSS form rendering in your React app as described [here](https://jss.sitecore.com/docs/techniques/forms#sitecore-forms--jss).
2. Create a new Sitecore Form with a Checkbox List and Submit button.
3. In the Checkbox List settings create two static list items: CheckOne and CheckTwo.
4. In the Checkbox List settings select the first CheckOne as a default value.
5. In the Submit button settings add the Save Data action.
6. Add the Form you created to some JSS site page.
7. Open the page on frontend and perform some tests:
- Leave the first checkbox enabled and submit
- Check both checkboxes and submit
- Uncheck both checkboxes and submit (bug scenario)
8. On the …

[sitecore-jss-forms] Fix for multi-valued fields with pre-filled form data

---

docs/data/routes/docs/nextjs/getting-started-nextjs/walkthrough-jsscreate/en.md

modified second point regarding deploying the nextjs app to site
It is confusing as on https://jss.sitecore.com/docs/nextjs/getting-started-nextjs/how-is-nextjs-different page, it says that you don't have to deploy next.js jss app to sitecore but on this page it is saying that you have to follow the same deployment approach as in react/angular app.
I was trying to setup nextjs and encountered this problem
documentation change only
documentation change only
documentation change only

modified second point regarding deploying the nextjs app to sitecore

---

samples/nextjs/sitecore/config/JssNextWeb.config

Added IncludeServerUrlInMediaUrls "default" configuration to Next.js sample config (necessary for Sitecore GraphQL Edge requests).

[NextJs] Added IncludeServerUrlInMediaUrls "default" configuration to sample config

---

packages/sitecore-jss-nextjs/src/services/graphql-sitemap-service.ts

Make the GraphQLSitemapService easier to customize/extend

GraphQLSitemapService - allow overriding of default query and search service

---

docs/data/routes/docs/client-frameworks/getting-started/quick-start/en.md
docs/data/routes/docs/techniques/ssr/sitecore-experience-edge/en.md
docs/src/app/components/Navigation/docs.js

Adds documentation for the new starter template for SSR using a Sitecore Experience Edge endpoint as requested in PBI 474350.
It includes a nav menu link under  `techniques/ssr/`.

[Docs][474350] Document the new starter template for SSR

---

packages/sitecore-jss/src/layout/rest-layout-service.test.ts
packages/sitecore-jss/src/layout/rest-layout-service.ts
samples/nextjs/src/lib/layout-service-factory.rest.ts

There are "jss" and "default" Layout Service configurations available in Sitecore. JSS's GraphQLLayoutService is fine using the "jss" configuration, which is the default. But for RestLayoutService, we need to be able to override the configuration to "default". This override is now possible by passing a "configurationName" arg in layout-service-factory
Tested locally with the following configurations
SSG/GraphQL
SSG/Rest
SSR/GraphQL
SSR/Rest
Docs - I'm adding mention of this new option to my branch on new services docs since it includes content on the new factories

Rest Layout Service - Allow override of "named" JSS configuration

---

docs/data/routes/docs/nextjs/graphql/sample-app/en.md
docs/src/app/components/Navigation/nextjs.js

A Next.js app using GraphQL for layout / dictionary data (e.g. `jss create my-app nextjs --fetchWith GraphQL`) will not be able to run in disconnected mode (i.e. `jss start`). This is because the disconnected proxies emulate the REST services only.

[Doc] [NextJS] GraphQL + Disconnected mode compatibility

---

docs/data/routes/docs/nextjs/graphql/sample-app/en.md
docs/src/app/components/Navigation/nextjs.js
samples/angular/src/index.html

Added `<base href="/">` to `index.html` of the Angular sample app as to solve error when navigating directly to the Danish styuleguide page in either connected or disconnected mode.
Reference: https://github.com/angular/angular-cli/issues/10325#issuecomment-399329033
bugfix
tested locally in connected and disconnected mode.
- [ x ] Bug fix (non-breaking change which fixes an issue)

[JSS][angular] dk-DA language is not rendered in connected and disconnected mode 

---

docs/data/routes/docs/nextjs/graphql/sample-app/en.md
docs/src/app/components/Navigation/nextjs.js
packages/sitecore-jss-nextjs/src/middleware/editing-render-middleware.ts

Prevent extraneous router.replace (and resulting 404 in certain route configurations) in Experience Editor when using SSG.
When SSG, Next will [attempt to perform a router.replace on the client-side](https://github.com/vercel/next.js/blob/v10.0.3/packages/next/client/index.tsx#L169) to inject the query string parms to the router state. However, this doesn't really work since at this point we're in the editor and the location.search has nothing to do with the Next route/page we've rendered. Beyond the extraneous request, this can result in a 404 with certain route configurations (e.g. multiple catch-all routes).
This fix swaps out injected SSG property w/ SSR to trick it into thinking we're SSR, thus avoiding any router.replace.
Tested locally in Experience Editor and Horizon.

[Next.js] Prevent extraneous router.replace in Experience Editor when using SSG

---

samples/nextjs/sitecore/config/JssNextWeb.config

layoutServiceConfiguration should be set to "default" when using Delivery Edge for API endpoints. When using integrated GraphQL with Delivery Edge, a $language value is injected since language is required in all Edge queries. XP does not do this (which is backwards compatible with JSS versions < 18.0.0). Since GraphQL does not play nice with passing inunused parameters to queries, we need to tell Sitecore type of GraphqL endpoint we are using.

Update Next.js sample config - layoutServiceConfiguration="default"

---

docs/data/routes/docs/nextjs/data-fetching/customizing-static-paths/en.md
docs/src/app/components/Navigation/nextjs.js

[Docs][Next.js] Add walkthrough for customizing static paths

---

samples/nextjs/src/components/graphql/GraphQL-ConnectedDemo.dynamic.tsx

Call `resetEditorChromes` on `mount` event

[NextJS] [Horizon] GraphqlConnectedDemo - not selectable before chromesReset is called

---

packages/sitecore-jss-react/src/components/Placeholder.test.tsx
packages/sitecore-jss-react/src/components/Placeholder.tsx

The issue that markup doesn't contain empty placeholder tag.
How it's working:
**In Experience Editor:**
* On page load EE inserts empty placeholder tag
* React removes empty placeholder tag because our `<Placeholder />` component doesn't get data for empty placeholder (it contains only data for two `<code />` tags)
* When Sitecore scripts loaded, EE inserts empty placeholder tag second time
**In Horizon:**
* During initialization Horizon inserts empty placeholder tag.
* React removes empty placeholder tag because our <Placeholder /> component doesn't get data for empty placeholder (it contains only data for two `<code />` tags)
* As a result we have only two `<code />` tags under `<div class='container' >`, without empty placeholder tag
**Solution:**
Take empty placeholder tags and …

[Horizon] Empty placeholder / initial load issue

---

packages/sitecore-jss-react/src/components/PlaceholderCommon.tsx
packages/sitecore-jss-react/src/testData/ee-data.ts

[sitecore-jss-react] Error rendering raw self-closing tag elements in placeholders

---

samples/angular/src/app/components/content-block/content-block.component.html
samples/nextjs/src/components/ContentBlock.tsx
samples/react/src/components/ContentBlock/index.js

Added wrapping div to ContentBlock component for all frameworks. This brings consistency (Vue already does this), but importantly this is required for Horizon editor compatibility.

[Horizon] Added wrapping div to ContentBlock component for all frameworks

---

samples/node-headless-ssr-proxy/config.js

Remove '/dist' path from `pathRewriteExcludeRoutes` in node-headless-ssr-proxy config because it is not needed, as the Express server is already set up to handle requests to '/dist'.
Delete redundant/unused code

[node-headless-ssr-proxy] Remove '/dist' path from 'pathRewriteExcludeRoutes' config property.

---

docs/data/routes/docs/fundamentals/services/dictionary/jss-dictionary-api/en.md
docs/data/routes/docs/fundamentals/services/layout/jss-layout-api/en.md
docs/data/routes/docs/nextjs/services/graphql-sitemap-service/en.md

Adds ref doc links to Next.js GraphQLSitemapService, JSS Layout API and JSS Dictionary API documentation.

[Docs] Add ref docs links

---

docs/data/routes/docs/techniques/forms/en.md

[Docs][489110] Add example and config for Forms in Next.js app + small fixes

---

packages/sitecore-jss-react-forms/src/components/field-templates/button.test.tsx
packages/sitecore-jss-react-forms/src/components/field-templates/button.tsx
packages/sitecore-jss-react-forms/src/components/field-templates/file-upload.test.tsx
packages/sitecore-jss-react-forms/src/components/form.test.tsx
packages/sitecore-jss-react-forms/src/components/form.tsx

- Use css class applied to `form` or `button` components.
- Cover `form`, `button` components by unit tests

[sitecore-jss-react-forms] Experience Forms JSS React implementation doesn't use CSS class applied to entire form

---

samples/angular/sitecore/config/JssAngularWeb.config
samples/react/sitecore/config/JssReactWeb.config
samples/vue/sitecore/config/JssVueWeb.config

This is needed for RAV when fetching with GraphQL

[RAV] Add missing property to config

---

packages/sitecore-jss/src/utils/editing.ts

When adding a new page in Horizon, it's possible that this window-level function is not defined when called.

[Horizon] Extra check for window-level Horizon chrome reset function

---

samples/nextjs/next.config.base.js

…when app started first time
Create a new nextjs sample
Run `jss build` or `jss start:production`
The following error occurs:
- ModuleNotFoundError: Module not found: Error: Can't resolve 'sitecore/manifest/sitecore-import.json' in 'C:\WIP\_TEMP\JSS\jss-next-dev\src\lib'. This is referenced in `/lib/sitemap-fetcher.ts` of the sample app.

[NextJS] Prevent webpack-5 to throw error for `sitecore-import.json` when app started first time

---

packages/sitecore-jss/src/media-api.ts

Import `lodash.unescape` instead of `lodash/unescape`

[sitecore-jss] Import lodash correctly

---

packages/sitecore-jss-cli/src/create/index.test.ts
packages/sitecore-jss-cli/src/create/index.ts
samples/angular/jss-create.js
samples/react/jss-create.js
samples/vue/jss-create.js

Set `/sitecore/api/graph/edge` graphqlEndpointPath as default one when use `jss create`

[sitecore-jss-cli] RAV fetchWith uses old GraphQl endpoint path in package.json

---

samples/angular/sitecore/config/JssAngularWeb.config
samples/react/sitecore/config/JssReactWeb.config
samples/vue/sitecore/config/JssVueWeb.config

Removed Sitecore config patch for `<IncludeServerUrlInMediaUrls>false</IncludeServerUrlInMediaUrls>` in RAV samples. This should only be disabled for the Next.js sample and for RAV when using the SSR Proxy.

[RAV] Include Sitecore server URL in media URLs by default (regression)

---

CHANGELOG.md
samples/react/src/setupProxy.js

When running React in connected mode against development environments, proxied Sitecore requests (visitor identification, media, etc) may result in 504 (Gateway Timeout) errors. Setting [`changeOrigin: true`](https://github.com/chimurai/http-proxy-middleware/tree/v0.21.0#readme) resolves this issue.

[React] Set `changeOrigin: true` for proxied Sitecore requests in connected mode

---

samples/angular/src/app/layout/jss-layout.service.ts

The new `Rest/GraphQLLayoutService` implementations do not return HTTP 404 status. Instead, a 200 is returned and a missing route value signifies not found.
Tested in disconnected and connected modes locally.

[Angular] [Regression] Fix handling of not found layout service requests in Angular sample

---

CHANGELOG.md
samples/angular/sitecore/definitions/templates/Styleguide-Explanatory-Component.sitecore.ts
samples/react/sitecore/definitions/templates/Styleguide-Explanatory-Component.sitecore.js
samples/vue/sitecore/definitions/templates/Styleguide-Explanatory-Component.sitecore.js
samples/vue/src/temp/GraphQLFragmentTypes.json

Update template id which was missing the prefix for RAV and was causing warnings on importing items.
Also update vue graphql fragment data

[RAV] Fix Template id for styleguide-explanatory-component-template & vue graphql fragment data

---

packages/sitecore-jss-cli/src/create/index.test.ts
packages/sitecore-jss-cli/src/create/index.ts
samples/vue/sitecore/definitions/components/ContentBlock.sitecore.js

This pr updates the `getPascalCaseName` function to handle app names including underscore. Unit test also added.

[CLI] Handle underscores in app name when replacing prefix

---

packages/sitecore-jss-cli/src/create/index.ts

Ignore .pdf and .png from the glob command so that these files aren't accidently edited and corrupted.

[CLI] Ignore pdf and images when replacing or stripping prefix

---

package.json
scripts/install-hooks.js
scripts/installHooks.js

Add a script that 'installs' a pre-commit hook which will lint packages and apps on ~~commit~~ push. If you'd like to skip this hook, add the `--no-verify` flag to your ~~commit~~ push i.e. `git push origin head --no-verify`
Instead of waiting for CI to potentially fail due to unlinted apps/packages, we want to catch those errors locally.

[Focused improvement] Add a linting gate for git push actions

---

packages/sitecore-jss-nextjs/src/index.ts
packages/sitecore-jss-react/src/components/SitecoreContext.test.tsx
packages/sitecore-jss-react/src/components/SitecoreContext.tsx
packages/sitecore-jss-react/src/components/VisitorIdentification.tsx
packages/sitecore-jss-react/src/enhancers/withDatasourceCheck.tsx
packages/sitecore-jss-react/src/enhancers/withSitecoreContext.tsx
packages/sitecore-jss-react/src/index.ts
samples/nextjs/src/Layout.tsx
samples/nextjs/src/components/graphql/GraphQL-Layout.tsx
samples/nextjs/src/components/styleguide/Styleguide-CustomRouteType.tsx
samples/nextjs/src/components/styleguide/Styleguide-Layout-Tabs-Tab.tsx
samples/nextjs/src/components/styleguide/Styleguide-RouteFields.tsx
samples/nextjs/src/components/styleguide/Styleguide-SitecoreContext.tsx
samples/nextjs/src/lib/component-props.ts
samples/nextjs/src/lib/page-props-factory.ts
samples/nextjs/src/lib/page-props.ts
samples/nextjs/src/pages/[[...path]].SSR.tsx
samples/nextjs/src/pages/[[...path]].tsx
samples/react/src/AppRoot.js
samples/react/src/Layout.js
samples/react/src/RouteHandler.js

* `<SitecoreContext/>` from `sitecore-jss-react` package should have exact type for `context` state
* React sample should work as expected in connected/headless/integrated modes
* Nextjs sample should work as expected using SSG/SSR modes
* `<Layout/>` component shouldn't run `render` when it's unnecessary
* (Additional issue which I noticed and fixed) Previously when you tried to switch language on the /styleguide page react re-rendered `<Layout />` component twice. Now it's fixed and it was happening b\c we rendered array of routes, see https://github.com/Sitecore/jss/pull/841/files#diff-b6f3b4055f9147512d69014aa8a1d1df8d4c129713f504a4ca597c75e224bb49R37-R39
`updateSitecoreContext` should trigger update for layout. Test it using:
// withSitecoreContext({ updatable: true }); 
// …

[React] [Next.js] Strongly typed SitecoreContext value

---

packages/sitecore-jss-angular/src/public_api.ts
packages/sitecore-jss-cli/src/create/index.ts
samples/nextjs/.eslintrc
samples/react/.eslintrc

- add lint --fix to create after replace prefix
- fix lint error in angular package
- reorder .eslintrc prettier plugin
fix `jss create`
ran `jss create very-long-appname-that-will-surely-cause-problems app --source .` with fix applied, then built resulting code successfully.

Prettier issue when performing jss build or jss deploy using long prefix

---

packages/sitecore-jss-nextjs/src/middleware/editing-render-middleware.test.ts
packages/sitecore-jss-nextjs/src/middleware/editing-render-middleware.ts

Handle 404 error from Vercel when we use `fallback: false`

[Next.js] Preview Mode doesn't work with fallback: false on Vercel

---

packages/sitecore-jss-nextjs/src/components/Link.test.tsx
packages/sitecore-jss-nextjs/src/components/Link.tsx

Prevented passing `internalLinkMatcher` prop to React Link component as it is an invalid HTML element prop.
While attempting to use a custom link matcher (`/^\/|^\#/g`) to allow internal anchor links, an error occurred for all non-internal link values used in the same component.
When a non-internal link is detected, it attempts to pass all props, including the unused `internalLinkMatcher` to the JSS React Link component, which then attempts to print it onto the anchor link, resulting in the following error:
```
Warning: React does not recognize the `internalLinkMatcher` prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase `internallinkmatcher` instead. If you accidentally passed it from a parent component, remove it from the …
```

[JSS][NextJS] - fix: Prevent passing internalLinkMatcher prop

---

packages/sitecore-jss-vue/src/components/PlaceholderCommon.ts
packages/sitecore-jss-vue/src/components/__snapshots__/Placeholder.test.ts.snap
samples/vue/package.json
yarn.lock

* It's impossible to set `key` using Vue 3 attributes, we can manipulate it after DOM render is finished.
* Fixed `apollo-client` version, new version has breaking changes for us

[Vue] [Authoring] 'Add here' modal does not show allowed items on placeholder

---

packages/create-sitecore-jss/src/initializers/node-headless-ssr-proxy/index.ts
packages/create-sitecore-jss/src/templates/nextjs/.vscode/launch.json
packages/create-sitecore-jss/src/templates/node-headless-ssr-proxy/.vscode/launch.json
packages/create-sitecore-jss/src/templates/node-headless-ssr-proxy/LICENSE.txt
packages/create-sitecore-jss/src/templates/node-headless-ssr-proxy/README.md
packages/create-sitecore-jss/src/templates/node-headless-ssr-proxy/cacheMiddleware.js
packages/create-sitecore-jss/src/templates/node-headless-ssr-proxy/config.js
packages/create-sitecore-jss/src/templates/node-headless-ssr-proxy/error.html
packages/create-sitecore-jss/src/templates/node-headless-ssr-proxy/httpAgents.js
packages/create-sitecore-jss/src/templates/node-headless-ssr-proxy/index.js
packages/create-sitecore-jss/src/templates/node-headless-ssr-proxy/package.json

**!!PLEASE DO NOT MERGE!!**
Note, decided _not_ to make enhancements to drive `config.js` with prompted values (e.g. `appName`). Those enhancements could be made later on (for example when introducing a .env). For now, we have 100% parity with existing sample / jss create.

Initializer for `node-headless-ssr-proxy` sample

---

packages/create-sitecore-jss/src/common/utils/helpers.test.ts
packages/create-sitecore-jss/src/common/utils/helpers.ts
packages/create-sitecore-jss/src/templates/nextjs-styleguide/sitecore/definitions/components/graphql/GraphQL-IntegratedDemo.sitecore.graphql
packages/create-sitecore-jss/src/templates/nextjs-styleguide/src/components/graphql/GraphQL-ConnectedDemo.dynamic.graphql
packages/create-sitecore-jss/src/templates/nextjs-styleguide/src/components/graphql/GraphQL-ConnectedDemo.dynamic.tsx
packages/create-sitecore-jss/src/templates/nextjs/src/temp/GraphQLIntrospectionResult.json

Added option to exclude hyphen in `getAppPrefix` ejs helper. Use for GraphQL prefixes (as hyphens are not supported in GQL schemas).

Added option to exclude hyphen in getAppPrefix helper. Use for GraphQL prefixes.

---

packages/create-sitecore-jss/src/templates/nextjs/package.json
packages/create-sitecore-jss/src/templates/nextjs/src/Layout.tsx
packages/create-sitecore-jss/src/templates/nextjs/src/pages/[[...path]].tsx

Removing `withSitecoreContext` from the `Layout.tsx` because it's should be used in case if somebody updates context using `updateSitecoreContext`, but in the sample we don't use such approach

[Next.js] Remove withSitecoreContext HOC from `Layout.tsx`

---

packages/create-sitecore-jss/src/templates/vue/server/server.js
packages/create-sitecore-jss/src/templates/vue/src/AppRoot.vue
packages/sitecore-jss-vue/src/components/PlaceholderCommon.ts
packages/sitecore-jss-vue/src/components/__snapshots__/Placeholder.test.ts.snap

[Vue][Horizon] Cannot add a new rendering or highlight existing

---

CONTRIBUTING.md
packages/create-sitecore-jss/src/index.ts
packages/create-sitecore-jss/src/init-runner.ts
packages/create-sitecore-jss/src/initializers/angular/index.ts
packages/create-sitecore-jss/src/initializers/nextjs-styleguide/index.ts
packages/create-sitecore-jss/src/initializers/nextjs/index.ts
packages/create-sitecore-jss/src/initializers/react-native/index.ts
packages/create-sitecore-jss/src/initializers/react/index.ts
packages/create-sitecore-jss/src/initializers/vue/index.ts
packages/create-sitecore-jss/src/templates/react/sitecore/definitions/components/Styleguide-FieldUsage-Checkbox.sitecore.js

This includes a batch of fixes for issues found during QA of initializers.
- 513110 Added early validation of provided templates, ignoring unknown. Provides better UX and alleviates some of the pain with npm 8.3.x option forwarding (not working with npm init/create)
- 513126 Added coercion of string parameters
- 513131 `--yes` handling for language and add-on initializers
- 513796 fixed app prefix missing hyphen for React `Styleguide-FieldUsage-Checkbox.sitecore.js`
- 513797 513797 fixed angular defaults/args precedence
- Misc language fixes

Initializer fixes

---

packages/create-sitecore-jss/src/common/prompts/base.ts
packages/create-sitecore-jss/src/common/prompts/styleguide.ts
packages/create-sitecore-jss/src/index.ts
packages/create-sitecore-jss/src/initializers/angular/index.ts
packages/create-sitecore-jss/src/initializers/nextjs-styleguide/index.ts
packages/create-sitecore-jss/src/initializers/nextjs/index.ts
packages/create-sitecore-jss/src/initializers/nextjs/prompts.ts
packages/create-sitecore-jss/src/initializers/react-native/index.ts
packages/create-sitecore-jss/src/initializers/react-native/prompts.ts
packages/create-sitecore-jss/src/initializers/react/index.ts
packages/create-sitecore-jss/src/initializers/vue/index.ts

Another round of fixes addressing the following:
- 514353 Fix inconsistency with default values applied in `--yes` mode across initializers. Responsibility is now owned by the individual prompts themselves (using inquirer "when").
- 514355 Handle multiple templates on positional parameter as well

Initializer fixes (round 2)

---

packages/create-sitecore-jss/src/templates/angular/src/app/components/content-block/content-block.component.html
packages/create-sitecore-jss/src/templates/angular/src/styles.css
packages/create-sitecore-jss/src/templates/react/src/assets/app.css
packages/create-sitecore-jss/src/templates/react/src/components/ContentBlock/index.js
packages/create-sitecore-jss/src/templates/vue/src/assets/app.css
packages/create-sitecore-jss/src/templates/vue/src/components/ContentBlock.vue

* NextJS tests are failing because we are validating the ContentBlock content by checking the classname
* We should have same the classname for each framework

[RAV] Change the classname of ContentBlock from display-4 to contentTitle

---

packages/create-sitecore-jss/src/templates/nextjs-styleguide/src/lib/next-config/plugins/disconnected.js

* We shouldn't remove default `fallback` options provided by nextjs, in another case it throws an error

[NextJS] Can't start app in disconnected mode, throws webpack `fallback` option error

---

packages/create-sitecore-jss/src/common/processes/install.ts
packages/create-sitecore-jss/src/common/utils/cmd.test.ts
packages/create-sitecore-jss/src/common/utils/cmd.ts

`npm i` hangs if `create-sitecore-jss` is executed from the powershell script. Pipe uses parent's std channel, `inherit` can't be used

[Initializers] Remove `inherit` stdio setting

---

packages/create-sitecore-jss/src/templates/node-headless-ssr-experience-edge/index.js
packages/create-sitecore-jss/src/templates/node-headless-ssr-proxy/config.js

As the base packages were refactored and the @sitecore-jss base package was broken down into submodules, the submodules import was not refactored in the `node-headless-ssr-experience-edge` and `node-headless-ssr-proxy` apps.
`npm start` works as expected after updating imports.

[Node-headless-ssr-experience-edge/ proxy] Fix for error while running `npm start` on headless apps

---

packages/create-sitecore-jss/src/templates/angular/package.json

Latest `angular-devkit/build-angular` compatible with `angular 11` package contains latest `postcss` which has fix for deprecation error

[Angular] Update angular-devkit/build-angular to fix deprecation error

---

packages/create-sitecore-jss/src/templates/nextjs-styleguide/src/lib/next-config/plugins/disconnected.js
packages/create-sitecore-jss/src/templates/nextjs/next.config.js

Use more focused paths for Sitecore rewrites (similar to RAV / headless proxy) to avoid interference with allowed path "/sitecore/templates". This fixes an issue which prevented template standard values from being edited in Sitecore.

[Next.js] Use more focused paths for Sitecore rewrites

---

packages/create-sitecore-jss/src/templates/angular/package.json
packages/create-sitecore-jss/src/templates/angular/scripts/bootstrap.ts
packages/create-sitecore-jss/src/templates/nextjs/scripts/bootstrap.ts
packages/create-sitecore-jss/src/templates/react/package.json
packages/create-sitecore-jss/src/templates/react/scripts/bootstrap.js
packages/create-sitecore-jss/src/templates/vue/package.json
packages/create-sitecore-jss/src/templates/vue/scripts/bootstrap.js
packages/sitecore-jss-nextjs/tsconfig.json
packages/sitecore-jss/src/constants.ts

The user should see a friendly error message when they try to run jss start i.e disconnected mode when fetchWtih is set to 'GraphQL'.

Throw error when run jss start using FETCH_WITH=GraphQL

---

packages/sitecore-jss-nextjs/src/components/Link.test.tsx
packages/sitecore-jss-nextjs/src/components/Link.tsx
packages/sitecore-jss-react/src/components/Link.test.tsx
packages/sitecore-jss-react/src/components/Link.tsx

Sitecore allows configuration of a query string for internal links. Make sure these are rendered properly for React (anchor) and NextJs (next/link).
This PR also fixes an issue for NextJs where the rendered markup would contain invalid attributes e.g. `field="[object Object]"`.

[React][NextJs] Handle Sitecore `querystring` property in Link component

---

packages/create-sitecore-jss/src/templates/angular/scripts/bootstrap.ts
packages/create-sitecore-jss/src/templates/nextjs/scripts/bootstrap.ts
packages/create-sitecore-jss/src/templates/react/scripts/bootstrap.js
packages/create-sitecore-jss/src/templates/vue/scripts/bootstrap.js

Highlighted the error message thrown when user starts the app in disconnected mode but `fetchWith=GaphQL`.
This would create a better user experience for the user.

Highlight error message for `fetchWith=GraphQL`

---

packages/create-sitecore-jss/package.json
packages/create-sitecore-jss/src/common/processes/install.ts
packages/create-sitecore-jss/src/common/utils/cmd.test.ts
packages/create-sitecore-jss/src/common/utils/cmd.ts
yarn.lock

We moved away from `inherit` for `stdio` in https://github.com/Sitecore/jss/pull/912 to address an issue with the `npm install` hanging when run within our dotnet template for Next.js. However, this resulted in a loss of useful output. This PR goes back to using `inherit` for `stdio` w/ fallback to `pipe` (when not TTY context).
Tested on Node.js LTS (16.10), including within dotnet template for Next.js

[Initializers] Restore sub-command (npm install / lint) console output

---

packages/sitecore-jss/src/utils/editing.ts

* Using 10.3 second dropdown item has `#!` instead of `!`, we have to check it

[Angular] [10.3] "Edit related item" button redirects to home

---

packages/sitecore-jss-vue/src/components/PlaceholderCommon.ts

* We have to reset EE chromes since sometimes experience editor script is executed earlier
than Vue script and EE can't set required attributes and chromes aren't visible

[VUE] Experience Editor controls does not work until hard reload is done

---

packages/sitecore-jss-react/src/components/Image.test.tsx
packages/sitecore-jss-react/src/components/Image.tsx

Fixes the issue with 'class' property not being handled property, after it is passed into Image component. 
This could lead to a console error in Experience Editor when displaying a placeholder image.
If "class" property is passed down from Layout Service it will be transformed into or appended to "className" instead.
Unit test added.

[sitecore-jss-react] Make Image handle 'class' prop when it's passed down

---

packages/sitecore-jss-vue/src/components/Link.test.ts
packages/sitecore-jss-vue/src/components/Link.ts

Make sure the query strings are rendered properly for Vue (anchor).

[Vue] Fix Sitecore querystring property in Link component

---

packages/create-sitecore-jss/src/templates/node-headless-ssr-experience-edge/README.md
packages/create-sitecore-jss/src/templates/node-headless-ssr-proxy/README.md
packages/create-sitecore-jss/src/templates/node-headless-ssr-proxy/cacheMiddleware.js
packages/sitecore-jss-proxy/src/ProxyConfig.ts
packages/sitecore-jss-proxy/src/index.ts
packages/sitecore-jss-proxy/src/test/config.test.ts

- Created a new interface LayoutServiceData in sitecore-jss-proxy/ProxyConfig.ts.
- Changed the shape of ProxyConfig interaface.
- Implemented the new LayoutServiceData in the sitecore-jss-proxy/index.ts.
- Typecast to replyWithError arg in sitecore-jss-proxy/index.ts.
- Removed the 'new' keyword from the cacheMiddleware.js file in the create-sitecore-jss/templates/node-headless-ssr-proxy. It was causing 'Only a void function can be called with the 'new' keyword.' error. 
- Added information to README.md files in create-sitecore-jss/node-headless-ssr-experience-edge and create-sitecore-jss/node-headless-ssr-proxy templates about the use of .env files

[Headless SSR Proxy] Fix shape of config object

---

packages/sitecore-jss-react/src/components/Image.test.tsx
packages/sitecore-jss-react/src/components/Image.tsx

[React] Adding srcSet to Image Component removes the src Attribute reducing compatibility with older browsers

---

packages/sitecore-jss-react/src/components/SitecoreContext.tsx

* Use context value as an object instead of class instance. Initially was fixed in #354

[JSS][React] SitecoreContextReactContext.Provider is not working properly, because value never changes as it is always same class instance

---

packages/create-sitecore-jss/src/templates/nextjs-sxa/src/components/Navigation.tsx
packages/create-sitecore-jss/src/templates/nextjs-sxa/src/components/Title.tsx

Update renderings due to the changes in [https://github.com/Sitecore/jss/commit/be48bd1d2e44818ffba85f8df11755ec9bf188d4](https://github.com/Sitecore/jss/commit/be48bd1d2e44818ffba85f8df11755ec9bf188d4)

#530659: [SXA][Headless] In preview mode links are broken because ? remains encoded

---

packages/sitecore-jss-nextjs/src/components/RichText.test.tsx
packages/sitecore-jss-nextjs/src/components/RichText.tsx

Fix to forward query params from the RichText component.

[Nextjs][SDK] RichText component not forwarding query params

---

packages/sitecore-jss-nextjs/src/edge/redirects-middleware.ts

decode URL when using query string. 
There was bug when redirects the URL where use query string in middleware redirects.
The problem was in special symbols(?) - they was encoding

 #530304 decode url for redirects

---

packages/create-sitecore-jss/src/templates/nextjs/package.json
packages/sitecore-jss-nextjs/package.json
yarn.lock

NextJs has bug in the version of 12.1.6 with middleware features. Just I set fixed version for our samples projects and sitecore-nextjs module

 #532998 temporary fix. set fix version of NextJs

---

packages/create-sitecore-jss/src/templates/nextjs-sxa/src/lib/middleware/plugins/redirects.ts
packages/sitecore-jss-nextjs/src/edge/redirects-middleware.ts

SXA Redirects middleware now checks the patterns for registered locales and updates the URL parameters accordingly.

#530555: [SXA][Headless] Redirects with defined language in source URL don't work

---

packages/create-sitecore-jss/src/templates/nextjs/scripts/templates/component-factory.ts
packages/create-sitecore-jss/src/templates/nextjs/src/pages/[[...path]].tsx

This change adds an extra method for componentFactory that will ensure dynamic nextjs components can be returned and rendered properly when adding renderings in Experience Editor
componentFactory is generated with two factory methods - and nextjs apps will use one or the other depending on the pageEditing sitecore context value.

[Nextjs] Dynamic components markup is missing in Experience Editor after adding new rendering

---

packages/create-sitecore-jss/src/templates/nextjs/scripts/templates/component-factory.ts

This fixes the optional param in component factory which could lead to errors building nextjs app.

Fixing optional params in component factory template

---

packages/sitecore-jss-vue/global.d.ts
packages/sitecore-jss-vue/package.json
packages/sitecore-jss-vue/src/components/RichText.test.ts
packages/sitecore-jss-vue/src/components/RichText.ts
packages/sitecore-jss-vue/tsconfig.json

- Changed how RichText handles internal links.
- Added unit tests for new functionality.

[Vue] RouteLinkedRichText

---

packages/create-sitecore-jss/src/templates/nextjs-styleguide/src/lib/next-config/plugins/disconnected.js
packages/create-sitecore-jss/src/templates/nextjs-styleguide/src/lib/next-config/plugins/styleguide.js
packages/create-sitecore-jss/src/templates/nextjs-sxa/src/lib/middleware/plugins/redirects.ts
packages/create-sitecore-jss/src/templates/nextjs-sxa/src/lib/next-config/plugins/robots.js
packages/create-sitecore-jss/src/templates/nextjs-sxa/src/lib/next-config/plugins/sitemap.js
packages/create-sitecore-jss/src/templates/nextjs/next.config.js
packages/create-sitecore-jss/src/templates/nextjs/src/lib/next-config/plugins/edge.js
packages/create-sitecore-jss/src/templates/nextjs/src/lib/next-config/plugins/graphql.js
packages/create-sitecore-jss/src/templates/nextjs/src/lib/next-config/plugins/monorepo.js

Fixes "debug module not found" error in redirects middleware.
Removes import of next.config.js in redirects middleware and use static values for now. next.config.js is not intended to be imported in this way. Will create follow-up to investigate approach to avoid duplicate locales configuration. Hopefully, we will have [access to locales directly in middleware](https://github.com/vercel/next.js/issues/37253).
Also includes type assist JSDoc comments for NextConfig.

[NextJs] Fix "debug module not found" error in redirects middleware

---

packages/sitecore-jss-react-forms/src/field-factory.tsx

`setComponents` supports only internal declared components.
We extend it for the ability to provide custom components
Related PR: https://github.com/Sitecore/jss/pull/875
This PR opened to fix lint issue and add change

[sitecore-jss-react] Allow to register custom field components

---

packages/create-sitecore-jss/src/templates/angular/src/app/components/styleguide-tracking/styleguide-tracking.component.ts
packages/sitecore-jss-angular/src/public_api.ts

Direct usage of `sitecore-jss` is not needed and cause a problem during the build stage

[Angular] Expose tracking functionality and remove direct usage of `sitecore-jss` module

---

packages/sitecore-jss/src/axios-fetcher.ts
packages/sitecore-jss/src/data-fetcher.test.ts
packages/sitecore-jss/src/data-fetcher.ts
packages/sitecore-jss/src/debug.ts
packages/sitecore-jss/src/graphql/app-root-query.ts
packages/sitecore-jss/src/i18n/dictionary-service.ts
packages/sitecore-jss/src/i18n/graphql-dictionary-service.ts
packages/sitecore-jss/src/i18n/rest-dictionary-service.ts
packages/sitecore-jss/src/layout/graphql-layout-service.ts
packages/sitecore-jss/src/layout/layout-service.ts
packages/sitecore-jss/src/layout/rest-layout-service.ts
packages/sitecore-jss/src/layout/utils.ts
packages/sitecore-jss/src/media/media-api.test.ts
packages/sitecore-jss/src/media/media-api.ts
packages/sitecore-jss/src/personalize/layout-personalizer.ts
packages/sitecore-jss/src/site/graphql-redirects-service.ts
packages/sitecore-jss/src/tracking/trackingApi.test.ts
packages/sitecore-jss/src/tracking/trackingApi.ts
packages/sitecore-jss/src/utils/resolve-url.ts
packages/sitecore-jss/src/utils/utils.test.ts

We would like the API described by our exports and Typedoc comments to be accurate and complete.
The functions that we export to our npm package should document the following:
> Purpose of the function 
> Description of parameters via @param
> Description of return possibilities via @returns
> A list of possible exceptions via @throws
Also added more unit tests wherever possible to improve test coverage.

[sitecore-jss] Audit API reference description for accuracy and completeness

---

packages/create-sitecore-jss/src/templates/nextjs-personalize/.env
packages/create-sitecore-jss/src/templates/nextjs-personalize/src/lib/middleware/plugins/personalize.ts
packages/create-sitecore-jss/src/templates/nextjs-personalize/src/lib/page-props-factory/plugins/personalize.ts
packages/sitecore-jss-nextjs/src/edge/personalize-middleware.ts
packages/sitecore-jss-nextjs/src/services/graphql-sitemap-service.test.ts
packages/sitecore-jss-nextjs/src/services/graphql-sitemap-service.ts
packages/sitecore-jss/src/personalize/cdp-service.test.ts
packages/sitecore-jss/src/personalize/cdp-service.ts
packages/sitecore-jss/src/personalize/graphql-personalize-service.test.ts
packages/sitecore-jss/src/personalize/graphql-personalize-service.ts
packages/sitecore-jss/src/personalize/index.ts
packages/sitecore-jss/src/personalize/layout-personalizer.test.ts
packages/sitecore-jss/src/personalize/layout-personalizer.ts
packages/sitecore-jss/src/personalize/utils.test.ts
packages/sitecore-jss/src/personalize/utils.ts
packages/sitecore-jss/src/test-data/personalizeData.ts

* Updates to reflect latest CDP API specs
* Switch from using "segments" (aka "Streaming Segments") to "variants" (aka "Experience Targeting") terminology
* Also exclude Sitecore API routes in personalize-middleware
Tested locally using mocked CDP API

[Next.js][Personalize] Switchover to Variants and latest CDP API

---

packages/create-sitecore-jss/src/templates/nextjs-sxa/src/assets/basic/_common.scss
packages/create-sitecore-jss/src/templates/nextjs-sxa/src/assets/basic/_component.scss
packages/create-sitecore-jss/src/templates/nextjs-sxa/src/assets/basic/_footer.scss
packages/create-sitecore-jss/src/templates/nextjs-sxa/src/assets/basic/_header.scss
packages/create-sitecore-jss/src/templates/nextjs-sxa/src/assets/basic/_navigation.scss
packages/create-sitecore-jss/src/templates/nextjs-sxa/src/assets/basic/_promo.scss
packages/create-sitecore-jss/src/templates/nextjs-sxa/src/assets/basic/_rich-text.scss
packages/create-sitecore-jss/src/templates/nextjs-sxa/src/assets/basic/main.scss
packages/create-sitecore-jss/src/templates/nextjs-sxa/src/components/Promo.tsx
packages/create-sitecore-jss/src/templates/nextjs-sxa/src/pages/_app.tsx

added additional styles for basic site(sxa initializer)

 #535917 added styles for sxa initializer(basic site)

---

packages/sitecore-jss/src/site/graphql-redirects-service.ts

There was error 'undefined .find method' on the redirects-middleware

 #hotfix: fixed return data of redirects

---

packages/sitecore-jss-proxy/src/ProxyConfig.ts
packages/sitecore-jss-proxy/src/index.ts

* Provide headers returned from `onError` to the response
* Using headers it's possible to enable redirect using `location` header
Related to issue #479 
[Repo](https://github.com/illiakovalenko/headless-proxy-authentication) that contains the reproduction of the authentication issue

[sitecore-jss-proxy] Provide headers to response when config.onError is called

---

packages/sitecore-jss-react/src/enhancers/withComponentFactory.tsx

To get around the missing component issue in nextjs SSR production we need to use the `useContext` hook within the HOC and pass the context down to the children components.

[sitecore-jss-react] Refactored `withComponentFactory` HOC

---

packages/create-sitecore-jss/src/common/index.ts
packages/create-sitecore-jss/src/common/utils/helpers.ts
packages/create-sitecore-jss/src/initializers/react/index.ts
packages/create-sitecore-jss/src/templates/react/config-overrides.js
packages/create-sitecore-jss/src/templates/react/package.json

* React throws `invalid hook call` error in case multiple `react` instances are used in the sample
* By default `yarn` doesn't solve duplicate `react` dependencies issue
* `react-app-rewire` provides way to customize webpack config for `create-react-app` template
* Provided `alias` for webpack config, to have a single `react` instance

[React] Resolve duplicate `react` instances issue

---

packages/sitecore-jss-react/package.json
packages/sitecore-jss-react/src/components/Link.tsx
yarn.lock

* Latest `react` 18 doesn't allow to render `dangerouslyInnerHtml` and `children` together, so we need to transform markup into React components and render that together

[sitecore-jss-react] Can't render Link component when Editable and Children are provided

---

CHANGELOG.md
packages/sitecore-jss-react/src/enhancers/withSitecoreContext.tsx

* Provide value using `hook` instead of `Provider` to fix the issue for react 17

[Nexjs] withSitecoreContext HOC doesn't provide context value

---

packages/sitecore-jss-react/src/components/VisitorIdentification.tsx

Add support for the `defer` prop to the `VisitorIdentification` component to support non-blocking script loading.
>This attribute allows the elimination of parser-blocking JavaScript where the browser would have to load and evaluate scripts before continuing to parse. async has a similar effect in this case.
Opt-in to make `VisitorIdentification` non-blocking.
Component does not have any tests.
Setting `defer` to `true` will render `<script defer ...></script>`.
Setting `defer` to `false` or `undefined` will render `<script ...></script>`.
Making the prop optional makes this a non-breaking change.

[sitecore-jss-react] Allow defer prop on VisitorIdentification component

---

packages/create-sitecore-jss/src/templates/react/server/server.webpack.config.js

* `html-react-parser` from `sitecore-jss-react` uses `htmlparser2` which uses `export * as ns from`: https://github.com/fb55/htmlparser2/issues/1237
* `webpack 4` doesn't support `export * as ns from`, and it's available by default only using `webpack 5`: https://github.com/webpack/webpack/issues/10460
* we can't upgrade webpack, cause we need to upgrade `create-react-app`, it has peer dep on `webpack`
* [@babel/plugin-proposal-export-namespace-from](https://babeljs.io/docs/en/babel-plugin-proposal-export-namespace-from) plugin allows to use `export * as ns from` in esm
Need to revisit webpack server config after the upgrade

[React] Module parse failed: Unexpected token, htmlparser2

---

packages/sitecore-jss/src/personalize/layout-personalizer.test.ts
packages/sitecore-jss/src/personalize/layout-personalizer.ts
packages/sitecore-jss/src/test-data/personalizeData.ts

* When variant is hidden it will have next structure
* Variant can't be null, so if we have `_default` variant, then component data will be used as a fallback

[Personalize] Middleware does not fallback to default variantID when route is not `/`

---

packages/create-sitecore-jss/src/templates/vue/scripts/disconnected-mode-proxy.js

After some analysis of the project, it seems the `compilers` option is not used anymore.  
It was renamed to `requireArg?: string | null;`
In general, I see that the Vue template is very outdated.
I'm working on a new template that uses Vite and supports TypeScript
https://github.com/jagaad/create-sitecore-jss-vue

[Vue] Fix compilers proxy options in template

---

packages/create-sitecore-jss/src/templates/nextjs/.babelrc
packages/create-sitecore-jss/src/templates/nextjs/package.json
packages/sitecore-jss-nextjs/package.json

Nextjs 12.2.4 fixes some issues - but reintroduces swc exception that happens in containers. This PR reintroduces babelrc file to avoid it.

Updating next to 12.2.4 - and reintroducing babel to avoid swc errors

---

packages/create-sitecore-jss/src/templates/nextjs-sxa/src/assets/sass/components/title/_component-title.scss

Experience Editor added it's markup in a `<span>`, which caused double underline. Changed the CSS to underline only immediate `<span>` and `<a>` children.

#544785: The title rendering is underlined with two lines

---

packages/create-sitecore-jss/src/templates/nextjs-sxa/src/assets/sass/components/_component-container.scss

Bootstrap 5 has a class named "container", which interferes with SXA Container rendering. I've set the `margin-right` and `margin-left` properties to `unset` in the Container rendering SCSS to fix this.

#544714: Wrong alignment for the Container component

---

packages/create-sitecore-jss/src/templates/nextjs/src/middleware.ts

This fixes the timeout error in EE by excluding the middleware paths.
NOTE: Should reverse this change once this gets fixed: https://github.com/vercel/next.js/issues/39262

[EE] Timeout error on CM when calling Next.js rendering host

---

packages/sitecore-jss-nextjs/src/components/RichText.test.tsx
packages/sitecore-jss-nextjs/src/components/RichText.tsx

Fix for _blank target in rich text links
Links in rich text fields will now correctly open new tab.
One extra unit test added

#546839: handle _blank target on links in rich text

---

packages/create-sitecore-jss/src/common/processes/transform.ts
packages/create-sitecore-jss/src/templates/react/server/server.webpack.config.js

* Resolves symlink issue for server bundle:
```
Error occurs:
Error Rendering Sitecore.JavaScriptServices.ViewEngine.Presentation.JsLayoutRenderer: Super expression must either be null or 
a function TypeError: Super expression must either be null or a function at _inherits 
(C:\inetpub\wwwroot\dist\react\server.bundle.js:947:11) at C:\inetpub\wwwroot\dist\react\server.bundle.js:21541:171 at 
Module.
```
* Resolves warnings presented in the console before

[React] App fails to open in Experience Editor/Headless ssr proxy

---

azure-pipelines.yml

Follow up to lint CI pull request
Disable scaffold and lint apps for publish CI runs to avoid git errors.

Disable scaffold apps during publish runs

---

packages/sitecore-jss-nextjs/package.json
packages/sitecore-jss-nextjs/src/edge/personalize-middleware.test.ts
packages/sitecore-jss-nextjs/src/edge/personalize-middleware.ts
packages/sitecore-jss-nextjs/src/tests/request.ts
packages/sitecore-jss-nextjs/src/tests/shim.ts
packages/sitecore-jss-nextjs/test/setup.js
packages/sitecore-jss/src/debug.ts
yarn.lock

* Unit tests for Personalize middleware
* Make `debug` object extendable for unit tests
* `setBrowserId` no need to check `browserId` anymore, it's always present, in another case request is skipped

[Next.js][Personalize] Unit tests for Personalize Middleware

---

packages/sitecore-jss-nextjs/src/services/graphql-sitemap-service.test.ts
packages/sitecore-jss-nextjs/src/services/graphql-sitemap-service.ts

* Handle `null` values fetched by `graphql-sitemap-service`
Related to #1102

[Next.js] Build error when null values received in graphql-sitemap-service.js

---

packages/create-sitecore-jss/src/templates/nextjs/.env
packages/create-sitecore-jss/src/templates/nextjs/src/pages/[[...path]].tsx

* Disable pages pre-render based on environment variable `DISABLE_SSG_FETCH` value

[Next.js] Add environment variable to allow disable of sitemap fetch in getStaticPaths

---

packages/create-sitecore-jss/src/templates/nextjs-sxa/src/Layout.tsx

Aligns Layout output between nexjs and sxa app templates so that Scripts component is used in both (instead of adding VisitorIdentification by default).

Add Scripts component to SXA layout

---

packages/sitecore-jss-nextjs/src/middleware/personalize-middleware.test.ts
packages/sitecore-jss-nextjs/src/middleware/personalize-middleware.ts
packages/sitecore-jss/src/personalize/cdp-service.test.ts
packages/sitecore-jss/src/personalize/cdp-service.ts

We need to make some adjustments to the CDP callFlows call (which occurs in personalize middleware) according to final specs.
- Removed `geo` from `params` (this is now being handled entirely on CDP-side via Cloudflare)
- Removed `ua` from `params` (moved to headers - see next)
- Added user agent to the callFlows fetch request headers ('User-Agent')
- Added ability to configure `channel` (default to 'WEB')
Local testing using mock CDP

[Next.js][Personalize] Finalize targeting experience call

---

CHANGELOG.md
packages/create-sitecore-jss/src/templates/nextjs-styleguide/src/pages/_app.tsx
packages/create-sitecore-jss/src/templates/nextjs-sxa/src/pages/_app.tsx
packages/create-sitecore-jss/src/templates/nextjs/src/lib/page-props.ts
packages/create-sitecore-jss/src/templates/nextjs/src/pages/_app.tsx

* Next 12.3.0 provides change to `AppPages` type, which requires to provide type for generic

[NextJs] Specify AppProps generic type in _app.tsx to align with latest changes from Next 12.3.0

---

packages/sitecore-jss-react/src/components/Placeholder.tsx

This adds a workaround for Experience Editor to make it work better with nextjs apps and avoid hydration errors that started occurring after next and react version upgrades.
React will add specific markup for empty placeholders in Experience Editor on first page load. This way it won't be "confused" by this markup when Experience Editor client side scripts add it.

Getting rid of hydration errors for nextjs pages in ExpEditor

---

packages/create-sitecore-jss/src/templates/angular/sitecore/definitions/components/graph-ql-integrated-demo.sitecore.graphql
packages/create-sitecore-jss/src/templates/angular/sitecore/definitions/routes.sitecore.ts
packages/create-sitecore-jss/src/templates/angular/src/app/components/graph-ql-connected-demo/graph-ql-connected-demo.component.graphql
packages/create-sitecore-jss/src/templates/angular/src/graphql-fragment-types.ts
packages/create-sitecore-jss/src/templates/nextjs-styleguide/sitecore/definitions/components/graphql/GraphQL-IntegratedDemo.sitecore.graphql
packages/create-sitecore-jss/src/templates/nextjs-styleguide/sitecore/definitions/routes.sitecore.ts
packages/create-sitecore-jss/src/templates/nextjs-styleguide/src/components/graphql/GraphQL-ConnectedDemo.dynamic.graphql
packages/create-sitecore-jss/src/templates/nextjs-styleguide/src/components/graphql/GraphQL-ConnectedDemo.dynamic.tsx
packages/create-sitecore-jss/src/templates/nextjs/src/temp/GraphQLIntrospectionResult.json
packages/create-sitecore-jss/src/templates/react/sitecore/definitions/components/GraphQL-IntegratedDemo.sitecore.graphql
packages/create-sitecore-jss/src/templates/react/sitecore/definitions/routes.sitecore.js
packages/create-sitecore-jss/src/templates/react/src/components/GraphQL-ConnectedDemo/query.graphql
packages/create-sitecore-jss/src/templates/react/src/temp/GraphQLFragmentTypes.json
packages/create-sitecore-jss/src/templates/vue/sitecore/definitions/components/GraphQL-IntegratedDemo.sitecore.graphql
packages/create-sitecore-jss/src/templates/vue/sitecore/definitions/routes.sitecore.js
packages/create-sitecore-jss/src/templates/vue/src/components/GraphQL/GraphQL-ConnectedDemo.query.graphql
packages/create-sitecore-jss/src/templates/vue/src/temp/GraphQLFragmentTypes.json

Rename AppRoute -> Page:
* graphql query
* introspection result
* definition files

Rename "App Route" to "Page"

---

packages/create-sitecore-jss/src/templates/nextjs-sxa/src/assets/sass/components/image/_image-banner.scss
packages/create-sitecore-jss/src/templates/nextjs-sxa/src/components/Image.tsx

added possibility to change image into banner variant of image component

 #545156: added possibility to change image 

---

packages/sitecore-jss-nextjs/src/middleware/personalize-middleware.test.ts
packages/sitecore-jss-nextjs/src/middleware/personalize-middleware.ts

Making sure the excludeRoutes from middleware constructor only adds exclude routes and doesn't override the default ones.
One unit test changed.

Fix middleware activating for favicon.ico and other paths

---

packages/sitecore-jss-nextjs/src/middleware/personalize-middleware.ts
packages/sitecore-jss/src/native-fetcher.ts

Fixing the issue when user-agent was ignored in fetcher when executing CDP experience.
To be further tested on Vercel or with mock.

Ensure headers from middleare are passed into NativeFetcher

---

packages/create-sitecore-jss/src/templates/nextjs-sxa/src/assets/sass/components/_component-column-splitter.scss

Change padding styles for Splitters components
Paddings for row and column splitter components are not aligned when you are using these 2 components together

 #519347 Change padding styles for Splitters components

---

packages/create-sitecore-jss/src/templates/nextjs-sxa/src/assets/basic/_header.scss

Return padding needed for basic site, change the "title" class to "bs-title" to not affect Title rendering on non-basic sites.

#549829: Title rendering has an indent in the header placeholder - updated fix

---

packages/sitecore-jss/package.json
packages/sitecore-jss/src/graphql-request-client.ts
packages/sitecore-jss/src/native-fetcher.ts
packages/sitecore-jss/src/utils/timeout-promise.ts
yarn.lock

This is a workaround to make sure GraphQL and other outgoing requests used by JSS are working in edge middleware.
This approach addresses the unexpected behavior discussed here:
https://github.com/vercel/vercel/discussions/8668
Manual tests are promising :)

Replace abortController.signal with promises timeout in native and graphql fetchers

---

packages/sitecore-jss/src/graphql/app-root-query.ts
packages/sitecore-jss/src/graphql/graphql.test.ts
packages/sitecore-jss/src/i18n/graphql-dictionary-service.ts

The dictionary service doesn't return `rootItemId` for other language versions other than English.
Added a fix to make another request using language as `en` to get the `rootItemId` as it is same in all versions.

[sitecore-jss] `rootItemId` not resolvable for different language versions 

---

packages/create-sitecore-jss/src/initializers/nextjs/index.ts

Correction for `nextjs-sxa` add-on compatibility pre-SXP 10.3 release (i.e. only compatible with XM Cloud, not SXP 10.2)

[Next.js] Correction for `nextjs-sxa` add-on compatibility pre-SXP 10.3 release

---

azure-pipelines.yml
packages/create-sitecore-jss/.nycrc
packages/sitecore-jss-angular-schematics/.nycrc
packages/sitecore-jss-angular/karma.conf.js
packages/sitecore-jss-cli/.nycrc
packages/sitecore-jss-dev-tools/.nycrc
packages/sitecore-jss-forms/.nycrc
packages/sitecore-jss-nextjs/.nycrc
packages/sitecore-jss-proxy/.nycrc
packages/sitecore-jss-react-forms/.nycrc
packages/sitecore-jss-react-native/jest.config.coverage.js
packages/sitecore-jss-react/.nycrc
packages/sitecore-jss-rendering-host/.nycrc
packages/sitecore-jss-vue/jest.config.coverage.js
packages/sitecore-jss/.nycrc

Introduce `Cobertura` - code coverage reporter which compatible with many testing libraries and with azure pipelines.
* `reportgenerator` extension is installed to generate a fancy and user friendly html report
* `PublishCodeCoverageResults` publish generated html report to azure pipelines

[Maintenance] Improve unit test coverage reporting

---

packages/sitecore-jss-forms/src/serializeForm.ts

Fix for file upload not returning a validation error when submitting an empty input.

[sitecore-jss-forms] File upload validation error

---

packages/sitecore-jss-react/src/index.ts

Export DataFieldProps for React DateField component.
Description / Motivation
DataFieldProps have been added to the index fil for export, so that I mirrors all the other components in the jss-React. Then It can be used along side the DataField component. 
Change type
BugFix

[React] export DateFieldProps

---

packages/sitecore-jss/src/layout/models.ts

Adding two extra fields (`id` & `url`) to the **Item** interface in models to be able to properly type incoming data.
The data that is coming from Sitecore seems to have these extra 2 fields on it, see example:
```js
paymentFrequencies: [
{
id: '7b7ff13f-f7af-4dc7-8612-baf46a61659a',
url: '/data/reference-data/payment-frequencies/fortnightly',
name: 'Fortnightly',
displayName: 'Fortnightly',
fields: {
label: {
value: 'due on {date}',
},
value: {
value: 'Fortnightly',
},
name: {
value: 'Fortnightly',
},
},
},
{
id: '63e0d50e-b123-4783-8817-b42ebbdc4d0e',
url: '/data/reference-data/payment-frequencies/four-weekly',
name: 'Four weekly',
displayName: 'Four weekly',
fields: {
label: {
value: 'due on {date}',
},
value: {
value: 'Four weekly',
},
name: {
value: '4Weekly',
},
},
},
]
```
Having …

[sitecore-jss] Update models: Add url and id property to item type

---

packages/sitecore-jss-nextjs/src/components/Link.test.tsx
packages/sitecore-jss-nextjs/src/components/Link.tsx
packages/sitecore-jss-react/src/components/Link.test.tsx
packages/sitecore-jss-react/src/components/Link.tsx

Add support for `anchor` attribute for:
* sitecore-jss-react
* sitecore-jss-nextjs
Pulled nextjs part from #1220

[Next.js][React] Link component does not add anchor to the internal links

---

packages/sitecore-jss/src/constants.ts
packages/sitecore-jss/src/debug.ts
packages/sitecore-jss/src/site/graphql-siteinfo-service.test.ts
packages/sitecore-jss/src/site/graphql-siteinfo-service.ts
packages/sitecore-jss/src/site/index.ts

Multi site service to retrieve site data from Sitecore, to be used for dynamic site resolving on JSS side.
- Uses search GraphQL to get Site Grouping SXA items;
- Reads hostname, virtual folder, site language;
- Returns an array of site data with the above;
- Uses in-memory caching

GraphQL site info service

---

packages/sitecore-jss/src/site/index.ts
packages/sitecore-jss/src/site/site-resolver.test.ts
packages/sitecore-jss/src/site/site-resolver.ts

* Introduced `SiteResolver`
* Returns `siteNamed` based on the provided `hostName` and `siteInfo` list
* Returns fallback default/custom site name when appropriate `siteInfo` is not found

[Next.js][Multi-site] Dynamic site resolver

---

packages/create-sitecore-jss/src/templates/nextjs-personalize/src/lib/middleware/plugins/personalize.ts
packages/sitecore-jss/src/personalize/graphql-personalize-service.test.ts
packages/sitecore-jss/src/personalize/graphql-personalize-service.ts

1) Memory cache usage added to personalize graphql service to cut the number of requests to Sitecore Edge endpoint.
2) Personalize middleware will be disabled by default in development environment - the disabled() delegate passed to middleware still can be changed when needed.

Performance improvements for personalize service and middleware

---

packages/create-sitecore-jss/src/templates/nextjs-sxa/src/pages/api/sitemap.ts

 #557761: fixed sitemap handler

---

packages/sitecore-jss-nextjs/src/editing/editing-data-cache.test.ts
packages/sitecore-jss-nextjs/src/editing/editing-data-cache.ts
packages/sitecore-jss-nextjs/src/editing/editing-data-middleware.ts
packages/sitecore-jss-nextjs/src/editing/editing-data-service.ts

For deploying Sitecore JSS Next.js to Azure Static Web Apps I had to provide my own implementation of the EditingDataCache class (using Azure Blobstorage instead of disk cache):
See https://github.com/erwinsmit/swa-jss/blob/master/src/lib/editing/editing-data-cache.ts for an example.
In this example I had to copy more stuff out of the JSS repo to make it work. If async was supported that wouldn't be necessary. 
The problem I had was that the "EditingDataService" was expecting the "EditingDataCache" to be sync, not async. This limits the implementation of the EditingDataCache class, it's not possible for example to write/read stuff to Blobstorage in a sync manner. 
With my suggested changes it's possible to use sync and async EditingDataCache implementations.  
I've tested my changes on …

add async to editing data cache

---

CHANGELOG.md
packages/sitecore-jss-nextjs/package.json
packages/sitecore-jss-nextjs/src/components/Link.test.tsx
packages/sitecore-jss-nextjs/src/components/Link.tsx
packages/sitecore-jss-react-forms/package.json
packages/sitecore-jss-react/package.json
packages/sitecore-jss-react/src/components/Link.test.tsx
packages/sitecore-jss-react/src/components/Link.tsx

Add support for anchor attribute for:
- sitecore-jss-react
- sitecore-jss-nextjs

[Next.js][React]  Link component does not add anchor to the internal links

---

packages/create-sitecore-jss/src/templates/nextjs/src/middleware.ts

Instead of excluding only `/api/editing` routes, we add more exclusions which will reduce unnecessary middleware invocations

[Next.js] Additional middleware default exclusions

---

packages/create-sitecore-jss/src/templates/nextjs-sxa/src/components/Image.tsx
packages/sitecore-jss-nextjs/src/index.ts

 #559289: added implementation getEEMarkup into sitecore-jss-nextjs

---

packages/create-sitecore-jss/src/templates/angular/sitecore/definitions/components/graph-ql-integrated-demo.sitecore.graphql
packages/create-sitecore-jss/src/templates/angular/sitecore/definitions/routes.sitecore.ts
packages/create-sitecore-jss/src/templates/angular/src/app/components/graph-ql-connected-demo/graph-ql-connected-demo.component.graphql
packages/create-sitecore-jss/src/templates/angular/src/graphql-fragment-types.ts
packages/create-sitecore-jss/src/templates/nextjs-styleguide/sitecore/definitions/components/graphql/GraphQL-IntegratedDemo.sitecore.graphql
packages/create-sitecore-jss/src/templates/nextjs-styleguide/sitecore/definitions/routes.sitecore.ts
packages/create-sitecore-jss/src/templates/nextjs-styleguide/src/components/graphql/GraphQL-ConnectedDemo.dynamic.graphql
packages/create-sitecore-jss/src/templates/nextjs-styleguide/src/components/graphql/GraphQL-ConnectedDemo.dynamic.tsx
packages/create-sitecore-jss/src/templates/nextjs/src/temp/GraphQLIntrospectionResult.json
packages/create-sitecore-jss/src/templates/react/sitecore/definitions/components/GraphQL-IntegratedDemo.sitecore.graphql
packages/create-sitecore-jss/src/templates/react/sitecore/definitions/routes.sitecore.js
packages/create-sitecore-jss/src/templates/react/src/components/GraphQL-ConnectedDemo/query.graphql
packages/create-sitecore-jss/src/templates/react/src/temp/GraphQLFragmentTypes.json
packages/create-sitecore-jss/src/templates/vue/sitecore/definitions/components/GraphQL-IntegratedDemo.sitecore.graphql
packages/create-sitecore-jss/src/templates/vue/sitecore/definitions/routes.sitecore.js
packages/create-sitecore-jss/src/templates/vue/src/components/GraphQL/GraphQL-ConnectedDemo.query.graphql
packages/create-sitecore-jss/src/templates/vue/src/temp/GraphQLFragmentTypes.json

This reverts commit e1d1a02737ad562f285d086ab8dbcd7ea0964ea1.
The new `Page` template name conflicts with SXA `Page`.
Typed GraphQL doesn't support duplicate type names, so we have to rename `Page` back to `AppRoute` to resolve the conflict.

Rename `Page` template back to `AppRoute`

---

package.json

When I worked on a PR recently:
https://github.com/Sitecore/jss/pull/1223
I had an issue running all the tests from the root of the repository. In the contributing guidelines, it states that you can run all the tests using `yarn test-packages`. But there doesn't seem to be an NPM task for this.
Adding a test task to the root of the repository for running tests across all the packages.

add test task

---

packages/sitecore-jss/.nycrc
packages/sitecore-jss/src/graphql/graphql.test.ts
packages/sitecore-jss/src/layout/utils.test.ts

Small increase for base package unit test coverage
- Ignore files that don't have executable logic
- Add tests where it makes sense

sitecore-jss extra unit test coverage

---

packages/sitecore-jss-react-forms/src/components/form.test.tsx
packages/sitecore-jss-react-forms/src/components/form.tsx

Provides `language` property to use `sc_lang` url parameter

[nextjs][react]The language of the form is changed after clicking the submit button

---

packages/sitecore-jss-vue/jest.config.coverage.js

Just a small change to get jss-vue coverage more accurate.

Exclude index file from jss-vue test coverage

---

packages/create-sitecore-jss/src/templates/nextjs-sxa/src/pages/api/sitemap.ts

Fixed functional of generating of sitemap.xml if there isn't from GRAPHQL request. 
The last version used absolute path to sitemap.xml's.
Now we are using public_url path.

 #556667: [SXA] fixed urls(using PUBLIC_URL) for generating sitemap.xml

---

packages/sitecore-jss/src/site/index.ts
packages/sitecore-jss/src/site/utils.test.ts
packages/sitecore-jss/src/site/utils.ts

Includes required utils for site rewrite path resolution:
* getSiteRewrite
* getSiteRewriteData
* normalizeSiteRewrite
Format is `_site_<sitename>/<path>`
Unit tests are added

[Next.js][Multi-site] Multi-site path utils

---

packages/sitecore-jss-react/src/components/PlaceholderCommon.tsx
packages/sitecore-jss-react/src/test-data/non-ee-data.ts

Rewrote code which deleted temporary dynamic placeholder.
Problem was in hardcoded prefix of name dynamic placeholder.

 #559044: [SXA] fixed rendering dynamic placeholder

---

packages/sitecore-jss/src/personalize/utils.test.ts
packages/sitecore-jss/src/site/utils.test.ts

With multisite feature adding another prefix, we need to ensure the program will understand and correctly handle path prefixes regardless of the order they go in, or their position.

Ensure site and variant prefixes are position agnostic

---

packages/sitecore-jss/src/site/graphql-siteinfo-service.ts

Fixes a bug where site query would retrieve site data from Standard Values and branch templates

Ensure site items are only retrieved from SXA sites' content tree

---

packages/create-sitecore-jss/src/templates/nextjs-sxa/src/lib/middleware/plugins/redirects.ts
packages/sitecore-jss-nextjs/src/middleware/redirects-middleware.test.ts
packages/sitecore-jss-nextjs/src/middleware/redirects-middleware.ts

This fixes the bug of multisite context being lost when rewrite plugin is present.

Ensure multisite response is persisted in rewrite middleware

---

packages/create-sitecore-jss/src/templates/nextjs-multisite/scripts/config/plugins/multisite.ts
packages/create-sitecore-jss/src/templates/nextjs/scripts/config/index.ts
packages/create-sitecore-jss/src/templates/nextjs/scripts/config/plugins/computed.ts
packages/create-sitecore-jss/src/templates/nextjs/scripts/config/plugins/fallback.ts
packages/create-sitecore-jss/src/templates/nextjs/scripts/config/plugins/package-json.ts
packages/create-sitecore-jss/src/templates/nextjs/scripts/config/plugins/scjssconfig.ts
packages/create-sitecore-jss/src/templates/nextjs/scripts/generate-config.ts

This PR slightly reworks how a config in nextjs app is built. 
Each value is resolved with the following logic:
1) Attempt to retrieve value from env
2) Attempt to retrieve value from supplementary files (package.json / scjssconfig)
3) If certain values (that can't be empty, i.e. language) are still empty - use fallback value.
This roughly follows pre-plugin approach to building config where env values take precedence, other sources follow as fallback.
This also ensures that graphQL endpoint will have a correct value, if hostname values is present in either env or scjssconfig.

Ensure app config variables have values at build-time

---

CHANGELOG.md
packages/sitecore-jss-angular/src/jss-component-factory.service.ts

* Remove outdated code that supported string type values for loadChildren.

[Angular] Address webpack warning about dynamic components

---

packages/create-sitecore-jss/src/templates/nextjs/scripts/generate-config.ts

This is a follow-up to #1296, adding the same default (pulling from env var) for `graphQLEndpoint` config prop.

[Next.js][Multi-site] Added default for graphQLEndpoint config prop

---

packages/sitecore-jss/src/site/graphql-siteinfo-service.test.ts
packages/sitecore-jss/src/site/graphql-siteinfo-service.ts

Use name from field instead of an item name when getting site data via GraphQL

[sitecore-jss] Use site name value from field for multisite

---

packages/create-sitecore-jss/src/templates/nextjs-multisite/src/lib/page-props-factory/plugins/site.ts
packages/create-sitecore-jss/src/templates/nextjs-personalize/src/lib/page-props-factory/plugins/personalize.ts
packages/create-sitecore-jss/src/templates/nextjs-sxa/src/lib/page-props-factory/plugins/error-pages.ts
packages/create-sitecore-jss/src/templates/nextjs/src/lib/page-props-factory/plugins/preview-mode.ts
packages/create-sitecore-jss/src/templates/nextjs/src/lib/page-props-factory/plugins/site.ts

* Better page props site resolution for editing/preview
* Added (missing) short-circuits for personalize and error-pages as well
* Fixes issue where a newly added site fails to resolve in Pages (Pages appends sc_site query string to the canvas request under the hood)
Tested on XMC staging

[Next.js][Multi-site] Better page props site resolution for editing/preview

---

packages/sitecore-jss-angular/src/jss-component-factory.service.ts

* Changes jss-component-factory in base Angular package to use loadChildren promise directly, removing obsolete logic.
Manual testing in connected mode

[Angular] Move away from rxjs use for lazyloading in favor of more direct approach

---

packages/sitecore-jss/src/site/site-resolver.test.ts
packages/sitecore-jss/src/site/site-resolver.ts

More specific hostname matches should take precedence over a less specific match (i.e. with wildcards). For example, given the following site info array:
```
[
{
name: "foo",
hostname: "*"
},
{
name: "bar",
hostname: "*.app.net"
},
{
name: "baz",
hostname: "baz.app.net"
},
]
```
it would resolve the following sites for given hostname:
```
"foo.net" > "foo"
"bar.app.net" > "bar"
"baz.app.net" > "baz"
```
Unit tests added

[Next.js][Multi-site] Updated site resolver to prefer more specific hostname matches

---

packages/create-sitecore-jss/src/templates/angular/data/routes/styleguide/en.yml
packages/create-sitecore-jss/src/templates/angular/package.json
packages/create-sitecore-jss/src/templates/angular/src/app/components/styleguide-field-usage-link/styleguide-field-usage-link.component.html
packages/create-sitecore-jss/src/templates/angular/src/app/components/styleguide-field-usage-text/styleguide-field-usage-text.component.html
packages/create-sitecore-jss/src/templates/angular/src/app/components/styleguide-layout/styleguide-layout.component.html
packages/create-sitecore-jss/src/templates/angular/src/app/routing/navigation/navigation.component.html
packages/create-sitecore-jss/src/templates/angular/src/styles.css

* Upgrades bootstrap to v5.2 in angular sample app
* Adds resolutions to avoid rules skip during build
* Tweaks CSS to match changes in bootstrap v5
Known issue:
* You may get the following error when building angular sample app in monorepo setup:
** Rules skipped due to selector errors: legend+* -> Cannot read property 'type' of undefined
to avoid it, add resolutions for css-select into the monorepo's root package:
```
"resolutions": {
"css-select": "4.2.1"
}
```
You can read more in here: https://github.com/GoogleChromeLabs/critters/issues/103
Manual testing for build and CSS on angular sample.

[angular] upgrade bootstrap in sample app

---

packages/create-sitecore-jss/src/initializers/nextjs-sxa/index.ts
packages/create-sitecore-jss/src/initializers/nextjs/prompts.ts

Adding incompatibility message when initializing nextjs sample app with both sxa with styleguide addons.

[create-sitecore-jss] Incompatibility message when installing sxa and styleguide

---

packages/create-sitecore-jss/src/templates/nextjs-personalize/src/components/CdpPageView.tsx

The engage version has been updated as part of nextjs third party upgrades.
This PR only renames pos param to pointOfSale in pageView call from CdpPageView control to match updated call signature.

[Next.js] Finalize @sitecore/engage version upgrade

---

packages/create-sitecore-jss/src/templates/node-headless-ssr-proxy/src/config.ts
packages/sitecore-jss-proxy/src/ProxyConfig.ts
packages/sitecore-jss-proxy/src/index.ts

[sitecore-jss/sitecore-jss-proxy] Better handling for WebSocket requests.
* Makes proxy handling of WebSocket requests configurable
* Adds ws property via ProxyConfig
* Makes it disabled by default
Manual testing.

[sitecore-jss-proxy] Disable websocket processing by default in proxy

---

packages/sitecore-jss-react/src/components/Placeholder.test.tsx
packages/sitecore-jss-react/src/components/PlaceholderCommon.tsx
packages/sitecore-jss-react/src/test-data/non-ee-data.ts

Added pattern and checking for rendering Dynamic placeholders. 
There was bug with rendering splitter components with fix Dynamics placeholders.

#559044: [SXA] fixed rendering dynamic placeholders for splitter components

---

packages/create-sitecore-jss/src/templates/nextjs-multisite/scripts/config/plugins/multisite.ts
packages/create-sitecore-jss/src/templates/nextjs/scripts/generate-config.ts

Import `dotenv/config` so that environment variables are picked up in default JSS config generation.
Note this happened to work if using JSS CLI (since `dotenv` support is built-in) to run commands (e.g. `jss start:connected`), but not if using npm (e.g. `npm run start:connected`).
Local testing and on XM Cloud Staging deployed to Vercel

[Next.js] Fix use of environment variables for JSS config generation (without JSS CLI)

---

packages/create-sitecore-jss/src/templates/nextjs-styleguide-tracking/src/Navigation.tsx
packages/create-sitecore-jss/src/templates/nextjs-styleguide/src/Navigation.tsx
packages/create-sitecore-jss/src/templates/nextjs-styleguide/src/components/fields/Styleguide-FieldUsage-Image.tsx
packages/create-sitecore-jss/src/templates/nextjs-styleguide/src/components/graphql/GraphQL-IntegratedDemo.tsx
packages/create-sitecore-jss/src/templates/nextjs-styleguide/src/components/styleguide/Styleguide-CustomRouteType.tsx
packages/create-sitecore-jss/src/templates/nextjs-styleguide/src/components/styleguide/Styleguide-Multilingual.tsx
packages/create-sitecore-jss/src/templates/nextjs-styleguide/src/components/styleguide/Styleguide-RouteFields.tsx
packages/create-sitecore-jss/src/templates/nextjs-styleguide/src/lib/next-config/plugins/disconnected.js
packages/create-sitecore-jss/src/templates/nextjs-styleguide/src/lib/next-config/plugins/styleguide.js
packages/create-sitecore-jss/src/templates/nextjs/package.json
packages/create-sitecore-jss/src/templates/nextjs/src/lib/next-config/plugins/monorepo.js
packages/sitecore-jss-nextjs/package.json
packages/sitecore-jss-nextjs/src/components/Link.tsx
packages/sitecore-jss-nextjs/src/components/NextImage.test.tsx
packages/sitecore-jss-nextjs/src/components/NextImage.tsx
packages/sitecore-jss-nextjs/src/middleware/multisite-middleware.test.ts
packages/sitecore-jss-nextjs/src/middleware/multisite-middleware.ts
packages/sitecore-jss-nextjs/src/middleware/personalize-middleware.test.ts
packages/sitecore-jss-nextjs/src/middleware/personalize-middleware.ts
packages/sitecore-jss-nextjs/src/middleware/redirects-middleware.test.ts
packages/sitecore-jss-nextjs/src/middleware/redirects-middleware.ts
yarn.lock

* _Next_ is bumped to _^13.1.6_
* _next/link_ <Link /> component doesn't accept `<a/>` tag as a child anymore
* _next/image_ <Image />: 
* Component doesn't support _layout_ property, _fill_ (fluid image) needs to be used instead, which requires having _relative_ positioned parent. 
* Set _sizes_ value to be the same as we have for RAV.
* Now _alt_ is required property
* _next-transpile-modules_ not needed anymore, _next_ now supports linked dependencies resolution OOTB, multiple _react_ dependencies related fix also not required to be present anymore
* Middleware's _cookie.get_ now returns _{ value, name, ...rest }_ instead of _value_
* Aligned unit tests according to new changes
* Not related to upgrade:
* Moved _sitecore/manifest/sitecore-import.json_ fallback config from …

[Next.js] Next 13 upgrade

---

.prettierignore
CHANGELOG.md

Update changelog with semantic version strategy details.

Update `CHANGELOG` with updated version strategy

---

packages/create-sitecore-jss/src/templates/nextjs/tsconfig.json

* Inside the Docker env, the sample app uses a lowercased path and can't find an appropriate module in case you have capitalized letters in your sample app dist path
Launched docker env with a reference to sample app inside the monorepo

[Nextjs] Sample in Docker env references linked packages using lowercase path

---

packages/create-sitecore-jss/src/templates/nextjs-styleguide/src/components/fields/Styleguide-FieldUsage-Image.tsx
packages/create-sitecore-jss/src/templates/nextjs/tsconfig.json
packages/sitecore-jss-nextjs/src/components/NextImage.test.tsx
packages/sitecore-jss-nextjs/src/components/NextImage.tsx

* Width/height attributes have to be excluded when `fill` property is provided, parent will use these values, see https://nextjs.org/docs/api-reference/next/image#fill
* Set default value for `forceConsistentCasingInFileNames`, otherwise _true_ will be set by default
Manual testing

[Next.js][Image] Exclude width/height when `fill` prop is provided

---

packages/create-sitecore-jss/src/templates/react/data/routes/styleguide/en.yml
packages/create-sitecore-jss/src/templates/react/src/Layout.js
packages/create-sitecore-jss/src/templates/react/src/components/Styleguide-FieldUsage-Link/index.js
packages/create-sitecore-jss/src/templates/react/src/components/Styleguide-FieldUsage-Text/index.js
packages/create-sitecore-jss/src/templates/react/src/components/Styleguide-Layout/index.js

Apply _font-weight -> fw_ naming after bootstrap upgrade

[React] Apply missing bootstrap styles after upgrade

---

packages/create-sitecore-jss/src/templates/vue/vue.config.js

SSR for EE was not working because `removeAttributeQuotes` was not disabled in the vue `html` `webpack plugin` due to which html was not minified.

[Vue] Fix EE error

---

packages/create-sitecore-jss/src/templates/nextjs/next.config.js

Adds an extra rewrite rule that allows JSS to handle Sitecore's default not-found page correctly.
Manual testing

[nextjs] Add rewrite for Sitecore's default 404 prefix

---

packages/sitecore-jss-react/src/components/PlaceholderCommon.tsx
packages/sitecore-jss-react/src/enhancers/withPlaceholder.test.tsx
packages/sitecore-jss-react/src/test-data/ee-data.ts
packages/sitecore-jss-react/src/test-data/non-ee-data.ts

This fixes the rendering issueWhen additional params are configured in sitecore, the the components using the withPlaceholder HOC crashes because the current implementation of PlaceholderCommon assumes that the params would always be present on any rendering which is not the case as it is an optional property.

[sitecore-jss-react] Fix rendering issue in components using withPlaceholder

---

packages/create-sitecore-jss/src/templates/angular/data/routes/styleguide/en.yml
packages/create-sitecore-jss/src/templates/angular/sitecore/definitions/components/styleguide-edit-frame.sitecore.ts
packages/create-sitecore-jss/src/templates/angular/src/app/components/styleguide-edit-frame/styleguide-edit-frame.component.html
packages/create-sitecore-jss/src/templates/angular/src/app/components/styleguide-edit-frame/styleguide-edit-frame.component.ts
packages/create-sitecore-jss/src/templates/nextjs-styleguide/data/routes/styleguide/en.yml
packages/create-sitecore-jss/src/templates/nextjs-styleguide/sitecore/definitions/components/styleguide/Styleguide-EditFrame.sitecore.ts
packages/create-sitecore-jss/src/templates/nextjs-styleguide/src/components/styleguide/Styleguide-EditFrame.tsx
packages/create-sitecore-jss/src/templates/react/data/routes/styleguide/en.yml
packages/create-sitecore-jss/src/templates/react/sitecore/definitions/components/Styleguide-EditFrame.sitecore.js
packages/create-sitecore-jss/src/templates/react/src/components/Styleguide-EditFrame/index.js
packages/create-sitecore-jss/src/templates/vue/data/routes/styleguide/en.yml
packages/create-sitecore-jss/src/templates/vue/sitecore/definitions/components/Styleguide-EditFrame.sitecore.js
packages/create-sitecore-jss/src/templates/vue/src/components/Styleguide/Styleguide-EditFrame.vue
packages/sitecore-jss-react/src/components/EditFrame.tsx

Adds a better showcase for edit frame component in Styleguide.

Improved usecases for styleguide edtframe example

---

azure-pipelines.yml

Reverts Sitecore/jss#1353 as it seems to be the reason our canary version builds fail.

Revert "Upgrade node to LTS"

---

packages/sitecore-jss-nextjs/src/middleware/personalize-middleware.ts

Resolve site only in case personalization is enabled, otherwise in preview mode newly added site can't be resolved

[sitecore-jss-nextjs] [Personalize] Don't resolve site in middleware when personalization is not enabled

---

packages/create-sitecore-jss/src/templates/nextjs-styleguide/scripts/config/plugins/disconnected.ts
packages/create-sitecore-jss/src/templates/nextjs/scripts/config/plugins/computed.ts
packages/create-sitecore-jss/src/templates/nextjs/scripts/config/plugins/fallback.ts

The computed JSS config plugin uses the `sitecoreApiHost` prop as part of its computed value for `graphQLEndpoint`. However, the disconnected JSS config plugin was running after this, so the `sitecoreApiHost` was not properly set for disconnected mode. 
This fixes the Graphql endpoint error when running in disconnected mode. Also gives some breathing room with the assigned orders.

[Next.js] Ensure disconnected JSS config plugin is run before computed plugin

---

packages/create-sitecore-jss/src/templates/nextjs-personalize/src/components/CdpPageView.tsx

The site can't be resolved in editing mode, so don't need to execute this logic

[Nextjs][Personalize] Don't resolve site in CdpPageView when it's disabled

---

packages/create-sitecore-jss/src/templates/angular/data/content/Styleguide/EditFrameDemo/Item1/en.yml
packages/create-sitecore-jss/src/templates/angular/data/content/Styleguide/EditFrameDemo/Item2/en.yml
packages/create-sitecore-jss/src/templates/angular/data/routes/styleguide/en.yml
packages/create-sitecore-jss/src/templates/angular/sitecore/definitions/templates/styleguide-edit-frame-list-item-template.sitecore.ts
packages/create-sitecore-jss/src/templates/angular/sitecore/definitions/templates/styleguide-edit-frame-list-item-template.sitecoret.ts
packages/create-sitecore-jss/src/templates/angular/src/app/components/styleguide-edit-frame/styleguide-edit-frame.component.html
packages/create-sitecore-jss/src/templates/nextjs-styleguide/data/content/Styleguide/EditFrameDemo/Item1/en.yml
packages/create-sitecore-jss/src/templates/nextjs-styleguide/data/content/Styleguide/EditFrameDemo/Item2/en.yml
packages/create-sitecore-jss/src/templates/nextjs-styleguide/data/routes/styleguide/en.yml
packages/create-sitecore-jss/src/templates/nextjs-styleguide/sitecore/definitions/templates/Styleguide-EditFrame-ListItem-Template.sitecore.ts
packages/create-sitecore-jss/src/templates/nextjs-styleguide/sitecore/definitions/templates/Styleguide-EditFrame-ListItem-Template.sitecoret.ts
packages/create-sitecore-jss/src/templates/nextjs-styleguide/src/components/styleguide/Styleguide-EditFrame.tsx
packages/create-sitecore-jss/src/templates/react/data/content/Styleguide/EditFrameDemo/Item1/en.yml
packages/create-sitecore-jss/src/templates/react/data/content/Styleguide/EditFrameDemo/Item2/en.yml
packages/create-sitecore-jss/src/templates/react/data/routes/styleguide/en.yml
packages/create-sitecore-jss/src/templates/react/sitecore/definitions/templates/Styleguide-EditFrame-ListItem-Template.sitecore.js
packages/create-sitecore-jss/src/templates/react/src/components/Styleguide-EditFrame/index.js
packages/create-sitecore-jss/src/templates/vue/data/content/Styleguide/EditFrameDemo/Item1/en.yml
packages/create-sitecore-jss/src/templates/vue/data/content/Styleguide/EditFrameDemo/Item2/en.yml
packages/create-sitecore-jss/src/templates/vue/data/routes/styleguide/en.yml
packages/create-sitecore-jss/src/templates/vue/sitecore/definitions/templates/Styleguide-EditFrame-ListItem-Template.sitecore.js
packages/create-sitecore-jss/src/templates/vue/src/components/Styleguide/Styleguide-EditFrame.vue

Edit Frame demo in styleguide reused items from Content List. It will now has its own set of items to avoid conflicts.

Add separate items for edit frame list demo

---

packages/create-sitecore-jss/src/templates/vue/package.json

Using SSR latest apollo-composable (beta.4) brings _useQuery_ related errors. See es imports related issue https://github.com/vuejs/apollo/issues/1462. For now version can be fixed to apollo-composable@4.0.0.beta.2 - since it's beta.
```
ERROR TypeError: (0 , lib_namespaceObject.getCurrentInstance) is not a function
at useQueryImpl (C:\inetpub\wwwroot\dist\sitecore-jss-app\server.bundle.js:106509:56)
at useQuery (C:\inetpub\wwwroot\dist\sitecore-jss-app\server.bundle.js:106505:10)
```

[Vue] Timeout error when opening graphql page in Experience Editor

---

packages/create-sitecore-jss/src/templates/vue/package.json

When starting the Vue app in connected mode the local dev server automatically starts at `0.0.0.0:3000` which has a wrong hostname.

[Vue] Fix local dev server launch error

---

packages/sitecore-jss-nextjs/src/middleware/redirects-middleware.test.ts
packages/sitecore-jss-nextjs/src/middleware/redirects-middleware.ts

Added start/end logs for Redirects middleware

[sitecore-jss-nextjs] Redirects middleware should debug log start/end

---

packages/sitecore-jss-nextjs/src/components/Link.test.tsx
packages/sitecore-jss-react/src/components/Link.test.tsx
packages/sitecore-jss-react/src/components/Link.tsx

Fixes an issue where 'anchor' type links would be incorrectly rendered.

[react][nextjs] Fix double hash in anchor links

---

azure-pipelines.yml

Sets node version to 16 for v19 branch. This ensures the branch builds in Azure Pipelines.

[v19] Ensure node version

---

packages/sitecore-jss/src/personalize/pos-resolver.test.ts
packages/sitecore-jss/src/personalize/pos-resolver.ts

Point of sale would default to site language value over wildcard fallback value before.
This PR ensures wildcard is used as first fallback.

[nextjs] Prefer wildcard fallback for point of sale resolution

---

packages/sitecore-jss-angular/src/components/placeholder.component.spec.ts
packages/sitecore-jss-react/src/components/Placeholder.test.tsx
packages/sitecore-jss-react/src/components/PlaceholderCommon.tsx
packages/sitecore-jss-vue/src/components/Placeholder.test.ts
packages/sitecore-jss-vue/src/components/PlaceholderCommon.ts
packages/sitecore-jss-vue/src/components/__snapshots__/Placeholder.test.ts.snap

Personalized components could render an error frame when default variant is hidden. This PR fixes it.

[RAV][nextjs] Ensure component works when default personalization variant is hidden

---

packages/create-sitecore-jss/src/templates/nextjs/src/lib/dictionary-service-factory.ts

This simply updates comments on rootItemId usage for DictionaryService.
Following SXA changes, rootItemId should be autoresolved for SXA sites in XM Cloud.

[nextjs-sxa] update comments on rootitemid

---

packages/create-sitecore-jss/src/templates/vue/scripts/disconnected-mode-proxy.js

In case _requireArg_ is not provided, the disconnected server manifest generation is started using [sitecore/definitions/config.js](https://github.com/Sitecore/jss/blob/dev/packages/create-sitecore-jss/src/templates/vue/sitecore/definitions/config.js) transpiler, that is working fine for us (and uses same the _@babel/register_ package).
As a worst case it would be possible to work around that by using `path.resolve(process.cwd(), 'node_modules/@babel/register')`. Since in monorepo some packages can be placed in the root _node_modules_ it's required to provide exact path if module imported from a different package, like [here](https://github.com/Sitecore/jss/blob/dev/packages/sitecore-jss-dev-tools/src/manifest/generator/generate.ts#L56)

[Vue] Disconnected mode doesn't start in monorepo

---

CHANGELOG.md
packages/sitecore-jss-nextjs/src/components/Link.test.tsx
packages/sitecore-jss-nextjs/src/components/Link.tsx
packages/sitecore-jss-react/src/components/Link.test.tsx

- Fixes an issue with nextjs Link component where build throws TypeError when field is undefined
- Also added a couple additional tests for editing use cases

[Next.js] Fix for Link component which throws error if field is undefined

---

CHANGELOG.md
packages/sitecore-jss-rendering-host/package.json
packages/sitecore-jss-rendering-host/src/index.ts
packages/sitecore-jss-rendering-host/src/ssrMiddleware.ts
ref-docs/sitecore-jss-rendering-host/README.md
yarn.lock

devServer is removed from sitecore-jss-rendering-host. renderingHostServer would be the only way to use rendering-host with react apps.
devServer was poorly documented and rarely used which led to the decisions to retire it

[sitecore-jss-rendering-host] Retire devServer

---

CHANGELOG.md
packages/sitecore-jss-nextjs/src/middleware/redirects-middleware.ts

Fixed regex middleware redirects.
Worked differently than on SXA MVC version.

 #577960: [SXA] fixed middleware redirects

---

CHANGELOG.md
packages/sitecore-jss-react/package.json
packages/sitecore-jss-react/src/components/Link.tsx
yarn.lock

Use of _html-react-parser_ is not needed, since we render _children_ as a sibling to _editable_ markup
The cause of the hydration error is that the server returns markup that includes additional space and _&quot_ instead of brackets (fragment of the server response)
Using _dangerouslySetInnerHTML_ property it's parsed and returned to the browser as expected

[sitecore-jss-react] Hydration error when render Link in Edit mode

---

CHANGELOG.md
packages/create-sitecore-jss/src/templates/nextjs-sxa/src/components/FEaaSWrapper.tsx
packages/sitecore-jss-react/src/components/FEaaSComponent.test.tsx
packages/sitecore-jss-react/src/components/FEaaSComponent.tsx

FEaaS Components follow a lifecycle different from Sitecore items so Layout Service will not always provide JSS apps with the correct component revision to show. 
This PR puts revision resolution into JSS logic:
- In editing and preview modes, 'staged' FEaaS variants should be rendered by default;
- Variant can be overridden via ComponentRevision rendering parameter field from a FEaaS rendering.

[FEaaS][nextjs-sxa] Fetch revision based on page state

---

CHANGELOG.md
packages/create-sitecore-jss/src/templates/nextjs-multisite/scripts/config/plugins/multisite.ts
packages/create-sitecore-jss/src/templates/nextjs/scripts/config/plugins/computed.ts

When working with nextjs and multisite the config value for graphqlEndpoint and apiKey comes out undefined because multisite config plugin runs before the computed config plugin.

[Nextjs][Multisite] Fix skipped site info fetch

---

packages/sitecore-jss-angular/src/components/image.directive.ts
packages/sitecore-jss-angular/src/components/link.directive.ts

(cherry picked from commit eccfe579c85668d2420f201977c150f5de1a4c93) (cherry picked from commit ea42cab2e753c6fb8975de050c44cf067beb81d0)
Hotfix of https://github.com/Sitecore/jss/pull/1435 on top of JSS 16, merge after the dev PR is done.

[angular] Fix #579162 on top of JSS 16

---

CHANGELOG.md
packages/create-sitecore-jss/src/templates/nextjs/src/middleware.ts

When you request the specific route the execution order is:
* headers from next.config.js
* redirects from next.config.js
* middleware
* rewrites from next.config.js
because of that it's required to exclude _/healthz_ from middleware execution, otherwise next config _rewrite_ is not executed

[Nextjs] Healthz shows page not found for multisite setup

---

azure-pipelines.yml

An internal fix.
1) Make pipeline use latest ubuntu image, for it to no longer fail.
2) Return family-friendliness to the YML (comment removed).

[v16] Ensure pipeline uses an ubuntu image that exists

---

azure-pipelines.yml
samples/react-native/package-lock.json

Part 2 of fixing ver16 pipeline: 
* Ensure node version is set to the supported v14
* Fix an SSH dependency for react-native so that npm ci can do its thing without access errors
* Add extra condition so that pre-release will publish when pushing to release branch

Internal dev/16/fix pipeline bootstrap

---

azure-pipelines.yml

Part 3 of pipeline adjustments. This one ensures pipeline checks out to the existing and correct branch name before performing lerna version and lerna publish actions.

[internal][v16] Fix branch checkout in azure pipeline

---

CHANGELOG.md
packages/create-sitecore-jss/src/templates/angular/src/app/app.component.ts

Remove extra calls to translate.use to avoid extra Dictionary service calls

[angular] Avoid double requests to dictionary service

---

CHANGELOG.md
packages/create-sitecore-jss/src/bin.ts
packages/create-sitecore-jss/src/templates/angular/scripts/install-pre-push-hook.ts
packages/create-sitecore-jss/src/templates/nextjs/scripts/install-pre-push-hook.ts
packages/create-sitecore-jss/src/templates/react/scripts/install-pre-push-hook.js
packages/create-sitecore-jss/src/templates/vue/package.json
packages/create-sitecore-jss/src/templates/vue/scripts/install-pre-push-hook.js

- Install the the `prePushHook` script to the root .git folder.
- Currently the --yes flag defaults prePushHook to true because of which if prePushHook flag is passed explicitly then it is not considered. We want the cli to accept both flags`--yes` and `prePushHook`.

[nextjs][RAV] Install `pre-push-hook` to root .git

---

CHANGELOG.md
packages/create-sitecore-jss/src/templates/nextjs/.babelrc

Remove .babelrc to (re)enable SWC compilation by default in our base nextjs template. Our original reason for adding (issues running inside Windows-based rendering host on local containers) is fixed on recent Next.js versions.

[Next.js] Remove .babelrc to (re)enable SWC compilation by default

---

packages/create-sitecore-jss/src/templates/nextjs-sxa/package.json

sass and saas-alias packages are used in the runtime of the Next.JS SXA Starter Kit inside the "saas" plugin.
Some of the hosting providers (like CloudflarePages and Azure Static Web Apps) only install packages listed as dependencies when they post-process the build artifacts which causes the application to never start.

[nextjs][sxa]Moving saas and sass-alias from devDependencies to dependencies

---

CHANGELOG.md
packages/create-sitecore-jss/src/templates/node-headless-ssr-experience-edge/src/index.ts

The `node-headless-ssr-experience-edge` template doesn't have the helper comment to add the `rootItemId` if missing.

[node-headless-ssr-experience-edge] Add helper comment for `rootItemId`

---

packages/create-sitecore-jss/src/templates/nextjs/.babelrc

The Wheel of Time weaves as the Wheel wills and we again need to add babelrc after the nextjs version update.
This should be a temporary measure to make our test agents work again, while we look for a better solution.

[nextjs] Re-introduce babelrc

---

CHANGELOG.md
packages/create-sitecore-jss/src/templates/nextjs-sxa/src/pages/404.tsx
packages/create-sitecore-jss/src/templates/nextjs-sxa/src/pages/500.tsx

Added condition DISABLE_SSG_FETCH for 404/500 pages to enable full ISR (Incremental Static Regeneration) flow

 #585891: fixed 404/500 added DISABLE_SSG_FETCH params

---

CHANGELOG.md
packages/create-sitecore-jss/src/templates/nextjs-sxa/src/components/Promo.tsx

Fixed type of Text2 for Promo Component in WithText variant

 #582982: [nextjs-sxa] changed type of text for Promo Component

---

CHANGELOG.md
packages/create-sitecore-jss/src/templates/nextjs-personalize/.env
packages/create-sitecore-jss/src/templates/nextjs-personalize/src/lib/middleware/plugins/personalize.ts
packages/sitecore-jss/src/personalize/cdp-service.ts
packages/sitecore-jss/src/personalize/graphql-personalize-service.test.ts
packages/sitecore-jss/src/personalize/graphql-personalize-service.ts

Updated:
* Default personalize middleware timeout values to 400
* Default personalize, cdp services timeout values to 400

[Next.js][Personalize] Update the default personalize middleware, personalize/cdp service timeout values to 400

---

packages/create-sitecore-jss/src/templates/nextjs/.babelrc

Now that we added C++ Redist to our internal containers we can revert Sitecore/jss#1497

Revert "[nextjs] Re-introduce babelrc"

---

CHANGELOG.md
packages/sitecore-jss-nextjs/src/components/RichText.test.tsx
packages/sitecore-jss-nextjs/src/components/RichText.tsx
packages/sitecore-jss-nextjs/src/tests/jsdom-setup.ts

When the RichText component content changes, the useEffect() hook is not re-run as it has no dependancies. This means the initializeLinks() function is not run so any embedded internal links within the component will not have the appropriate click event handler. This causes any link within the component to cause a full page load rather than client side routing occuring. This change adds the "hasText" property (essentially the rich text) as a dependancy for the useEffect() hook, ensuring the initializeLinks() function is run when the content changes, enabling client side routing to occur.
Unit test added. 
Manual testing involved applying the proposed changes to a local dev instance of Sitecore 10.2 and 10.3 and observing the appropriate  event handler is applied to internal links within …

[NextJS] Fix for bug in RichText component - links not reinitialised when content changes

---

azure-pipelines.yml

Fix the azure pipeline, ensure lerna uses the version from package.json and not the one installed in environment, when pipeline is running.

[Chore] launch lerna build through npm and not directly

---

CHANGELOG.md
packages/create-sitecore-jss/src/templates/vue/package.json

`apollo/client` uses the latest version of `tslib` which is not compatible with our current setup.
Added previous patch release of `tslib` to vue template.

[Vue] Fix integrated mode error

---

packages/sitecore-jss-react/src/components/FEaaSComponent.tsx

Passing an extra prop into FEAAS, per Components' team request. The prop is needed for correct parsing of FEAAS Components in multi-instance Sitecore setup.

[nextjs][feaas] pass optional component instance ID into FEAAS

---

CHANGELOG.md
packages/sitecore-jss-react/src/components/FEaaSComponent.test.tsx
packages/sitecore-jss-react/src/components/FEaaSComponent.tsx

Components SDK makes requests on the client-side to check for latest version. These extra requests are unnecessary for SSR.
We omit the last-modified attribute in the component and just give it the "template". It will not do the cache-busting behavior

[Next.js][FEaaS] Prevent extra components client-side requests for SSR

---

CHANGELOG.md
packages/create-sitecore-jss/src/templates/nextjs-sxa/package.json
packages/create-sitecore-jss/src/templates/nextjs-sxa/src/assets/basic/_fonts.scss
packages/create-sitecore-jss/src/templates/nextjs-sxa/src/assets/main.scss

There was problem with CORS and getting fonts
Added CDN for FontAwesome fonts

 #544756: [templates/nextjs-sxa] added cdn for font-awesome font

---

CHANGELOG.md
packages/sitecore-jss-nextjs/src/middleware/personalize-middleware.test.ts
packages/sitecore-jss-nextjs/src/middleware/personalize-middleware.ts

Personalize middleware doesn't access a real referrer value (from headers), instead, it provided a default "about:client" value from the request

[sitecore-jss-nextjs] Referrer is not captured by Personalize middleware

---

CHANGELOG.md
packages/create-sitecore-jss/src/templates/nextjs-sxa/package.json

Reverted @fontawesome package for mixins

#544756: [templates/nextjs-sxa]fix font awesome

---

CHANGELOG.md
packages/create-sitecore-jss/src/templates/nextjs-sxa/src/assets/sass/components/navigation/_navigation-main-horizontal-vertical.scss
packages/create-sitecore-jss/src/templates/nextjs-sxa/src/assets/sass/components/navigation/_navigation-mobile.scss

Fixed styles of navigation component

#544756: [templates/nextjs-sxa] 544756 fix font awesome. fixed styles

---

CHANGELOG.md
azure-pipelines.yml

Since we decided to use the exact version of our npm packages, we need to configure the same for canary builds

[Chore] Use exact canary version instead of range

---

CHANGELOG.md
packages/sitecore-jss-nextjs/src/middleware/redirects-middleware.test.ts
packages/sitecore-jss-nextjs/src/middleware/redirects-middleware.ts

The middleware of redirects ignored token like ($1, $2, $3...). Fixed this handler

 #589841: [sitecore-jss-nextjs] use token in redirects

---

CHANGELOG.md
packages/sitecore-jss-react/src/components/Placeholder.tsx

Remove workaround from bug 540957 (https://github.com/Sitecore/jss/pull/1161) that addressed placeholder hydration errors.
This will bring back hydration console errors when using jss connected mode in rendering host, but will get rid of issues when using rendering host in production mode instead (which is a better tradeoff).

[nextjs] Fix double placeholder in Experience Editor in production mode

---

CHANGELOG.md
packages/sitecore-jss-nextjs/src/middleware/redirects-middleware.test.ts
packages/sitecore-jss-nextjs/src/middleware/redirects-middleware.ts

Fixed pattern for redirects of tokens

#589841: [sitecore-jss-nextjs] use token in redirects. fixed pattern

---

CHANGELOG.md
packages/create-sitecore-jss/src/templates/nextjs-sxa/src/lib/middleware/plugins/redirects.ts
packages/create-sitecore-jss/src/templates/nextjs/src/middleware.ts
packages/sitecore-jss-nextjs/src/middleware/middleware.test.ts
packages/sitecore-jss-nextjs/src/middleware/middleware.ts
packages/sitecore-jss-nextjs/src/middleware/multisite-middleware.ts
packages/sitecore-jss-nextjs/src/middleware/personalize-middleware.ts
packages/sitecore-jss-nextjs/src/middleware/redirects-middleware.test.ts

* Don't skip files in Next middleware
* Exclude files only for redirects-middleware, rest of middlewares exclude files as usually

[sitecore-jss-nexjts] Redirects don't work when file extensions present in a route

---

CHANGELOG.md
packages/sitecore-jss/src/site/graphql-siteinfo-service.test.ts
packages/sitecore-jss/src/site/graphql-siteinfo-service.ts

* Use pagination to prefetch all the sites
* For consistency, added **pageSize** property as a part of the config

[Next.js][Multisite] GraphQLSiteInfoService does not fetch more than 10 sites

---

CHANGELOG.md
packages/sitecore-jss-vue/src/components/Link.test.ts
packages/sitecore-jss-vue/src/components/Link.ts

* Pulled changes from #1407 
* Added unit tests to cover this case

[sitecore-jss-vue] Link component renders link description even when children are provided

---

CHANGELOG.md
packages/create-sitecore-jss/src/templates/nextjs-sxa/src/components/BYOCWrapper.tsx
packages/sitecore-jss-nextjs/src/index.ts
packages/sitecore-jss-react/src/components/BYOCRenderer.test.tsx
packages/sitecore-jss-react/src/components/BYOCRenderer.tsx
packages/sitecore-jss-react/src/components/FEaaSComponent.tsx
packages/sitecore-jss-react/src/components/MissingComponent.test.tsx
packages/sitecore-jss-react/src/components/MissingComponent.tsx
packages/sitecore-jss-react/src/index.ts
packages/sitecore-jss-react/src/utils.test.ts
packages/sitecore-jss-react/src/utils.ts

BYOC unwrapped allows developers to create components and then use them without following the component deployment guidelines. It means that components:
- Can use any prop type, without consideration for layout service data
- Be located anywhere
- Are not required to be deployed to Sitecore as rendering items
Right now BYOC can be used with Component Builder, but this PR allows using registered components on a page, directly.
Minor side effect of this PR is changes to MissingComponent - it can now display custom error messages to accommodate BYOC usecases.

[nextjs] Bring your own code (BYOC) feature

---

CHANGELOG.md
packages/create-sitecore-jss/src/templates/nextjs-sxa/src/pages/api/sitemap.ts

Reverted changes. Reason: it was not a bug. Redirect to 404 if sitemap isn't generated - it's ok

 #563014: [templates/nextjs-sxa] sitemap. reverted chanegs

---

CHANGELOG.md
packages/create-sitecore-jss/src/templates/nextjs/src/lib/page-props-factory/plugins/component-props.ts
packages/sitecore-jss-nextjs/src/index.ts
packages/sitecore-jss-nextjs/src/services/component-props-service.test.ts
packages/sitecore-jss-nextjs/src/services/component-props-service.ts
packages/sitecore-jss-nextjs/src/sharedTypes/component-props.ts

Previously, if an error was thrown in component-level getStatic/ServerSideProps, it was swallowed and the page was rendered without the specific component.
* This PR provides better error handling, it will throw an error by accumulating all the component-level errors
* Added _componentName_ in the error log for a better understating of the root cause

[Nextjs] Better error handling for component-level data fetching

---

CHANGELOG.md
packages/create-sitecore-jss/src/templates/nextjs-sxa/src/lib/page-props-factory/plugins/feaas-themes.ts
packages/sitecore-jss-nextjs/src/index.ts
packages/sitecore-jss-react/src/index.ts
packages/sitecore-jss/feaas.d.ts
packages/sitecore-jss/feaas.js
packages/sitecore-jss/src/feaas/index.ts
packages/sitecore-jss/src/feaas/themes.test.ts
packages/sitecore-jss/src/feaas/themes.ts
packages/sitecore-jss/tsconfig.json

This PR builds upon @illiakovalenko 's original work on supporting stylesheets (https://github.com/Sitecore/jss/pull/1359).
The basic idea is for JSS to load stylesheets in SSR whenever FEAAS themes are applied to components on page.
Current PR ensures style parameters can be read from component params, component data source or component class.

[FEAAS][BYOC] Stylesheet loading support

---

CHANGELOG.md
packages/sitecore-jss-nextjs/src/utils/utils.ts

Part of the effort to improve Netlify support. Allows for public URL detection so that specifying PUBLIC_URL env variable is no longer needed.
Uses Netlify's DEPLOY_URL variable to be in line with our implementation for Vercel support.

[Netlify] Allow public URL detection

---

CHANGELOG.md
packages/create-sitecore-jss/src/templates/nextjs/scripts/generate-component-builder/index.ts
packages/create-sitecore-jss/src/templates/nextjs/scripts/generate-component-builder/plugins/component-builder.ts
packages/create-sitecore-jss/src/templates/nextjs/scripts/generate-component-builder/plugins/components.ts
packages/create-sitecore-jss/src/templates/nextjs/scripts/generate-component-builder/plugins/packages.ts
packages/create-sitecore-jss/src/templates/react/scripts/generate-component-builder/plugins/component-builder.js
packages/create-sitecore-jss/src/templates/react/scripts/generate-component-builder/plugins/components.js
packages/create-sitecore-jss/src/templates/react/scripts/generate-component-builder/plugins/packages.js
packages/sitecore-jss-dev-tools/src/templating/components.ts
packages/sitecore-jss-dev-tools/src/templating/nextjs/generate-component-builder.test.ts
packages/sitecore-jss-dev-tools/src/templating/nextjs/generate-component-builder.ts
packages/sitecore-jss-dev-tools/src/templating/react/generate-component-builder.test.ts
packages/sitecore-jss-dev-tools/src/templating/react/generate-component-builder.ts

* Introduced a new **components** property for _ComponentBuilder_ in order to be able to bring custom components that can be placed under a specific path that doesn't match the default one.
* Added a new **components** plugin (react, next), where you can configure the _components_ property.

[sitecore-jss-dev-tools] [Nextjs] [React] Introduce "components" configuration for ComponentBuilder

---

CHANGELOG.md
packages/create-sitecore-jss/src/templates/nextjs-sxa/src/components/Image.tsx

See #1593.
Don't wrap IMG with A when TargetUrl has no href value.
AFAIK there are no unit tests for nextjs-sxa components.

[nextjs-sxa] Don't let Image component wrap <img> with <a> tag when TargetUrl is not configured

---

CHANGELOG.md
packages/create-sitecore-jss/src/templates/nextjs/src/lib/page-props-factory/plugins/normal-mode.ts

Dictionary service can fail and throw a 5xx error when requesting a language on a page with no version in this language. This PR fixes it.

[nextjs] Only fetch dictionary data when layout data is present

---

CHANGELOG.md
packages/sitecore-jss-nextjs/src/services/base-graphql-sitemap-service.ts
packages/sitecore-jss-nextjs/src/services/graphql-sitemap-service.test.ts

- Set default page size for the sitemap GraphQL request to 100
- Switch from using a parallel approach (Promise.all) to a serial approach when fetching each language.

[sitecore-jss-nextjs] Reduce the amount of Edge API calls during fetch `getStaticPaths`

---

CHANGELOG.md
packages/create-sitecore-jss/src/templates/nextjs/.eslintrc
packages/create-sitecore-jss/src/templates/nextjs/package.json
packages/create-sitecore-jss/src/templates/nextjs/tsconfig.json
packages/sitecore-jss-nextjs/package.json
packages/sitecore-jss-react/package.json
yarn.lock

Fix linting and react types errors for monorepo

---

CHANGELOG.md
packages/sitecore-jss-react-forms/src/components/form.test.tsx
packages/sitecore-jss-react-forms/src/components/form.tsx

Original fix had problems with adding 'inert' attribute on state change. This fixes it.

[sitecore-jss-react-forms] Follow up to form disable bugfix

---

CHANGELOG.md
packages/create-sitecore-jss/src/templates/nextjs/package.json
packages/sitecore-jss-nextjs/package.json
packages/sitecore-jss-nextjs/src/components/Link.test.tsx
packages/sitecore-jss-nextjs/src/components/RichText.test.tsx
yarn.lock

[templates/nextjs] [sitecore-jss-nextjs] Upgrade Nextjs to `13.4.16`

---

CHANGELOG.md
packages/create-sitecore-jss/src/templates/nextjs-sxa/src/pages/404.tsx
packages/create-sitecore-jss/src/templates/nextjs-sxa/src/pages/500.tsx
packages/create-sitecore-jss/src/templates/nextjs/.env
packages/create-sitecore-jss/src/templates/nextjs/src/lib/dictionary-service-factory.ts
packages/create-sitecore-jss/src/templates/nextjs/src/lib/layout-service-factory.ts
packages/sitecore-jss/src/site/graphql-error-pages-service.ts
yarn.lock

Follow up to rate limits PR.
ErrorPages service from SXA may cause trouble during build when rate limits are enabled. This PR extends retryer functionality to that service and makes retry count be configurable through env (GRAPH_QL_SERVICE_RETRIES).

[templates/nextjs][templates/nextjs-sxa] Extend retrier to ErrorPagesService and make it configurable through env

---

CHANGELOG.md
packages/sitecore-jss-react/src/components/BYOCComponent.test.tsx
packages/sitecore-jss-react/src/components/BYOCComponent.tsx
yarn.lock

The BYOC component should parse the passed props when fetchedDatais not present.

[sitecore-jss-react] Handle BYOC Component error

---

CHANGELOG.md
packages/sitecore-jss-proxy/src/index.ts

When customers use `followRedirects: true` and try to send a _HEAD_ request, the proxy server crashes.
This PR addresses this problem. When _followRedirects_ is enabled, _http-proxy-middleware_ initializes a proxy request before _onProxyReq_ is called, after it's initialized there is no way to update the method without accessing to internal properties, so we swap **HEAD** with **GET** before _onProxyReq_ is called, and change it back in _onProxyReq_ event in case it's accessed later.
This change shouldn't be treated as a **_breaking_** change, since Express middleware accepts an array of handlers also.

[sitecore-jss-proxy] Setting "followRedirects" to true" breaks HEAD requests

---

CHANGELOG.md
packages/create-sitecore-jss/src/templates/nextjs-sxa/src/lib/page-props-factory/plugins/error-pages.ts
packages/create-sitecore-jss/src/templates/nextjs/.env
packages/create-sitecore-jss/src/templates/nextjs/src/lib/dictionary-service-factory.ts
packages/create-sitecore-jss/src/templates/nextjs/src/lib/layout-service-factory.ts
packages/sitecore-jss-nextjs/src/services/graphql-sitemap-service.test.ts
packages/sitecore-jss-nextjs/src/services/graphql-sitemap-service.ts
packages/sitecore-jss/src/graphql-request-client.test.ts
packages/sitecore-jss/src/graphql-request-client.ts
packages/sitecore-jss/src/i18n/graphql-dictionary-service.ts
packages/sitecore-jss/src/layout/graphql-layout-service.ts
packages/sitecore-jss/src/site/graphql-error-pages-service.ts

This PR merges changes from:
* https://github.com/Sitecore/jss/pull/1612
* https://github.com/Sitecore/jss/pull/1618, https://github.com/Sitecore/jss/pull/1619

Release 20.2

---

CHANGELOG.md
packages/sitecore-jss-proxy/package.json
packages/sitecore-jss-proxy/src/index.ts
yarn.lock

When customers use `followRedirects: true` and try to send a _HEAD_ request, the proxy server crashes.
This PR contains modified version of the changes introduced in PR https://github.com/Sitecore/jss/pull/1630 , for v.20

[sitecore-jss-proxy] setting "followRedirects" to "true" breaks HEAD requests - fix for v20

---

CHANGELOG.md
packages/sitecore-jss-nextjs/src/editing/constants.ts
packages/sitecore-jss-nextjs/src/editing/editing-data-middleware.test.ts
packages/sitecore-jss-nextjs/src/editing/editing-data-middleware.ts
packages/sitecore-jss-nextjs/src/editing/editing-data-service.test.ts
packages/sitecore-jss-nextjs/src/editing/editing-data-service.ts
packages/sitecore-jss-nextjs/src/editing/editing-render-middleware.test.ts
packages/sitecore-jss-nextjs/src/editing/editing-render-middleware.ts

Added support for deployment protection bypass query string parameters (or any query string parameters, really) on the `editing/render` endpoint. Currently, this is setup for Sitecore (`x-sitecore-protection-bypass`) and Vercel (`x-vercel-protection-bypass`) protection bypass query parameters, but could easily be extended to handle others.

[Next.js] Deployment Protection Bypass support for Editing

---

CHANGELOG.md
packages/create-sitecore-jss/src/templates/nextjs/src/lib/next-config/plugins/cors-header.js

Problem was with custom headers. There was missed extends common nextjs config of headers

 #600951: [templates/nextjs] fixed plugin of cors header

---

packages/create-sitecore-jss/src/templates/nextjs/tsconfig.json

Monorepo was failing with 'useContext' error (cannot read properties of null). This PR should fix it.

[templates/nextjs] Fix monorepo sample failing on client

---

CHANGELOG.md
packages/sitecore-jss-react/src/components/Placeholder.test.tsx
packages/sitecore-jss-react/src/components/PlaceholderCommon.tsx

There was issue with dynamic placeholders when there uses two and more dynamic placeholders in one component.
Added conditional for correct working dynamic placeholders.

 #597453: [sitecore-jss-react] fixed rendering with two and more dynamic placeholders

---

CHANGELOG.md
packages/sitecore-jss/src/feaas/themes.test.ts
packages/sitecore-jss/src/feaas/themes.ts

Introduced support for the **published** and **staged** revisions of stylesheets/themes:
* **staged**: Editing, Preview modes
* **published**: Normal mode
Updated unit tests structure to be split by _editing_, _normal_ modes in the right way.

[sitecore-jss] Support for both 'published' and 'staged' revisions of FEAAS stylesheets/themes

---

CHANGELOG.md
packages/create-sitecore-jss/src/templates/nextjs/src/lib/graphql-client-factory/create.ts
packages/sitecore-jss-nextjs/graphql-client.d.ts
packages/sitecore-jss-nextjs/graphql-client.js
packages/sitecore-jss-nextjs/src/graphql-client/index.ts
packages/sitecore-jss-nextjs/src/index.ts
packages/sitecore-jss-nextjs/src/utils/index.ts
packages/sitecore-jss-nextjs/tsconfig.json

Nextjs app fails if imports from the main '@sitecore-jss/sitecore-jss-nextjs' module are used in middeware. This PR moves some of the needed imports to submodules to fix middleware-related build issues.

[sitecore-jss-nextjs][templates/nextjs] Move graphql client imports to allow usage in middleware

---

packages/create-sitecore-jss/src/templates/nextjs/src/lib/graphql-client-factory/create.ts
packages/sitecore-jss-nextjs/graphql-client.d.ts
packages/sitecore-jss-nextjs/graphql-client.js
packages/sitecore-jss-nextjs/graphql.d.ts
packages/sitecore-jss-nextjs/graphql.js
packages/sitecore-jss-nextjs/src/graphql/index.ts
packages/sitecore-jss-nextjs/src/index.ts
packages/sitecore-jss-nextjs/src/utils/index.ts
packages/sitecore-jss-nextjs/tsconfig.json

Rework of https://github.com/Sitecore/jss/pull/1648 with a change to submodule name to align it with @sitecore-jss/sitecore-jss package's exports naming.

[sitecore-jss-nextjs][templates/nextjs] Move graphql client imports - followup

---

CHANGELOG.md
packages/create-sitecore-jss/src/templates/nextjs-multisite/scripts/config/plugins/multisite.ts

When building on XM Cloud, the CM instance is not necessarily provisioned and available. The site info fetch fails in this case (but build continues). This change prevents site fetch from even being attempted. Note we're already disabling CM usage during static generation (via `DISABLE_SSG_FETCH`).

[Next.js] [Multisite] Skip site info fetch on XM Cloud rendering/editing host builds

---

packages/sitecore-jss/src/feaas/themes.test.ts
packages/sitecore-jss/src/feaas/themes.ts

[sitecore-jss] Fix FEAAS stylesheet issue

---

package.json

Scaffolding of any app in monorepo fails with the latest release of `eslint` peer dependency `eslint-plugin-jsx-a11y: 6.8.0`

Fix `yarn watch` 

---

CHANGELOG.md
packages/create-sitecore-jss/src/init-runner.test.ts
packages/create-sitecore-jss/src/init-runner.ts
packages/create-sitecore-jss/src/initializers/nextjs-xmcloud/index.ts
packages/create-sitecore-jss/src/initializers/nextjs-xmcloud/remove-dev-dependencies.ts
packages/create-sitecore-jss/src/templates/nextjs-xmcloud/src/lib/next-config/plugins/monorepo-xmcloud.js

Follow-up to https://github.com/Sitecore/jss/pull/1653 which fixes the following issues:
- Fix issue where nextjs-xmcloud template's /src/lib/next-config/plugins/monorepo.js wasn't being cleaned up properly. Use dedicated monorepo-xmcloud.js instead.
- Fix issue with init-runner where response.initializers would prevent any following initializers to be skipped (return statement caused early exit)

[Next.js] Fixes for `nextjs-xmcloud` Initializer Template

---

CHANGELOG.md
packages/create-sitecore-jss/src/initializers/nextjs/prompts.ts

Minor fix to prevent "Are you building for XM Cloud?" prompt if `nextjs-xmcloud` template was specified on CLI.

[Next.js] Fixes (part 2) for `nextjs-xmcloud` Initializer Template

---

CHANGELOG.md
packages/create-sitecore-jss/src/templates/nextjs-xmcloud/package.json
packages/create-sitecore-jss/src/templates/nextjs-xmcloud/src/Bootstrap.tsx

This resolves the "Could not resolve site for name" error when building on XM Cloud editing hosts.
Also (unrelated), this PR bumps the @sitecore/components package to latest (1.1.2).

[Next.js] [XMC] Fix "Could not resolve site for name" error on XMC rendering host build

---

CHANGELOG.md
packages/sitecore-jss-nextjs/src/context/context.test.ts
packages/sitecore-jss-nextjs/src/context/context.ts

In case we are trying to merge _context_ instance as an object we lose all available methods, e.g _getSDK_.
This PR changes _getSDK_ to use arrow function, in this case it's available after the merge operation

[Nextjs] [Context] Context's getSDK is non-enumerable

---

CHANGELOG.md
packages/create-sitecore-jss/src/templates/nextjs-xmcloud/src/lib/page-props-factory/plugins/feaas-themes.ts
packages/sitecore-jss/src/feaas/themes.test.ts
packages/sitecore-jss/src/feaas/themes.ts

Use Edge Platform file proxy for FEaaS stylesheets. This replaces both the CDN URL (https://github.com/Sitecore/jss/pull/1645) and staged/published (https://github.com/Sitecore/jss/pull/1644) determination we used previously. These are now determined by the Edge Platform environment and Context ID (Preview vs Live), respectively.

[Next.js] Use Edge Platform file proxy for FEaaS stylesheets

---

CHANGELOG.md
packages/create-sitecore-jss/src/templates/node-headless-ssr-proxy/src/config.ts

The `sc_site` query string parameter is now added to Layout Service requests by default. This is to ensure that the Layout Service request is routed to the correct Sitecore site when using the proxy. It ensures that the target site is resolved correctly for both Layout and Dictionary Service requests (For Dictionary Service requests, the `sc_site` parameter is already added to the request path, see [config.ts](https://github.com/Sitecore/jss/blob/dev/packages/create-sitecore-jss/src/templates/node-headless-ssr-proxy/src/config.ts#L32), [path](https://github.com/Sitecore/jss/blob/dev/packages/sitecore-jss/src/i18n/rest-dictionary-service.ts#L84)).

[node-headless-ssr-proxy] Add sc_site qs parameter to Layout Service requests by default

---

CHANGELOG.md
packages/create-sitecore-jss/src/templates/nextjs-xmcloud/src/byoc/index.ts
packages/create-sitecore-jss/src/templates/nextjs-xmcloud/src/components/CdpPageView.tsx
packages/sitecore-jss-nextjs/src/context/context.test.ts
packages/sitecore-jss-nextjs/src/context/context.ts

This PR fixes type errors when creating custom BYOC component that use context SDKs (i.e. Events Cloud SDK).
- Remove `undefined` from `getSDK` return type. This matches the augmented type we have in `@sitecore/components/context`. If an invalid SDK is passed somehow then we return a rejected promise instead.
- Also added `import @sitecore/components/context` in byoc/index so that the augmented types are included by default.

[BYOC] Fix type errors when creating custom BYOC components that use context SDKs

---

CHANGELOG.md
packages/sitecore-jss-nextjs/src/middleware/redirects-middleware.test.ts
packages/sitecore-jss-nextjs/src/middleware/redirects-middleware.ts

When param of trailingSlash is true the targetURL in redirects middleware logic doesn't match with pattern.
Added a little fix in logic.

 #603676: [sitecore-jss-nextjs] fixed redirect middleware logic

---

CHANGELOG.md
azure-pipelines.yml
packages/create-sitecore-jss/package.json
packages/sitecore-jss-angular/package.json
packages/sitecore-jss-angular/src/test.ts
packages/sitecore-jss-cli/package.json
packages/sitecore-jss-dev-tools/package.json
packages/sitecore-jss-dev-tools/src/templating/react/generate-component-builder.ts
packages/sitecore-jss-forms/package.json
packages/sitecore-jss-nextjs/package.json
packages/sitecore-jss-nextjs/src/editing/editing-render-middleware.ts
packages/sitecore-jss-proxy/package.json
packages/sitecore-jss-react-forms/package.json
packages/sitecore-jss-react-native/package.json
packages/sitecore-jss-react/package.json
packages/sitecore-jss-rendering-host/package.json
packages/sitecore-jss-vue/package.json
packages/sitecore-jss/package.json

* Updated repository to use Node.js v20.x (LTS)
* Fixed the 'Command line is too long' error that occurred when running 'npm run lint:packages'. The issue was due to the _eslint_ command interpreting the regular expression as a list of files to be passed via the command line. The solution was to pass the regular expression as a string to the _eslint_ command..
* Fixed minor eslint issues, not related to upgrade

[Chore] Upgrade to Node.js 20.x

---

CHANGELOG.md
packages/sitecore-jss-react/src/components/BYOCComponent.test.tsx
packages/sitecore-jss-react/src/components/BYOCComponent.tsx

* Use **ComponentDataOverride** instead of **ComponentProps** for _BYOCComponent_

[sitecore-jss-react] Use ComponentDataOverride instead of ComponentProps for BYOCComponent

---

CHANGELOG.md
packages/create-sitecore-jss/src/templates/nextjs-sxa/src/components/Image.tsx

When image is empty there was set property background-image. This way made an additional request with status - 404.
Fixed

[templates/nextjs-sxa] fixed request background image if it is empty

---

packages/sitecore-jss-react/package.json
packages/sitecore-jss-react/src/components/BYOCComponent.test.tsx
packages/sitecore-jss-react/src/components/BYOCComponent.tsx
packages/sitecore-jss-react/src/components/FEaaSComponent.test.tsx
packages/sitecore-jss-react/src/components/FEaaSComponent.tsx
packages/sitecore-jss-react/src/utils.ts
yarn.lock

This is a change to how FEEAS and BYOC handle fetched data.
FEAASComponent:
- ComponentDataOverride will only be used in server context. No change to functionality, since FEAASComponent is not used directly by Sitecore
- Data from item datasource is now always used by FEAAS, without overwriting anything from fetched data (rendering params or fetch endpoint)
BYOCComponent:
- Data from item datasource is now always used by BYOC, without overwriting anything from fetched data

[packages/sitecore-jss-react] Combine fetched and datasource item props in BYOC and FEAAS

---

CHANGELOG.md
packages/sitecore-jss-nextjs/src/middleware/redirects-middleware.ts

A loop of error occured when pattern of redirect had default locale.
This fix remove default locale in pattern because req.url hasn't default locale in pathname.

 [sitecore-jss-nextjs]: fixed redirects middleware when pattern use default locale in regexp

---

CHANGELOG.md
CONTRIBUTING.md
packages/create-sitecore-jss/package.json
packages/sitecore-jss-angular-schematics/package.json
packages/sitecore-jss-angular/package.json
packages/sitecore-jss-cli/package.json
packages/sitecore-jss-dev-tools/package.json
packages/sitecore-jss-forms/package.json
packages/sitecore-jss-nextjs/package.json
packages/sitecore-jss-proxy/package.json
packages/sitecore-jss-react-forms/package.json
packages/sitecore-jss-react-native/package.json
packages/sitecore-jss-react/package.json
packages/sitecore-jss-rendering-host/package.json
packages/sitecore-jss-vue/package.json
packages/sitecore-jss/package.json

Removed _npm_ field since it requires customer to use **npm 10**, even when customer uses **node < 18.19**, which provides **npm 9**

[Chore] Removed "npm" field from "engines" property

---

CHANGELOG.md
packages/create-sitecore-jss/src/templates/nextjs-xmcloud/src/Bootstrap.tsx
packages/sitecore-jss-nextjs/src/context/context.test.ts
packages/sitecore-jss-nextjs/src/context/context.ts

Extends shared context with pageState property. This allows BYOC components and CloudSDK functionality to adjust behavior based on the current state (editing, preview, normal).

[sitecore-jss-nextjs] Add page state into shared context

---

CHANGELOG.md
packages/create-sitecore-jss/src/templates/nextjs-xmcloud/src/lib/next-config/plugins/feaas.js

BYOC components doesn't render on pages because of double registration i.e one on server and another on client.

Fix double registration of byoc components

---

CHANGELOG.md
packages/create-sitecore-jss/src/templates/nextjs-xmcloud/src/lib/next-config/plugins/feaas.js

Fix FEAAS webpack config 

---

CHANGELOG.md
packages/create-sitecore-jss/src/templates/nextjs-styleguide/src/pages/_app.tsx

Scaffolding a nextjs styleguide+xmcloud app causes Event context to not be initialized. Ensuring Bootstrap is used in styleguide fixes this issue.
This should be cherrypicked in v21 branch ahead of 21.6 release.

[templates/nextjs-styleguide] Ensure Bootstrap component is used

---

CHANGELOG.md
packages/create-sitecore-jss/src/templates/nextjs-xmcloud/src/lib/context/sdk/events.ts
packages/sitecore-jss-nextjs/src/context/context.test.ts
packages/sitecore-jss-nextjs/src/context/context.ts

Events SDK should not initialize in dev environment or server context. This PR ensures Events SDK promise is not pending in such situations and will reject instead. Context logic has been made to handle initialization rejects.

[sitecore-jss-nextjs] Reject SDK promise when init was rejected

---

CHANGELOG.md
packages/create-sitecore-jss/src/templates/nextjs-xmcloud/src/components/CdpPageView.tsx

A bugfix follow up to https://github.com/Sitecore/jss/pull/1712 . Adds a failsafe catch for getSDK call in CdpPageView component.

[templates/nextjs-xmcloud] Failsafe catch for getSDK

---

CHANGELOG.md
packages/sitecore-jss-nextjs/src/context/context.test.ts
packages/sitecore-jss-nextjs/src/context/context.ts

Follow up to context changes.
- Ensure SDK init methods can throw without halting context init
- Ensure getSDK method can properly resolve and reject
- Ensure relevant message is passed when getSDK rejects

[sitecore-jss-nextjs] Rework promises in context implementation

---

CHANGELOG.md
packages/create-sitecore-jss/src/templates/nextjs-styleguide/src/components/graphql/GraphQL-ConnectedDemo.dynamic.tsx
packages/create-sitecore-jss/src/templates/nextjs/scripts/fetch-graphql-introspection-data.ts

Modify all `GraphQLRequestClient` import statements so that it gets imported from the `/graphql` submodule

[templates/nextjs] [templates/nextjs-styleguide] Update deprecated GraphQLRequestClient import statement

---

CHANGELOG.md
packages/sitecore-jss-nextjs/src/components/NextImage.test.tsx
packages/sitecore-jss-nextjs/src/components/NextImage.tsx

Currently the custom loader function i.e. sitecoreLoader formats the URL to use Sitecore's image optimization. However, it is limited to image resizing and we would like to use the vercel's built-in image optimization.

[sitecore-jss-nextjs] Enable NextImage to use built-in image optimization from vercel

---

CHANGELOG.md
packages/create-sitecore-jss/src/templates/nextjs-xmcloud/src/lib/next-config/plugins/feaas.js
packages/create-sitecore-jss/src/templates/nextjs-xmcloud/src/middleware.ts
packages/create-sitecore-jss/src/templates/nextjs-xmcloud/src/pages/api/editing/feaas/render.ts
packages/create-sitecore-jss/src/templates/nextjs-xmcloud/src/pages/feaas/render.tsx
packages/sitecore-jss-nextjs/src/editing/editing-render-middleware.ts
packages/sitecore-jss-nextjs/src/editing/feaas-render-middleware.test.ts
packages/sitecore-jss-nextjs/src/editing/feaas-render-middleware.ts
packages/sitecore-jss-nextjs/src/editing/index.ts
packages/sitecore-jss-nextjs/src/editing/render-middleware.test.ts
packages/sitecore-jss-nextjs/src/editing/render-middleware.ts

Added a new endpoint to enable Component Builder to work with BYOC components registered in a JSS application
- The `FEAASRenderMiddleware` ( _/api/editing/feaas/render_) will
1) Enable Next.js Preview Mode.
2) Redirect to the /feaas/render page.
> NOTE: Handles Vercel protection bypass, custom server url etc.
If "src" query parameter is provided, the page will render a FEAAS component.
The page provides all the registered FEAAS components
- The `FEAASRender` (_/feaas/render_) page is responsible for
1) Rendering the FEAAS component if the "feaasSrc" is provided.
2) Rendering all the registered components.
3) The page is rendered only if it's requested by the api route (/api/editing/feaas/render) using the preview mode.
- Introduced a common `RenderMiddleware`

[Next.js] [BYOC] Component Builder integration endpoint

---

CHANGELOG.md
packages/create-sitecore-jss/src/templates/nextjs/next.config.js

… hostnames
This PR adds default image remotePatterns configuration for whitelisting remove image hostnames.
Only Images from the whitelisted hostnames will be served from the Next.js Image Optimization API - see https://nextjs.org/docs/app/api-reference/components/image#remotepatterns

[templates/nextjs] Add default image remotePatterns config for whitelisting remote image hostnames

---

CHANGELOG.md
packages/create-sitecore-jss/src/templates/nextjs/next.config.js

Whitelist additional hostname for feaas component images to use with Next.js Image Optimization API. Addition to #1732

[templates/nextjs] Whitelist additional hostname for feaas component images to use with Next.js Image Optimization API

---

.prettierignore
CHANGELOG.md
packages/sitecore-jss/src/graphql-request-client.test.ts
packages/sitecore-jss/src/graphql-request-client.ts

At present, the initial retry delay evaluated to 2 seconds, which becomes relatively high for subsequent retries when assessed in an exponential manner. We aim to initiate the first retry after a 1-second wait instead.

[sitecore-jss] Optimize initial Retry delay time

---

CHANGELOG.md
packages/sitecore-jss-nextjs/src/middleware/redirects-middleware.ts

The redirects middleware has been fixed when pattern has locale and target is absolute url. There was bug when redirect logic paste locale in absolute url

 [sitecore-jss-nextjs] #607601: redirects middleware has been fixed 

---

packages/sitecore-jss/src/graphql-request-client.test.ts

Retry unit tests take a long time to complete- by design. This PR is a small QoL change for devs. Putting all retry tests under the single root makes disabling them during development easier, when working on non-graphql-client logic.

[chore][sitecore-jss] Set single root for retry unit tests

---

CHANGELOG.md
packages/create-sitecore-jss/src/templates/nextjs-multisite/scripts/config/plugins/multisite.ts
packages/create-sitecore-jss/src/templates/nextjs-xmcloud/src/lib/graphql-client-factory/create.ts
packages/sitecore-jss/src/graphql-request-client.ts
packages/sitecore-jss/src/site/graphql-siteinfo-service.test.ts
packages/sitecore-jss/src/site/graphql-siteinfo-service.ts

SiteInfoGraphQLService now accepts a boolean xmCloud parameter. The parameter enables using site query - and it will be enabled by default when xmcloud addon is used via clientConfig.

[sitecore-jss][templates/nextjs-xmcloud] Enable site query in XMCloud

---

CHANGELOG.md
packages/sitecore-jss-react/src/components/Placeholder.test.tsx
packages/sitecore-jss-react/src/components/PlaceholderCommon.tsx
packages/sitecore-jss-react/src/test-data/non-ee-data.ts

The bug appeared when user add a new dynamic placeholder for example: accordion-1-{*} and it didn't work.
The pattern of detecting has been changed to universal pattern.

 [sitecore-jss-react] Fix the pattern of detecting dynamic placeholder using double digit

---

CHANGELOG.md
packages/create-sitecore-jss/src/templates/nextjs-multisite/src/lib/middleware/plugins/multisite.ts
packages/sitecore-jss-nextjs/src/middleware/multisite-middleware.test.ts
packages/sitecore-jss-nextjs/src/middleware/multisite-middleware.ts

This PR provides the option for the developer to add attributes to the `sc_site` cookie: `secure`, `httpOnly`, `expires`, `sameSite`

[NextJs] Add attributes to 'sc_site' cookie

---

CHANGELOG.md
packages/sitecore-jss/src/i18n/graphql-dictionary-service.ts
packages/sitecore-jss/src/layout/graphql-layout-service.ts
packages/sitecore-jss/src/site/graphql-error-pages-service.ts

Enable the `Layout` and `dictionary` service to use custom `retryStrategy`.

[sitecore-jss] Fix custom `retryStrategy`

---

CHANGELOG.md
packages/sitecore-jss/src/personalize/layout-personalizer.test.ts
packages/sitecore-jss/src/personalize/layout-personalizer.ts

This PR makes sure that any unused personalized variants are deleted before sending layout data to the client, thus are completely hidden from the customer.

[Personalize] Remove unused component experiences from layout

---

CHANGELOG.md
packages/sitecore-jss/src/graphql-request-client.test.ts
packages/sitecore-jss/src/graphql-request-client.ts

[sitecore-jss] Use ['Retry-After'] header value without rounding off

---

CHANGELOG.md
packages/create-sitecore-jss/src/templates/nextjs-xmcloud/package.json
packages/sitecore-jss-nextjs/package.json
yarn.lock

Updated @sitecore-cloudsdk/* dependencies to version ^0.2.4 to avoid a mismatch between _devDependencies_ and _peerDependencies_

Updated @sitecore-cloudsdk/* dependencies to version ^0.2.4

---

CHANGELOG.md
packages/sitecore-jss/src/layout/graphql-layout-service.ts

Added optional chaining to handle null items for layout service.

[sitecore-jss] Handle null items in graphql layout service

---

CHANGELOG.md
docs/upgrades/unreleased.md
packages/create-sitecore-jss/src/templates/nextjs-multisite/scripts/config/plugins/multisite.ts
packages/sitecore-jss/src/site/graphql-siteinfo-service.test.ts
packages/sitecore-jss/src/site/graphql-siteinfo-service.ts

- `SiteInfoGraphQLService` now uses the site query by default for both XP and XMCloud. Search query has been removed.
- Previously introduced Boolean `useSiteQuery` switch for XMCLoud users has been removed.

[sitecore-jss] Switch to edge site query for XP

---

CHANGELOG.md
packages/create-sitecore-jss/src/templates/node-headless-ssr-proxy/package.json
packages/sitecore-jss-dev-tools/.vscode/launch.json
packages/sitecore-jss-dev-tools/package.json
packages/sitecore-jss-dev-tools/src/pipelines/runner.ts
packages/sitecore-jss-vue/package.json
yarn.lock

Security vulnerabilities audit

[Chore] Security vulnerabilities audit

---

CHANGELOG.md
docs/upgrades/unreleased.md
packages/create-sitecore-jss/src/templates/nextjs-xmcloud/package.json
packages/sitecore-jss-nextjs/package.json
packages/sitecore-jss-nextjs/src/middleware/multisite-middleware.test.ts
packages/sitecore-jss-nextjs/src/middleware/personalize-middleware.ts
yarn.lock

Update CloudSDK personalize and events dependencies to version 0.3.0

[Chore][nextjs] Update CloudSDK dependencies to 0.3.0

---

CHANGELOG.md
packages/create-sitecore-jss/src/templates/react/src/components/fields/Styleguide-FieldUsage-Image.js

Replaced deprecated _media_ property by _field_ property

[React] Replaced deprecated 'media' Styleguide-Image property by 'field'

---

CHANGELOG.md
docs/upgrades/unreleased.md
packages/create-sitecore-jss/src/templates/angular/scripts/generate-config.ts
packages/create-sitecore-jss/src/templates/nextjs/scripts/generate-config.ts
packages/create-sitecore-jss/src/templates/react/scripts/generate-config.js
packages/create-sitecore-jss/src/templates/vue/scripts/generate-config.js

An extra trim() call in generate-config scripts to cleanup any unwanted whitespace characters.
- nextjs app builds and works in prodcuction mode on macOS 15 and Windows
- RAV apps work OK on MacOS 15 in disconnected mode

[nextjs][RAV] avoid unexpected linebreaks when generating config

---

CHANGELOG.md
packages/sitecore-jss-react/src/components/ErrorBoundary.test.tsx
packages/sitecore-jss-react/src/components/Placeholder.test.tsx
packages/sitecore-jss-react/src/components/Placeholder.tsx
packages/sitecore-jss-react/src/components/PlaceholderCommon.tsx
packages/sitecore-jss-react/src/test-data/ee-data.ts

This PR fixes extra markup being generated for empty placeholders, which broke adding components in Experience Editor.
This also does a couple other things:
- Add 'empty placeholder' mock data without 'rendering' code blocks. Empty placeholders would not render them.
- Shorten the code blocks content for empty placeholder data, making it easier to maintain and read
- make all the 'empty placeholder' unit tests use the 'empty placeholder' mock data

[React][nextjs] Do not apply ErrorBoundaries to empty placeholders

---

CHANGELOG.md
packages/create-sitecore-jss/src/templates/nextjs-sxa/src/components/Image.tsx
packages/create-sitecore-jss/src/templates/nextjs-sxa/src/components/Title.tsx

Within a new approach(Shallow chromes - metadata) which will be implemented the SXA components has been refactored

[templates/nextjs-sxa] SXA components has been reworked with supporting metadata

---

CHANGELOG.md
docs/upgrades/22x/22.0.md
docs/upgrades/unreleased.md
packages/sitecore-jss-react/src/components/Placeholder.test.tsx
packages/sitecore-jss-react/src/enhancers/withSitecoreContext.tsx
packages/sitecore-jss-react/src/index.ts

- Fix unit tests
- update upgrade guide to inform about breaking changes

[Editing Integration] Placeholder chromes hydration (Update - Part 2)

---

CHANGELOG.md
packages/sitecore-jss-react/src/components/ErrorBoundary.test.tsx
packages/sitecore-jss-react/src/components/ErrorBoundary.tsx

This PR is a follow up to https://github.com/Sitecore/jss/pull/1786 and updates the error message display logic so that component name is being shown in the error message in preview mode (in addition to edit mode); it also updates the logging logic and now failed component name and rendering uid are being logged in the console when in edit/preview/development mode.

[sitecore-jss-react] ErrorBoundary - Show error message with failed component name in preview mode

---

CHANGELOG.md
docs/upgrades/unreleased.md
packages/create-sitecore-jss/src/templates/nextjs-styleguide/src/components/styleguide/Styleguide-Layout-Tabs.tsx
packages/sitecore-jss-nextjs/src/components/Placeholder.tsx
packages/sitecore-jss-nextjs/src/index.ts
packages/sitecore-jss-react/src/components/Placeholder.tsx
packages/sitecore-jss-react/src/components/PlaceholderCommon.tsx
packages/sitecore-jss-react/src/components/SitecoreContext.test.tsx
packages/sitecore-jss-react/src/enhancers/withFieldMetadata.tsx
packages/sitecore-jss-react/src/enhancers/withSitecoreContext.tsx
packages/sitecore-jss-react/src/index.ts
packages/sitecore-jss/src/utils/index.ts
packages/sitecore-jss/src/utils/utils.ts

* Made a cleanup for _withSitecoreContext_ HOC. (For reviewer) Please, also check the initial implementation in _dev_ branch
* Set _editable=true_ in _withFieldMetadata_ HOC
* Removed _ComponentConsumerProps_ type since it's redundant
* _sitecoreContext_ set as a required property, as it was before work on _editing integration_ feature

[sitecore-jss-react] [sitecore-jss-nextjs] Reconciled withSitecoreContext and Placeholder types

---

CHANGELOG.md
packages/sitecore-jss-react/src/components/ErrorBoundary.test.tsx
packages/sitecore-jss-react/src/components/ErrorBoundary.tsx
packages/sitecore-jss-react/src/components/Placeholder.test.tsx
packages/sitecore-jss-react/src/components/PlaceholderCommon.tsx

This PR is a follow up to https://github.com/Sitecore/jss/pull/1786 . It aims to fix an issue in the case where parent component is being used with withPlaceholder HOC and references its child components' props (this issue was caught in automated rendering tests for styleguide tabs component); since each child component is wrapped by ErrorBoundary, this adds additional level of nesting and changes the way parent should access its children's props; this is solved by exposing components props inside the error boundary. 
This PR also: 
- renames ErrorBoundary's customErrorComponent prop;
- updates failing Placeholder unit test to not select ErrorBoundary and check only html elements;

[sitecore-jss-react] ErrorBoundary nested components fix

---

CHANGELOG.md
docs/upgrades/unreleased.md
packages/create-sitecore-jss/src/templates/nextjs-xmcloud/src/Scripts.tsx
packages/sitecore-jss-nextjs/src/index.ts
packages/sitecore-jss-react/src/components/EditingScripts.test.tsx
packages/sitecore-jss-react/src/components/EditingScripts.tsx
packages/sitecore-jss-react/src/index.ts
packages/sitecore-jss/src/layout/models.ts

Introduced `EditingScripts` component to render clientScripts / clientData in editing. Pages requires scripts and data to be rendered in the app to enable editing features.
Used html `script` tag instead of next.js `Script` component since `Script` can't prerender the data if it's not used in a next.js custom `_document.tsx` file

[Editing Integration] Render clientScripts / clientData

---

CHANGELOG.md
packages/sitecore-jss-nextjs/src/editing/editing-config-middleware.test.ts
packages/sitecore-jss-nextjs/src/editing/editing-data-middleware.test.ts
packages/sitecore-jss-nextjs/src/editing/feaas-render-middleware.test.ts
packages/sitecore-jss/src/utils/utils.test.ts
packages/sitecore-jss/src/utils/utils.ts

Followup to https://github.com/Sitecore/jss/pull/1798 
EnforceCors function should also check the previously set CORS headers if present, as editing middleware will be requested from sitecoreApiHost too.

[sitecore-jss-nexts] Consider existing CORS header when running enforceCors

---

CHANGELOG.md
packages/sitecore-jss-react/src/components/Placeholder.tsx
packages/sitecore-jss-react/src/components/PlaceholderCommon.tsx
packages/sitecore-jss-react/src/components/sharedTypes.ts

A quick follow up for https://github.com/Sitecore/jss/pull/1807 to address post-merge comments.
- Add missing comments
- Adjust the types in sharedTypes
- streamline the logic for not wrapping empty components in placeholder

[sitecore-jss-react] Address later comments from PR 1807

---

.github/workflows/publish-npm-package.yml
CHANGELOG.md
packages/create-sitecore-jss/package.json
packages/create-sitecore-jss/src/common/processes/transform.test.ts
packages/create-sitecore-jss/src/common/test-data/pkg.ts
packages/create-sitecore-jss/src/common/test-data/test.package.json
packages/create-sitecore-jss/src/templates/angular/package.json
packages/create-sitecore-jss/src/templates/nextjs/package.json
packages/create-sitecore-jss/src/templates/node-headless-ssr-proxy/package.json
packages/sitecore-jss-angular-schematics/package.json
packages/sitecore-jss-angular/package.json
packages/sitecore-jss-cli/package.json
packages/sitecore-jss-dev-tools/package.json
packages/sitecore-jss-dev-tools/src/templating/utils.test.ts
packages/sitecore-jss-forms/package.json
packages/sitecore-jss-nextjs/package.json
packages/sitecore-jss-proxy/package.json
packages/sitecore-jss-react-forms/package.json
packages/sitecore-jss-react-native/package.json
packages/sitecore-jss-react/package.json
packages/sitecore-jss-rendering-host/package.json
packages/sitecore-jss-vue/package.json
packages/sitecore-jss/package.json
packages/sitecore-jss/src/native-fetcher.test.ts
packages/sitecore-jss/tsconfig.json
yarn.lock

Simple update to node/types and dependencies that were failing with node 20.

[Chore] Bump node types to v20

---

CHANGELOG.md
packages/sitecore-jss-react/src/components/Placeholder.test.tsx
packages/sitecore-jss-react/src/components/Placeholder.tsx
packages/sitecore-jss-react/src/components/PlaceholderCommon.tsx
packages/sitecore-jss-react/src/components/PlaceholderMetadata.test.tsx
packages/sitecore-jss-react/src/components/PlaceholderMetadata.tsx

Expose raw placeholder name not a computed one when dynamic placeholder is rendered

[Editing Integration] Expose raw placeholder name not a computed one when dynamic placeholder is rendered

---

CHANGELOG.md
packages/sitecore-jss-react/src/components/Placeholder.test.tsx
packages/sitecore-jss-react/src/components/PlaceholderCommon.tsx
packages/sitecore-jss-react/src/components/PlaceholderMetadata.test.tsx
packages/sitecore-jss-react/src/components/PlaceholderMetadata.tsx

Fix root placeholder code tags to use empty rendering UID

[Editing Integration] Metadata for root placeholder should use empty/default GUID

---

packages/create-sitecore-jss/src/templates/nextjs-styleguide/src/components/styleguide/Styleguide-Layout-Tabs.tsx

[Next.js] Missing Props type in Styleguide-Layout-Tabs component

---

.github/workflows/notify_teams.yml
CHANGELOG.md
scripts/notify-teams.js

Post announcements about the release on teams channel.

[Chore] Github - Teams Integration

---

CHANGELOG.md
packages/create-sitecore-jss/src/templates/nextjs-sxa/src/components/Image.tsx

Banner variant of image component has been fixed for metadata mode

[templates/nextjs-sxa]: Image component has been fixed for metadata mode

---

CHANGELOG.md
packages/sitecore-jss-nextjs/src/editing/constants.ts
packages/sitecore-jss-nextjs/src/editing/editing-render-middleware.test.ts
packages/sitecore-jss-nextjs/src/editing/editing-render-middleware.ts
packages/sitecore-jss-nextjs/src/editing/feaas-render-middleware.test.ts
packages/sitecore-jss-nextjs/src/editing/render-middleware.test.ts
packages/sitecore-jss-nextjs/src/editing/render-middleware.ts

Updates to Next.js editing integration to further support secure hosting scenarios (on XM Cloud & Vercel), including:
* Added header pass-through capability to the editing handler SSR request (_chromes_ edit mode). Headers which will be passed: `authorization`, `cookie`
* Removed experimental `x-sitecore-protection-bypass` query param propagation
* Added support for `x-vercel-set-bypass-cookie` query param propagation

[Next.js] [Editing Integration] Secure hosting updates

---

CHANGELOG.md
packages/sitecore-jss-react/src/components/Date.test.tsx
packages/sitecore-jss-react/src/enhancers/withEmptyFieldEditingComponent.test.tsx
packages/sitecore-jss/src/layout/index.ts
packages/sitecore-jss/src/layout/utils.test.ts
packages/sitecore-jss/src/layout/utils.ts

The default DateField value provided by Layout Service is date, we need to rely on it and on empty string value as well

[React][Next.js] DateField empty value is not treated as empty

---

CHANGELOG.md
packages/create-sitecore-jss/src/templates/nextjs-sxa/src/assets/sass/components/title/_component-title.scss

The problem is wrong styles in title component in metadata mode.
The styles of title component has been fixed.

 [template/nextjs-sxa]: fixed styles of title component for metadata #SXA-7409

---

CHANGELOG.md
packages/create-sitecore-jss/src/templates/angular/package.json

Follow up to Angular 17 upgrade.
Bug--> /graphql pages not working.
After reverting apollo-angular dependency everything works as expected.
Graphql dependencies will be updated with Angular 18 since some of them are not compatible with 17.

[template/angular] Fix `/graphql` page for all modes

---

CHANGELOG.md
packages/create-sitecore-jss/src/templates/angular/package.json

Follow up to Angular 17 upgrade.
Bug--> /graphql pages not working.
apollo-angular v6 works fine with angular 17.

[template/angular] Fix `/graphql`  page for all modes

---

CHANGELOG.md
packages/create-sitecore-jss/src/templates/nextjs-sxa/src/components/Title.tsx

There was error of missing value of field data in Title component.
Title component has been fixed.

 [templates/nextjs-sxa]: Title component has been fixed with missing value #SXA-7389

---

CHANGELOG.md
packages/sitecore-jss/src/editing/graphql-editing-service.ts

Updated GraphQL query to reduce complexity of GraphQLEditingService query

[sitecore-jss] [Editing] Updated dictionary query to reduce query complexity

---

CHANGELOG.md
packages/create-sitecore-jss/src/initializers/angular-sxp/index.ts
packages/create-sitecore-jss/src/initializers/angular-xmcloud/index.ts
packages/create-sitecore-jss/src/initializers/angular/index.ts
packages/create-sitecore-jss/src/initializers/angular/prompts.ts
packages/create-sitecore-jss/src/initializers/node-xmcloud-proxy/index.ts

Angular will have XMC-only logic. This PR makes preparations for the new create-sitecore-jss init journey for Angular.

[create-sitecore-jss] New initializer journey for Angular

---

CHANGELOG.md
packages/sitecore-jss-nextjs/src/editing/editing-render-middleware.test.ts
packages/sitecore-jss-nextjs/src/editing/editing-render-middleware.ts

Fix CORs issue for editMode when pointing Pages to a running localhost instance to use as the site editing host by modifying the cookies set by the setPreviewData from SameSite=Lax to SameSite=None

[sitecore-jss-nextjs] Fix edit mode for localhost

---

packages/create-sitecore-jss/src/templates/nextjs-xmcloud/src/pages/api/editing/render.ts

Updates the comment in api/editing/render endpoint for XMCloud apps with description of new Metadata editing mode flow. 
create-sitecore-jss helper cannot determine the addons being installed, so the comment was added as part of an override file in nextjs-xmcloud.

[templates/nextjs-xmcloud] Add xmcloud-specific comments in api/editing/render

---

CHANGELOG.md
docs/upgrades/unreleased.md
packages/create-sitecore-jss/src/templates/nextjs/package.json

Install sharp in nextjs apps by default. https://nextjs.org/docs/messages/sharp-missing-in-production
Having sharp installed is recommended by Vercel to avoid issues with image optimization:
Version is locked to 0.32.6 due to this potential issue: https://github.com/vercel/next.js/issues/59516#issuecomment-1941850968

[Chore][nextjs] Install sharp dependency for nextjs apps

---

packages/create-sitecore-jss/src/initializers/angular-xmcloud/index.ts

- Follow up to jss-3563 - Angular Initializer support
- Add transform logic to the add-on
- Scaffold of node-xmcloud-proxy app relatively to base angular app

[angular/xmcloud] Fix angular app initialization setup for xmc 

---

CHANGELOG.md
packages/sitecore-jss-angular/src/components/placeholder.component.spec.ts
packages/sitecore-jss-angular/src/components/placeholder.component.ts
packages/sitecore-jss-angular/src/services/jss-component-factory.service.ts
packages/sitecore-jss-angular/src/test-data/non-ee-data.ts
packages/sitecore-jss-react/src/components/Placeholder.test.tsx
packages/sitecore-jss-react/src/components/PlaceholderCommon.tsx
packages/sitecore-jss-react/src/components/PlaceholderMetadata.tsx
packages/sitecore-jss/src/layout/index.ts
packages/sitecore-jss/src/layout/utils.test.ts
packages/sitecore-jss/src/layout/utils.ts

Angular placeholder support of SXA component features including:
- dynamic placeholders
- rendering variants (via design pattern using Angular templates)
- convenience params (currently just 'styles' which matches our React SDK)

[sitecore-jss-angular] Angular placeholder support for SXA components

---

CHANGELOG.md
packages/create-sitecore-jss/src/templates/angular/scripts/generate-config.ts
packages/create-sitecore-jss/src/templates/angular/scripts/update-graphql-fragment-data.ts

The config generation messages had an incorrect order, since the generation was executed in parallel. 
Also the message was rendered 3 times when pulling the graphql introspection data

[Angular] Adjust config generation messages order

---

packages/create-sitecore-jss/src/initializers/angular-xmcloud/index.ts
packages/create-sitecore-jss/src/templates/angular-sxp/.env
packages/create-sitecore-jss/src/templates/angular/.env

- fetchWith prompt will only appear during angular-sxp intializer execution - but it's expected in base angular template. We prevent an error from happening by moving FETCH_WITH into sxp-only .env file
- proxyAppDestination from flags was ignored by prompt logic in angular-xmcloud initializer. This is fixed too.

[create-sitecore-jss] Only put FETCH_WITH for SXP template, pass proxyPath to prompt

---

CHANGELOG.md
packages/create-sitecore-jss/src/templates/angular-xmcloud/src/app/jss-link.service.ts
packages/create-sitecore-jss/src/templates/angular/src/app/app.module.ts

Fixes a build error of angular+angular-sxp app by removing the angular-xmcloud specific link service from app.module and providing it via provideIn='root'

[template/angular-sxp] Fix build error of angular-sxp, service not found

---

CHANGELOG.md
packages/sitecore-jss-nextjs/src/components/NextImage.test.tsx
packages/sitecore-jss-nextjs/src/components/NextImage.tsx

Disable nextjs image optimization on NextImage component for edit and preview modes. Ensures better stability when rendering SXA images.

[templates/nextjs-xmcloud] Disable image optimization for edit/preview

---

CHANGELOG.md
packages/create-sitecore-jss/src/templates/angular-xmcloud/src/app/components/column-splitter/column-splitter.component.html
packages/create-sitecore-jss/src/templates/angular-xmcloud/src/app/components/column-splitter/column-splitter.component.ts

Add `ColumnSplitterComponent` to angular xmcloud

[angular-xmcloud] Introduce column-splitter component for angular

---

CHANGELOG.md
packages/sitecore-jss-nextjs/src/middleware/redirects-middleware.ts

There was a problem with redirects when the parameter Shall query string be preserved upon redirect? wasn’t set, but the user was redirected with the query string parameters.

[sitecore-jss-nextjs] The redirects with query string has been fixed #SXA-7405

---

CHANGELOG.md
packages/create-sitecore-jss/src/templates/angular-xmcloud/src/app/components/partial-design-dynamic-placeholder/partial-design-dynamic-placeholder.component.html
packages/create-sitecore-jss/src/templates/angular-xmcloud/src/app/components/partial-design-dynamic-placeholder/partial-design-dynamic-placeholder.component.ts

Introduce angular SXA PartialDesignDynamicPlaceholder component

[template/angular-xmcloud] Introduce angular SXA PartialDesignDynamicPlaceholder component

---

CHANGELOG.md
packages/create-sitecore-jss/src/templates/angular-xmcloud/src/app/routing/layout/layout.component.html

Remove the hardcoded navigation module from sxa layout

[angular-xmcloud] Remove the hardcoded navigation module from sxa layout

---

CHANGELOG.md
packages/create-sitecore-jss/src/templates/nextjs/package.json
packages/sitecore-jss-nextjs/package.json
yarn.lock

Ensure the latest nextjs version - fixing some nextjs-specific bugs.

[templates/nextjs] Update nextjs to 14.2.7

---

CHANGELOG.md
packages/sitecore-jss-nextjs/src/middleware/redirects-middleware.test.ts
packages/sitecore-jss-nextjs/src/middleware/redirects-middleware.ts

The issue was caused by **the x-middleware-next** header in Next.js, which prevented the flow from being interrupted properly.
As a result, **redirects** did not function correctly in certain cases.
This fix ensures that the flow is correctly interrupted, allowing redirects to work as expected.

 [sitecore-jss-nextjs] fix for Redirects related to x-middleware-next Header #SXA-6564

---

CHANGELOG.md
packages/create-sitecore-jss/src/templates/nextjs-xmcloud/src/lib/page-props-factory/plugins/component-themes.ts
packages/create-sitecore-jss/src/templates/nextjs/src/lib/page-props-factory/plugins/component-props.ts

BYOC / FEAAS components are not rendered on the page when A/B testing is applied
This is happening due to the wrong order of _componentThemes_, _componentProps_ plugins. They should be executed after the personalizePlugin, since the personalizePlugin updates layout data and sets the proper variant, while themes/props plugins were executed using non-personalized data

[Next.js] FEAAS / BYOC Components are not visible on the page with running A/B test

---

CHANGELOG.md
packages/sitecore-jss-react/src/components/EditingScripts.test.tsx
packages/sitecore-jss-react/src/components/EditingScripts.tsx
packages/sitecore-jss/src/editing/index.ts
packages/sitecore-jss/src/editing/utils.test.ts
packages/sitecore-jss/src/editing/utils.ts

isEditorActive() call would return false for when called from XMCloud Pages. This has been fixed.

[sitecore-jss] fix isEditorActive for XMCloud Pages

---

CHANGELOG.md
packages/sitecore-jss-nextjs/src/middleware/redirects-middleware.test.ts
packages/sitecore-jss-nextjs/src/middleware/redirects-middleware.ts

The core issue was that Next.js was setting the **x-middleware-rewrite** header during the **NextResponse.redirect** process. This caused the redirect to fail during execution on Netlify service, as the header interfered with its proper functioning.

[sitecore-jss-nextjs]: removing header x-middleware-rewrite for redirects #SXA-6564

---

CHANGELOG.md
packages/sitecore-jss-angular/src/components/base-field.directive.spec.ts
packages/sitecore-jss-angular/src/components/base-field.directive.ts
packages/sitecore-jss-angular/src/components/date.directive.spec.ts
packages/sitecore-jss-angular/src/components/date.directive.ts
packages/sitecore-jss-angular/src/components/default-empty-field-editing-image.component.ts
packages/sitecore-jss-angular/src/components/default-empty-field-editing.component.ts
packages/sitecore-jss-angular/src/components/default-empty-image-field-editing-placeholder.component.ts
packages/sitecore-jss-angular/src/components/default-empty-text-field-editing-placeholder.component.ts
packages/sitecore-jss-angular/src/components/generic-link.directive.spec.ts
packages/sitecore-jss-angular/src/components/generic-link.directive.ts
packages/sitecore-jss-angular/src/components/image.directive.spec.ts
packages/sitecore-jss-angular/src/components/image.directive.ts
packages/sitecore-jss-angular/src/components/link.directive.spec.ts
packages/sitecore-jss-angular/src/components/link.directive.ts
packages/sitecore-jss-angular/src/components/rendering-field.ts
packages/sitecore-jss-angular/src/components/rich-text.directive.spec.ts
packages/sitecore-jss-angular/src/components/rich-text.directive.ts
packages/sitecore-jss-angular/src/components/router-link.directive.spec.ts
packages/sitecore-jss-angular/src/components/router-link.directive.ts
packages/sitecore-jss-angular/src/components/text.directive.spec.ts
packages/sitecore-jss-angular/src/components/text.directive.ts
packages/sitecore-jss-angular/src/test-data/test-base.directive.ts
packages/sitecore-jss/src/layout/models.ts
packages/sitecore-jss/src/layout/utils.test.ts
packages/sitecore-jss/src/layout/utils.ts

This PR enhances the rendering of fields in editing mode for editMode metadata. When a field value is empty, a placeholder content should be rendered to signify that the field has no value. The placeholder should be interactable, so user can add value to the field. Additionally developers can provide their own custom empty field template via the field directive's emptyFieldEditingTemplate imput property, which will be rendered instead of the default one.
The fields with this functionality are:
- [sitecore-jss-angular] image.directive.ts
- [sitecore-jss-angular] date.directive.ts
- [sitecore-jss-angular] rich-text.directive.ts
- [sitecore-jss-angular] text.directive.ts
- [sitecore-jss-angular] link.directive.ts
- [sitecore-jss-angular] router-link.directive.ts
- [sitecore-jss-angular] …

[sitecore-jss] [sitecore-jss-angular] Default Placeholder Content for empty fields in editMode metadata

---

packages/create-sitecore-jss/src/templates/angular-xmcloud/.env
packages/create-sitecore-jss/src/templates/node-xmcloud-proxy/.env
packages/create-sitecore-jss/src/templates/node-xmcloud-proxy/README.md
packages/create-sitecore-jss/src/templates/node-xmcloud-proxy/src/config.ts

Updated default PORT number to 3000, to be aligned with the rest of "node" based proxies.
It allows us to prevent an additional configuration in XM Cloud

[node-xmcloud-proxy] Set default PORT number to 3000

---

CHANGELOG.md
docs/upgrades/unreleased.md
packages/sitecore-jss/src/constants.ts

Set FETCH_WITH.REST to 'REST' instead of 'Rest' to match the value we mention in our docs

[sitecore-jss] Set FETCH_WITH.REST to 'REST' instead of 'Rest'

---

CHANGELOG.md
docs/upgrades/unreleased.md
packages/create-sitecore-jss/src/templates/angular/src/app/app.module.ts
packages/create-sitecore-jss/src/templates/angular/src/app/i18n/jss-translation-client-loader.service.ts

When SSR is executed, the data is pre-fetched and populated by Node.js server. However the DictionaryService API call is still executed in a browser on initial page load. We now transfer the pre-fetched SSR data to the client, preventing unnecessary client-side API calls and improving app's performance.

[template/angular] Prevent client-side dictionary API call when SSR data is available

---

CHANGELOG.md
packages/sitecore-jss-angular/package.json
packages/sitecore-jss-angular/src/components/base-field.directive.spec.ts
packages/sitecore-jss-angular/src/components/base-field.directive.ts
packages/sitecore-jss-angular/src/components/date.directive.spec.ts
packages/sitecore-jss-angular/src/components/date.directive.ts
packages/sitecore-jss-angular/src/components/field-metadata-marker.component.spec.ts
packages/sitecore-jss-angular/src/components/field-metadata-marker.component.ts
packages/sitecore-jss-angular/src/components/image.directive.spec.ts
packages/sitecore-jss-angular/src/components/image.directive.ts
packages/sitecore-jss-angular/src/components/link.directive.spec.ts
packages/sitecore-jss-angular/src/components/link.directive.ts
packages/sitecore-jss-angular/src/components/placeholder.component.ts
packages/sitecore-jss-angular/src/components/rich-text.directive.spec.ts
packages/sitecore-jss-angular/src/components/rich-text.directive.ts
packages/sitecore-jss-angular/src/components/text.directive.spec.ts
packages/sitecore-jss-angular/src/components/text.directive.ts
packages/sitecore-jss-angular/src/test-data/test-base.directive.ts
packages/sitecore-jss-react/src/components/FieldMetadata.tsx
packages/sitecore-jss-react/src/components/PlaceholderMetadata.tsx
packages/sitecore-jss/src/editing/index.ts
packages/sitecore-jss/src/editing/models.ts
yarn.lock

This PR enables editing support for the fields in editing mode for editMode metadata. When a field is rendered in `metadata` mode it will be surrounded with open and close `code` elements with metadata content. This elements indicate location of the field and provide required metadata to enable editing in editor applications like Pages.
The fields with this functionality are:
[sitecore-jss-angular] image.directive.ts
[sitecore-jss-angular] date.directive.ts
[sitecore-jss-angular] rich-text.directive.ts
[sitecore-jss-angular] text.directive.ts
[sitecore-jss-angular] link.directive.ts
[sitecore-jss-angular] router-link.directive.ts
[sitecore-jss-angular] generic-link.directive.spec.ts

[sitecore-jss] [sitecore-jss-angular] Field metadata chromes in editMode metadata

---

docs/upgrades/unreleased.md
packages/create-sitecore-jss/src/templates/angular/src/app/app.module.ts
packages/create-sitecore-jss/src/templates/angular/src/app/app.server.module.ts
packages/create-sitecore-jss/src/templates/angular/src/app/i18n/jss-translation-client-loader.service.ts
packages/create-sitecore-jss/src/templates/angular/src/app/i18n/jss-translation-server-loader.service.ts
packages/sitecore-jss-angular/src/public_api.ts

Follow up to: https://github.com/Sitecore/jss/pull/1930

[template/angular] [follow-up] Prevent client-side dictionary API call when SSR data is available

---

CHANGELOG.md
packages/sitecore-jss-angular/src/components/default-empty-image-field-editing-placeholder.component.ts

This PR fixes the issue when Image component is selected Edit frame is expanded to all the area

[sitecore-jss-angular] Fix default empty image styles

---

CHANGELOG.md
packages/sitecore-jss-nextjs/src/middleware/redirects-middleware.test.ts
packages/sitecore-jss-nextjs/src/middleware/redirects-middleware.ts
packages/sitecore-jss/src/utils/index.ts
packages/sitecore-jss/src/utils/utils.test.ts
packages/sitecore-jss/src/utils/utils.ts

This PR includes a fix for an issue with Netlify, where URL parameters are being sorted by alphabet.
This causes redirects with two or more query parameters to not match the expected patterns. 
To resolve this, a new method has been added that generates all possible permutations of the query parameters based on their arrangement. This ensures that the redirect logic can correctly handle unordered query strings, allowing for proper matching with URL patterns, regardless of how parameters are ordered in the incoming requests.

 [sitecore-jss-nextjs]: Redirects with double and more parameters has been fixed for netlify #SXA-7554

---

CHANGELOG.md
packages/sitecore-jss-angular/src/components/image.directive.spec.ts
packages/sitecore-jss-angular/src/components/image.directive.ts

If image field has a style property, its value is an object and that's why it is not rendered properly. This PR addresses this issue

[sitecore-jss-angular] Fix style attribute from field not rendered properly in image field

---

CHANGELOG.md
packages/sitecore-jss-nextjs/src/middleware/index.ts

…Config for project reusability
Expose MiddlewareBase class so it can be used by developers as a starting point for new middleware plugins in projects.

[sitecore-jss-nextjs]: Expose MiddlewareBase class and MiddlewareBaseConfig type

---

CHANGELOG.md
packages/sitecore-jss-angular/src/components/editing-scripts.component.spec.ts
packages/sitecore-jss-angular/src/components/editing-scripts.component.ts

This PR fixes issue where editing scripts are rendered twice (for server and client) in pages edit mode metadata - by rendering the scripts only on the server.

[sitecore-jss-angular] Fix Editing Scripts component rendered twice in pages 

---

CHANGELOG.md
packages/create-sitecore-jss/src/templates/angular-xmcloud/package.json
packages/create-sitecore-jss/src/templates/angular-xmcloud/src/app/routing/scripts/cloud-sdk-init.component.ts
packages/create-sitecore-jss/src/templates/angular-xmcloud/src/app/routing/scripts/scripts.component.html
packages/create-sitecore-jss/src/templates/angular-xmcloud/src/app/routing/scripts/scripts.module.ts
packages/create-sitecore-jss/src/templates/nextjs-xmcloud/package.json

- Initializes CloudSDK on browser for Angular app
- Allows for other parts of app to use events etc
Note: adding events init TBD

[angular][xmcloud] Init CloudSDK on browser

---

CHANGELOG.md
packages/sitecore-jss-nextjs/src/components/Link.test.tsx
packages/sitecore-jss-nextjs/src/components/Link.tsx

We need to render regular React link instead of Next.js link component when relative URL has a file extension

[sitecore-jss-nextjs] Link component prefetches files

---

CHANGELOG.md
packages/create-sitecore-jss/src/templates/angular-xmcloud/src/app/components/image/image.component.html
packages/create-sitecore-jss/src/templates/angular-xmcloud/src/app/components/link-list/link-list.component.html
packages/create-sitecore-jss/src/templates/angular-xmcloud/src/app/components/navigation/navigation-item.component.html
packages/create-sitecore-jss/src/templates/angular-xmcloud/src/app/components/promo/promo.component.html
packages/create-sitecore-jss/src/templates/angular-xmcloud/src/app/components/title/title.component.html

In order to perform the client side routing without the full page refresh we need to use "scRouterLink" in Navigation component instead of regular "scLink"

[XM Cloud][Angular] Navigation component link forces full page reload

---

CHANGELOG.md
docs/upgrades/unreleased.md
packages/create-sitecore-jss/src/templates/angular-xmcloud/src/app/routing/scripts/cloud-sdk-init.component.ts

This PR modifies cloudsk init component to not initialize CloudSDK in the browser if we are in edit or preview mode or route data is missing.

[angular][xmcloud] Do not initialize CloudSDK if we are in edit or preview mode

---

CHANGELOG.md
docs/upgrades/22.x/22.2.md
packages/create-sitecore-jss/src/templates/nextjs-xmcloud/src/lib/middleware/plugins/personalize.ts
packages/sitecore-jss-nextjs/src/middleware/personalize-middleware.ts

This PR adds a new property `enablePersonalizeCookie` to PersonalizeMiddlewareConfig and pass it to CloudSDK.addPersonalize() function, which is required to enable A/B testing and personalization; update personalize plugin to set it to `true` by default.

[nextjs][xmcloud]  Introduce property `enablePersonalizeCookie` to PersonalizeMiddlewareConfig
