Sitecore/jss

- samples/advanced-sample-react/assets/css/app.css
> Closing #7

- samples/basic-sample-react/src/app/components/Welcome.js
> Use the RichText helper for the basic app

- CONTRIBUTING.md
- README.md
- packages/sitecore-jss-angular-schematics/package.json
> testing ci tooling

- samples/react/public/index.html
- samples/react/server/server.js
- samples/react/src/index.js
- samples/vue/public/index.html
- samples/vue/server/server.js
- samples/vue/src/main.js
* Fixes #76
* Allows for use of CSP without unsafe-inline
* Faster parse times for the SSR data
* Better safety by not allowing injection of JS functions, etc into the page only data
* This is an optional enhancement to the sample apps, and no library changes were needed
* Both old and new styles of SSR will continue to work fine
e2e tests have passed in integrated and disconnected modes, visually inspected and checked for JS errors
> Modify SSR handling in React and Vue

- samples/react/server/server.js
- samples/vue/server/server.js
This results in 3x faster serialization time!
Thanks to https://github.com/Sitecore/jss/pull/95#issuecomment-446898713 @jantimon for the suggestion
Passed integrated mode e2e
> Flag the SSR state as JSON

- docs/data/routes/docs/techniques/ssr/headless-mode-ssr/en.md
See [this SSE answer](https://sitecore.stackexchange.com/a/15531/267) - missing a step in the docs.
This was also a test of #107's link ;)
> Updates headless directions

- samples/sitecore-embedded-jss-app/package.json
> patch embedded react version

- packages/sitecore-jss-proxy/src/index.ts
- samples/angular/server.bundle.ts
- samples/node-headless-ssr-proxy/README.md
- samples/node-headless-ssr-proxy/config.js
- samples/react/server/server.js
- samples/vue/server/server.js
> Fixed version of #128

- docs/data/routes/docs/techniques/azure-deployment/en.md
> Update documentation for Azure deployment

- docs/data/routes/features/why-sitecore/en.md
Tiny fix of typo in page copy.
> Tiny typo fix

- docs/data/routes/docs/client-frameworks/react/react-placeholders/en.md
Documentation update for the React Placeholder Techniques page. Changed placeholder prop from "route" to "rendering".
> Adjusted React placeholder rendering prop name.

- packages/sitecore-jss-angular/src/components/placeholder.component.ts
While implementing lazy loading with Sitecore JSS we ran into the issue that there was no way to know when a placeholder was done loading its children. In order to solve this issue we implemented the following solution. 
This change adds a `loaded` event to the placeholder component. This is emitted once all its child components are loaded.
Our usecase for this was related to analytics. We allow modules to register analytics enhancers which can augment the default analytics data. The basic analytics implementation was based on router events, the problem we ran into when implementing lazy loaded modules was that the router event fired before the lazy module was loaded. 
Because of this, on page load, the event was completed before the lazily loaded enhancer was registered. We use this …
> Placeholder loaded event

- docs/data/routes/docs/client-frameworks/react/sample-app/en.md
Fix the import statement
Current documentation contains an outdated import statement
Fix documentation
Tested in Sitecore JSS project in progress
> Import correct npm package

- docs/data/routes/docs/techniques/azure-deployment/en.md
Documentation update. 
Updated documentation will help to deploy fully functional environment to the Azure.
> Update deployment guide with security permission step.

- docs/data/routes/connected-demo/getting-started/connecting/en.md
Fixed a sentence syntax typo and added a word to another sentence.
Helps with readability.
I proofread my changes :)
- [ x ] Documentation change
- [ x ] I have read the Contributing guide.
- [ x ] My code follows the code style of this project.
> Fix sentences syntax

- docs/data/routes/docs/getting-started/jss-server-install/en.md
Just added a tool that can be used to observe the message
Added text
New mark down viewed in VS code
> Added a method for seeing http error message

- samples/react/data/routes/en.yml
> Fixing small typo in react sample project.

- packages/sitecore-jss-react/src/index.ts
See https://github.com/Sitecore/jss/issues/224
> Export SitecoreContextReactContext

- packages/sitecore-jss-manifest/src/generator/pipelines/generateManifest/expandReferencedContent.ts
> #61 Nested component definitions via Item Link returns only IDs

- docs/data/routes/release-notes/en.md
> Add 11.1 Notes and Compatibility Matrix to release notes

- packages/sitecore-jss-react/src/components/Date.tsx
- packages/sitecore-jss-react/src/components/File.tsx
- packages/sitecore-jss-react/src/components/Image.tsx
- packages/sitecore-jss-react/src/components/Link.tsx
- packages/sitecore-jss-react/src/components/Placeholder.tsx
- packages/sitecore-jss-react/src/components/PlaceholderCommon.tsx
- packages/sitecore-jss-react/src/components/RichText.tsx
- packages/sitecore-jss-react/src/components/Text.tsx
- packages/sitecore-jss-react/src/enhancers/withPlaceholder.tsx
> remove InferProps

- docs/data/routes/docs/techniques/authentication/sitecore-auth/en.md
Corrected a misspelling in the first paragraph, second sentence.
> Corrected misspelling

- docs/data/routes/docs/fundamentals/application-modes/en.md
One line had ``... and and...``.
The second was removed.
> Double 'and' removed

- docs/data/routes/docs/fundamentals/services/layout-service/en.md
Updated the documentation to resolve issues mentioned in #212   and #253 
The documentation was incomplete. I have updated so that other users wont hit the same issue. 
I tested my updates by following the steps I added to the docs on a Vanilla install of JSS and my own headless application.
Running Node.js v 12.13.1 on Windows 10.
> Update en.md with fixes for #212 and #253

- samples/angular/src/polyfills.ts
> Fix - Angular scaffolding has error in polyfill.ts

- packages/sitecore-jss-cli/src/scripts/deploy.files.ts
> #336 CLI deploy options do not trigger build step (Vue sample app)

- packages/sitecore-jss-angular/ngcc.config.js
Added ngcc.config.js that should give possibility to use angular ngcc command without errors
Fix for issue #348 
Smokey test passed successfully
> #348 Added ngcc.config.js to sitecore-jss-angular package.

- samples/node-headless-ssr-proxy/README.md
Fixed a broken link on the node-headless-ssr-proxy sample docs
This has been tested by previewing the read.md
> [node-headless-ssr-proxy sample] - Fix broken Headless SSR mode link

- docs/data/routes/docs/getting-started/jss-server-install/en.md
* Fixes minor formatting issue on XML code snippet within [JSS Server Setup documentation](https://jss.sitecore.com/docs/getting-started/jss-server-install#server-components-installation) (see step 4):
* Corrects capitisation of 7-Zip.
* Highlights `Web.config` with code formatting.
Improves documentation quality.
Tested locally; visually validated change worked as expected.
> [Doc] Minor formatting fix in JSS Server Setup documentation

- docs/README.md
> Fixing link to Migrating to JSS page

- packages/sitecore-jss-react/src/components/SitecoreContext.tsx
- samples/react/server/server.js
- samples/react/src/AppRoot.js
- samples/react/src/RouteHandler.js
- samples/react/src/index.js
…r HTML from a different route
> [JSS 15][React sample] Race condition, under load React app may render HTML from a different route

- docs/data/routes/help/en.md
Update Sitecore's support policy for JSS on the /help page
Tested on local environment
> [Docs] Update support policy description on help page

- packages/sitecore-jss-angular/ngcc.config.js
[sitecore-jss-angular] ngcc config not correctly implemented
> [sitecore-jss-angular] ngcc config not correctly implemented

- docs/data/routes/docs/techniques/ssr/headless-mode-ssr/en.md
- samples/node-headless-ssr-proxy/config.js
- samples/node-headless-ssr-proxy/package.json
Remove use of onProxyReq event in sample proxy options
> [node-headless-proxy] Remove use of onProxyReq event in sample proxy options

- packages/sitecore-jss-proxy/package-lock.json
- samples/node-headless-ssr-proxy/package-lock.json
- samples/node-headless-ssr-proxy/package.json
> [node-headless-proxy] Upgrade lodash, node-fetch libraries

- docs/data/routes/docs/techniques/content-translation/en.md
[Doc] Documentation for Content Translation has unfinished sentence
Related to #445
> [Doc] Documentation for Content Translation has unfinished sentence

- packages/sitecore-jss-angular/ngcc.config.js
> [sitecore-jss-angular] Fix ngcc.config.js incorrect structure

- packages/sitecore-jss-manifest/src/generator/pipelines/generateMedia/utils.ts
> [sitecore-jss-manifest] Process media field with single item recursively

- packages/sitecore-jss-angular/src/components/image.directive.spec.ts
- packages/sitecore-jss/src/mediaApi.ts
[sitecore-jss][mediaApi] Prevent editing of original query/params
> [sitecore-jss][mediaApi] Prevent editing of original query/params

- docs/data/routes/docs/getting-started/jss-server-install/en.md
> [Doc] Update for JSS Server 15.0.1

- docs/data/routes/guides/performance/en.md
- [X Documentation update (non-breaking change; modified files are limited to the `/docs` directory)
> fix typo guide performance

- samples/nextjs/src/components/GraphQL-ConnectedDemo/index.tsx
- samples/nextjs/src/components/NotFound.tsx
- samples/nextjs/src/pages/404.tsx
- samples/nextjs/src/pages/[[...path]].tsx
- samples/nextjs/src/pages/_error.tsx
- samples/nextjs/src/pages_examples/[[...path]].SSR.tsx
> [NextJS] Render unhandled errors and 404

- packages/sitecore-jss-react-native/package-lock.json
- packages/sitecore-jss-react-native/package.json
- samples/react-native/package-lock.json
- samples/react-native/package.json
> [sitecore-jss-react-native][react-native sample] Fix peer dependencies

- docs/data/routes/release-notes/en.md
- package.json
- packages/sitecore-jss-react/src/enhancers/withSitecoreContext.test.tsx
- packages/sitecore-jss-react/src/enhancers/withSitecoreContext.tsx
- packages/sitecore-jss-react/src/index.ts
> [sitecore-jss-react] add useSitecoreContext hook

- packages/sitecore-jss-nextjs/src/components/RichText.tsx
> [sitecore-jss-nextjs] RichText, detect locale from url instead of using current

- docs/data/routes/docs/fundamentals/services/view-engine/en.md
> fixes typos and grammar

- packages/sitecore-jss-react/src/components/SitecoreContext.tsx
- packages/sitecore-jss-react/src/enhancers/withSitecoreContext.tsx
- samples/nextjs/src/components/GraphQL-Layout/index.tsx
- samples/nextjs/src/components/Styleguide-CustomRouteType/index.tsx
- samples/nextjs/src/components/Styleguide-Layout-Tabs-Tab/index.tsx
- samples/nextjs/src/components/Styleguide-Multilingual/index.tsx
- samples/nextjs/src/components/Styleguide-RouteFields/index.tsx
- samples/nextjs/src/components/Styleguide-SitecoreContext/index.tsx
- samples/nextjs/src/lib/component-props.ts
- samples/nextjs/src/pages/[[...path]].tsx
- samples/nextjs/src/pages/_edit.tsx
- samples/nextjs/src/pages_examples/[[...path]].SSR.tsx
Switch sample app from using withSitecoreContext HOC to useSitecoreContext hook
> [NextJS] Switch sample app from using withSitecoreContext HOC to useSitecoreContext hook

- docs/data/routes/docs/client-frameworks/nextjs/nextjs-static-export/en.md
- docs/src/app/sidenav.js
Maintaining static html export capability is becoming increasingly complicated with new releases of Next.js. In version 10, for example, both i18n and image optimization are not compatible with next export.
We should define documentation to help customer enable next export
> [NextJS] Document Next.js Static HTML Export

- packages/sitecore-jss-nextjs/src/middleware/editing-render-middleware.test.ts
- packages/sitecore-jss-nextjs/src/middleware/editing-render-middleware.ts
Fix error when insert new rendering into placeholder. Now user will see correct renderings and can add it without reload of page and without error.
> [NextJS] [EE] Adding a new rendering to a placeholder results into an error

- docs/data/routes/docs/techniques/azure-deployment/en.md
Update to the Azure deployment guide.
Documentation update should solve issue described in the following issue https://github.com/Sitecore/jss/issues/152
> #454503 Update deployment guide

- samples/nextjs/scripts/scaffold-component.ts
Completed work during QA by Design for `[JSS] [Nextjs] Refactor styleguide component structure`
> [NextJS] Generate definition files using .sitecore.ts instead of .tsx

- docs/data/routes/docs/client-frameworks/nextjs/nextjs-static-export/en.md
- docs/data/routes/docs/techniques/forms/en.md
Sitecore Forms with JSS currently do not support Sitecore Robot Detection. Mention it in JSS docs
> [Doc] Specify explicitly that JSS-Forms does not support Sitecore Robot detection

- samples/nextjs/src/components/graphql/GraphQL-ConnectedDemo.tsx
- samples/nextjs/src/components/graphql/GraphQL-IntegratedDemo.tsx
> [Next.js] Fix inaccurate content on GraphQL demo components

- samples/nextjs/package.json
- samples/nextjs/src/lib/sitemap-fetcher.ts
> [NextJS] Remove jss manifest from bootstrap

- packages/sitecore-jss/package-lock.json
- packages/sitecore-jss/package.json
- packages/sitecore-jss/src/dictionary-service.test.ts
- packages/sitecore-jss/src/dictionary-service.ts
If we use `node-cache`, Angular sample app throws error during `jss deploy app`:
`
ERROR in node_modules/@sitecore-jss/sitecore-jss-angular/node_modules/@sitecore-jss/sitecore-jss/types/dictionary-service.d.ts:1:8 - error TS1259: Module '"C:/repos/dev2/jss/samples/angular/node_modules/@sitecore-jss/sitecore-jss-angular/node_modules/@sitecore-jss/sitecore-jss/node_modules/node-cache/index"' can only be default-imported using the 'allowSyntheticDefaultImports' flag
`
Seems like something related to `node-cache` library, using `memory-cache` it's working as expected.
> [sitecore-jss] Use memory-cache instead of node-cache

- docs/data/routes/docs/nextjs/data-fetching/data-services/en.md
Doc for section: Data services used by Next.js with JSS
> [Doc] [NextJS] Data services used by Next.js with JSS

- docs/data/routes/docs/nextjs/getting-started/options/en.md
> [Doc] [NextJS] Add documentation for getting-started/options

- docs/data/routes/docs/nextjs/deploying-to-production/export/en.md
> [Doc] [NextJS] Revise documentation for deploying-to-production/export

- docs/data/routes/docs/nextjs/getting-started/walkthrough-jsscreate/en.md
> [Doc] [NextJS] Add procedures for getting-started/walkthrough-jsscreate

- docs/data/routes/docs/nextjs/data-fetching/getStaticPaths/en.md
[Doc] [NextJS] getStaticPaths and the Sitemap Service
> [Doc] [NextJS] getStaticPaths and the Sitemap Service

- docs/data/routes/docs/nextjs/introduction/why-nextjs/en.md
> [Doc] [NextJS] Add documentation for introduction/why-nextjs

- docs/data/routes/docs/nextjs/creating-components/new-component/en.md
- docs/src/app/components/Navigation/nextjs.js
> [Doc][NextJS] Document creation of new component

- docs/data/routes/release-notes/en.md
- docs/data/routes/upgrade-guides/16.0/en.md
Release notes and migration guide for JSS 16
> [Doc] Release notes, migration guide

- docs/data/routes/docs/nextjs/migration/en.md
- docs/src/app/components/Navigation/nextjs.js
Starting point for a migration guide. This adds a section for component structure
> [Docs] Migration guide - component structure section

- docs/data/routes/docs/nextjs/getting-started-nextjs/walkthrough-jsscreate/en.md
- docs/src/app/components/Footer.js
> [Doc]Fix links, footer anchors

- docs/data/routes/docs/nextjs/getting-started-nextjs/walkthrough-dotnetnew/en.md
- docs/data/routes/docs/techniques/authentication/sitecore-auth/en.md
- docs/data/routes/docs/techniques/ssr/headless-mode-ssr/en.md
- docs/data/routes/docs/temp/node-certificates/en.md
**Note** the location is TBD (ignore "temp" placement for now).
> [Doc] [NextJs] Node extra CA certificates configuration

- packages/sitecore-jss-nextjs/src/index.ts
- packages/sitecore-jss/src/index.ts
- packages/sitecore-jss/src/layout-service.test.ts
- packages/sitecore-jss/src/layout-service.ts
Provide ability to fetch Layout data from GraphQL Edge Schema
> [sitecore-jss] Add GraphQLLayoutService

- docs/data/routes/docs/introduction/headless-concepts/en.md
> [Docs]Fix typo

- docs/data/routes/docs/client-frameworks/vue/sample-app/en.md
> [Docs]Fix heading display

- e2e/cypress/package-lock.json
- package-lock.json
- package.json
- packages/sitecore-jss-angular/package-lock.json
- packages/sitecore-jss-forms/package-lock.json
- packages/sitecore-jss-manifest/package-lock.json
- packages/sitecore-jss-nextjs/package-lock.json
- packages/sitecore-jss-rendering-host/package-lock.json
- packages/sitecore-jss-vue/package-lock.json
- samples/nextjs/package-lock.json
- samples/nextjs/package.json
- samples/react/package-lock.json
- samples/sitecore-embedded-jss-app/package-lock.json
- samples/sitecore-javascript-renderings/package-lock.json
- samples/vue/package-lock.json
Updates to all packages, samples, e2e per GitHub Dependabot alerts and manual `npm audit` results. All except the Angular sample app (to be addressed in separate PR) now have either 0 or low severity (w/ blocking/breaking updates) vulnerabilities remaining.
> NPM package security audit & updates

- docs/data/routes/docs/fundamentals/troubleshooting/debug-logging/en.md
- docs/data/routes/docs/nextjs/troubleshooting/en.md
- docs/data/routes/release-notes/en.md
- docs/src/app/components/Navigation/docs.js
- packages/sitecore-jss-nextjs/package-lock.json
- packages/sitecore-jss-nextjs/package.json
- packages/sitecore-jss-nextjs/src/debug.ts
- packages/sitecore-jss-nextjs/src/middleware/editing-render-middleware.ts
- packages/sitecore-jss-nextjs/src/services/editing-data-service.ts
- packages/sitecore-jss-nextjs/src/services/graphql-sitemap-service.ts
- packages/sitecore-jss/package-lock.json
- packages/sitecore-jss/package.json
- packages/sitecore-jss/src/axios-fetcher.test.ts
- packages/sitecore-jss/src/axios-fetcher.ts
- packages/sitecore-jss/src/debug.ts
- packages/sitecore-jss/src/graphql-request-client.test.ts
- packages/sitecore-jss/src/graphql-request-client.ts
- packages/sitecore-jss/src/i18n/graphql-dictionary-service.ts
- packages/sitecore-jss/src/i18n/rest-dictionary-service.ts
- packages/sitecore-jss/src/index.ts
- packages/sitecore-jss/src/layout-service.ts
- samples/nextjs/.env
- samples/nextjs/src/components/graphql/GraphQL-ConnectedDemo.tsx
Debug logging for SDKs (focused on Next.js) using the [debug](https://www.npmjs.com/package/debug) module.
> [JSS] [NextJs] Debug Logging

- docs/data/routes/docs/client-frameworks/getting-started/quick-start/en.md
- docs/data/routes/docs/en.md
- docs/data/routes/docs/fundamentals/cli/en.md
- docs/data/routes/docs/nextjs/getting-started-nextjs/walkthrough-dotnetnew/en.md
- docs/data/routes/docs/nextjs/getting-started-nextjs/walkthrough-jsscreate/en.md
> [Docs][469075] Add notes on compatibility & CLI example for older JSS releases

- docs/data/routes/docs/introduction/why-jss/en.md
choose vs. chose
It's a text change to the docs.
I'm a grammar aficionado.
It's a text change to the docs.
> Update en.md "choose" vs. "chose"

- docs/data/routes/docs/nextjs/deploying-to-production/export/en.md
I removed this step, because in `disconnected-mode-proxy.ts` script we are using `language` to run `disconnected-proxy` server, so it's required.
https://github.com/Sitecore/jss/blob/dev/samples/nextjs/scripts/disconnected-mode-proxy.ts#L25
> [Doc] Remove `remove language from package.json` step in `Walkthrough: Using next export`

- samples/angular/src/app/components/styleguide-angular-lazy-loading/styleguide-angular-lazy-loading.component.html
Lazy Loading component script name contains hash in production mode instead of default filename. We should mention it in description
> [Angular] Extend description for Lazy Loading component

- docs/package-lock.json
- package-lock.json
- packages/sitecore-jss-angular/package-lock.json
- packages/sitecore-jss-forms/package-lock.json
- packages/sitecore-jss-manifest/package-lock.json
- packages/sitecore-jss-nextjs/package-lock.json
- packages/sitecore-jss-proxy/package-lock.json
- packages/sitecore-jss-react-forms/package-lock.json
- packages/sitecore-jss-react-native/package-lock.json
- packages/sitecore-jss-rendering-host/package-lock.json
- packages/sitecore-jss-tracking/package-lock.json
- packages/sitecore-jss-update-package/package-lock.json
- packages/sitecore-jss/package-lock.json
- packages/sitecore-pipelines/package-lock.json
- samples/angular/package-lock.json
- samples/nextjs/package-lock.json
- samples/node-headless-ssr-proxy/package-lock.json
- samples/react-native/package-lock.json
- samples/react/package-lock.json
- samples/sitecore-embedded-jss-app/package-lock.json
- samples/sitecore-javascript-renderings/package-lock.json
- samples/vue/package-lock.json
> Dependency upgrades - High severity vulnerabilities

- samples/node-headless-ssr-experience-edge/README.md
> [node-headless-ssr-experience-edge] Update readme

- docs/package-lock.json
- e2e/cypress/package-lock.json
- package-lock.json
- packages/sitecore-jss-angular/package-lock.json
- packages/sitecore-jss-angular/package.json
- packages/sitecore-jss-cli/package-lock.json
- packages/sitecore-jss-dev-tools/package-lock.json
- packages/sitecore-jss-forms/package-lock.json
- packages/sitecore-jss-manifest/package-lock.json
- packages/sitecore-jss-nextjs/package-lock.json
- packages/sitecore-jss-proxy/package-lock.json
- packages/sitecore-jss-react-forms/package-lock.json
- packages/sitecore-jss-react/package-lock.json
- packages/sitecore-jss-rendering-host/package-lock.json
- packages/sitecore-jss-tracking/package-lock.json
- packages/sitecore-jss-update-package/package-lock.json
- packages/sitecore-jss-vue/package-lock.json
- packages/sitecore-jss/package-lock.json
- packages/sitecore-pipelines/package-lock.json
- samples/vue/package-lock.json
Updated packages with security vulnerabilities
> [JSS] Address high severity vulnerabilities

- samples/nextjs/sitecore/config/JssNextWeb.config
Add language fallback settings to nextjs sample config
> Add language fallback settings to nextjs sample config

- packages/sitecore-jss/src/i18n/graphql-dictionary-service.ts
Quick fix, required by Delivery Edge. "Key" and "Phrase" should be capitalized instead of lowercase
> [sitecore-jss] [graphql-dictionary-service] use "Key" and "Phrase" capitalized

- packages/sitecore-jss/package-lock.json
- packages/sitecore-jss/package.json
- packages/sitecore-jss/src/graphql-request-client.ts
Timeout for GraphQL request client by AbortController.
> abort controller

- docs/data/routes/docs/nextjs/getting-started-nextjs/walkthrough-dotnetnew/en.md
This may trip someone using a new Windows environment.
> Remind to open the Execution Policy

- docs/data/routes/docs/introduction/headless-concepts/en.md
Sentence is referring to the three previous front end types, not `there`.
> Fix word error

- packages/sitecore-jss/src/axios-fetcher.ts
> Test commit

- docs/data/routes/docs/client-frameworks/getting-started/quick-start/en.md
- docs/data/routes/docs/techniques/ssr/headless-mode-ssr/en.md
> [Docs] Explicitly mention that NodeJS is a third-party technology.

- README.md
> [Docs] Update README with samples entry for Next.js and highlight features

- docs/data/routes/docs/client-frameworks/vue/vue-placeholders/en.md
- packages/sitecore-jss-vue/src/components/Placeholder.ts
- packages/sitecore-jss-vue/src/components/__snapshots__/Placeholder.test.ts.snap
https://v3.vuejs.org/guide/migration/fragments.html
> [Vue] Use fragments by default with sc-placeholder

- docs/data/routes/docs/nextjs/getting-started-nextjs/walkthrough-jsscreate/en.md
- docs/src/app/components/RouteLinkedRichText.js
- docs/src/boot/RouteHandler.js
> [Docs][Next.js]Fix step for deploying Next.js items to Sitecore [479849]

- samples/vue/server/server.vue.config.js
Use `@babel/transform-runtime` plugin
> [Vue] regeneratorRuntime error when opening Vue app in EE

- samples/angular/tsconfig.json
> [Angular] jss deploy files (jss deploy app) commands fails for angular sample app

- samples/angular/jss-create.js
- samples/nextjs/jss-create.js
- samples/react/jss-create.js
- samples/vue/jss-create.js
Update paths to the `create` module so that `jss create` works as expected.
> `jss create` Cannot find module error

- docs/data/routes/docs/nextjs/deploying-to-production/server-components/en.md
- docs/data/routes/docs/techniques/authentication/sitecore-auth/en.md
> [Docs] Fix broken links to main docs

- docs/sitecore/definitions/routes.sitecore.js
** Docs change only**
Use branch `release/18.0.0` instead of `master`
> Update "Found a problem" link in docs

- samples/react/jss-create.js
Currently throws error when using `jss create react-app react`
> 🕷[React][Sample] Typo in jss-create throws error

- samples/react/sitecore/config/JssReactWeb.config
- samples/react/src/components/GraphQL-IntegratedDemo/index.js
Cleaning up more messes I left 🙃
> 🕷[React][Sample] Typo in sitecore config

- CHANGELOG.md
Move past release notes to [CHANGELOG.md](https://github.com/Sitecore/jss/blob/dev/CHANGELOG.md)
NOTE: Links to migration guides under "Upgrading" headings should be updated when docs move.
> Migrate release notes to CHANGELOG.md

- CHANGELOG.md
Validated that changelog has everything for v19, updates as needed. Other adjustments for consistency.
> [Docs] v19 CHANGELOG updates

- docs/data/routes/docs/techniques/forms/en.md
Clarify session cookie requirements, adjustments to Next.js example (also requires setting `sitecoreApiHost` to an empty string).
> [Docs] Sitecore Forms doc updates for Next.js / session requirements

- samples/angular/src/app/components/graph-ql-integrated-demo/graph-ql-integrated-demo.component.html
Add missing `results` array to Angular's GraphQL Integrated Demo component.
> [Angular] [Regression] Console error when /graphql requested in EE, localhost or horizon

- samples/vue/src/lib/layout-service-factory.js
> [Vue] Fix Vue sample `RestLayoutService` config (use 'apiHost', not 'endpoint')

- .github/PULL_REQUEST_TEMPLATE.MD
- CONTRIBUTING.md
Contributing guidelines are outdated, update them to reflect current development workflow and stylistic guidelines.
> Update contributing guidelines

- packages/sitecore-jss-nextjs/package.json
- samples/nextjs/next-env.d.ts
- samples/nextjs/package.json
- yarn.lock
> Upgrade to Next.js 12

- azure-pipelines.yml
- packages/sitecore-jss-cli/src/scripts/create.ts
- packages/sitecore-jss-nextjs/package.json
- packages/sitecore-jss-react-forms/package.json
- packages/sitecore-jss-react/package.json
* Use `NodeTool` to specify node.js version, and we will have latest `npm` version
* run `npm i` with `--legacy-peer-deps'` flag, since `peerDependencies` are strict for npm 8, but anyway we will upgrade all dependencies.
* fix unit tests for packages that use `--require enzyme-setup.ts`, mocha didn't finish at the end of the execution. May be some issues related to `enzyme` or `enzyme adapter`, let's see after the upgrade.
> Node.js 16 upgrade

- packages/sitecore-jss-cli/package.json
- packages/sitecore-jss-cli/src/cli-shared.ts
- packages/sitecore-jss-dev-tools/package.json
- packages/sitecore-jss-rendering-host/package.json
- packages/sitecore-jss-rendering-host/src/tunnel.ts
- samples/nextjs/package.json
- yarn.lock
Upgrade security vulnerable packages
> Upgrade security vulnerable packages

- packages/create-sitecore-jss/src/common/steps/transform.test.ts
- packages/create-sitecore-jss/src/common/steps/transform.ts
- packages/create-sitecore-jss/src/index.ts
- packages/create-sitecore-jss/src/initializers/nextjs-styleguide/index.ts
- packages/create-sitecore-jss/src/initializers/nextjs/index.ts
* Use `--force` when we need to skip prompt related to file system
* Use `--yes` when we want to use defaults
> [Initializers] Split `force`, `yes` flags

- CONTRIBUTING.md
- packages/create-sitecore-jss/package.json
- packages/create-sitecore-jss/src/templates/nextjs/package.json
- packages/create-sitecore-jss/src/templates/node-headless-ssr-experience-edge/package.json
- packages/create-sitecore-jss/src/templates/node-headless-ssr-proxy/package.json
- packages/sitecore-jss-angular-schematics/package.json
- packages/sitecore-jss-angular/package.json
- packages/sitecore-jss-cli/package.json
- packages/sitecore-jss-dev-tools/package.json
- packages/sitecore-jss-forms/package.json
- packages/sitecore-jss-nextjs/package.json
- packages/sitecore-jss-proxy/package.json
- packages/sitecore-jss-react-forms/package.json
- packages/sitecore-jss-react-native/package.json
- packages/sitecore-jss-react/package.json
- packages/sitecore-jss-rendering-host/package.json
- packages/sitecore-jss-vue/package.json
- packages/sitecore-jss/package.json
npm 8 supports node.js starting from version 12. We should have appropriate configuration
> Update minimal node.js version, update CONTRIBUTING.md

- CONTRIBUTING.md
> [Retire samples] Improve contributing guide

- packages/create-sitecore-jss/src/initializers/angular/index.ts
- packages/create-sitecore-jss/src/initializers/nextjs/index.ts
- packages/create-sitecore-jss/src/initializers/react/index.ts
- packages/create-sitecore-jss/src/initializers/vue/index.ts
Switch defaults to fetchWith: REST and appPrefix: false to be consistent with current `jss create`.
> Switch Initializer defaults to fetchWith: REST and appPrefix: false

- packages/create-sitecore-jss/src/common/prompts/styleguide.ts
- packages/create-sitecore-jss/src/initializers/angular/index.ts
- packages/create-sitecore-jss/src/initializers/nextjs-styleguide/index.ts
- packages/create-sitecore-jss/src/initializers/react-native/index.ts
- packages/create-sitecore-jss/src/initializers/react/index.ts
- packages/create-sitecore-jss/src/initializers/vue/index.ts
- packages/create-sitecore-jss/src/templates/angular/src/app/components/styleguide-multilingual/styleguide-multilingual.component.html
- packages/create-sitecore-jss/src/templates/nextjs-styleguide/src/components/styleguide/Styleguide-Multilingual.tsx
- packages/create-sitecore-jss/src/templates/nextjs-styleguide/src/lib/next-config/plugins/styleguide.js
- packages/create-sitecore-jss/src/templates/react-native/src/components/Styleguide-Multilingual/index.js
- packages/create-sitecore-jss/src/templates/react-native/src/dataService/dataService.disconnected.js
- packages/create-sitecore-jss/src/templates/react/src/components/Styleguide-Multilingual/index.js
- packages/create-sitecore-jss/src/templates/vue/src/components/Styleguide/Styleguide-Multilingual.vue
* Require an additional language for all initializers (empty value should not be allowed)
* Set all initializers to use `da-DK` as default
* Adjusted template code to anticipate there _always_ being a language
> Require additional language for all initializers and default to `da-DK`

- packages/create-sitecore-jss/src/templates/vue/server/server.js
- packages/sitecore-jss-vue/src/components/PlaceholderCommon.ts
- packages/sitecore-jss-vue/src/components/__snapshots__/Placeholder.test.ts.snap
Changes from hotfix #902 into version 20
> [Vue][EE] Cannot add a new rendering to the newly created

- packages/create-sitecore-jss/README.md
Add a basic README to create-sitecore-jss package, similar to other @sitecore-jss npm packages, so that details show up in npmjs (https://www.npmjs.com/package/create-sitecore-jss).
@ancaemcken This minimal version is in line with our other npm packages (deferring to docs). However, maybe we should provide a bit more here like other `create-` packages in the community? Examples:
- https://www.npmjs.com/package/create-react-app
- https://www.npmjs.com/package/create-next-app
- https://www.npmjs.com/package/create-svelte-app
> README for `create-sitecore-jss`

- packages/create-sitecore-jss/src/templates/angular/src/app/routing/jss-route-builder.service.ts
GraphQL queries are case-sensitive in terms of language value. So we have to use the correct Sitecore format
> [Angular] Convert language to the sitecore compatible format

- packages/create-sitecore-jss/src/common/processes/install.ts
- packages/create-sitecore-jss/src/templates/angular/package.json
- packages/create-sitecore-jss/src/templates/angular/src/app/app.module.ts
- packages/create-sitecore-jss/src/templates/angular/src/app/jss-meta.service.ts
- packages/create-sitecore-jss/src/templates/angular/src/app/routing/layout/layout.component.ts
- packages/create-sitecore-jss/src/templates/vue/package.json
- packages/sitecore-jss-dev-tools/package.json
- yarn.lock
* _@ngx-meta/core_ doesn't support Angular 11, a new meta service was implemented
* _eslint_ for Vue now is compatible with _vue-eslint-plugin_
* Fixes for React will be added in [Apollo Client Upgrade PR](https://github.com/Sitecore/jss/tree/fix/515132)
* Removed not needed peer dep _chalk_ for _sitecore-jss-dev-tools_
> [RAV] Fix peer dependency errors

- README.md
> [DOCS] Add getting started and working with older versions info to the README

- README.md
> Update readme for v.20.0.0.

- packages/create-sitecore-jss/src/initializers/nextjs/index.ts
Allow add-on initializers to define description text that will show when the list of options is presented during the `create-sitecore-jss` prompt.
> [Initializers] [20.0.0] Add descriptions to add-on list

- packages/create-sitecore-jss/src/initializers/nextjs/index.ts
Allow add-on initializers to define description text that will show when the list of options is presented during the `create-sitecore-jss` prompt.
> [Initializers] Add descriptions to add-on list

- packages/create-sitecore-jss/src/templates/nextjs-personalize/src/components/CdpIntegrationScript.tsx
- packages/create-sitecore-jss/src/templates/nextjs-personalize/src/lib/layout-personalizer.ts
Updated imports for next personalize initializer add-on
> [Fix] Nextjs Personalize initializer add-on

- CHANGELOG.md
- packages/create-sitecore-jss/src/templates/nextjs/package.json
- packages/sitecore-jss-nextjs/package.json
- yarn.lock
* Bump Nextjs version to `12.1.0`
> [Nextjs] Bump Nextjs version to `12.1.0`

- packages/create-sitecore-jss/src/common/index.ts
- packages/create-sitecore-jss/src/initializers/nextjs/index.ts
* Remove `graphql-let` command when create empty app
> [Initializers] graphql-let error when bootstrapping empty Nextjs app

- packages/create-sitecore-jss/src/templates/nextjs-personalize/src/lib/middleware/plugins/personalize.ts
- packages/create-sitecore-jss/src/templates/nextjs/scripts/generate-plugins.ts
- packages/create-sitecore-jss/src/templates/nextjs/src/lib/middleware/index.ts
- packages/create-sitecore-jss/src/templates/nextjs/src/pages/_middleware.ts
* Each middleware should return `response` in order to use it by other middlewares
* Each middleware should have `order` to be defined
> [Nextjs] Create plugins approach for the nextjs middleware

- packages/sitecore-jss-react/src/components/VisitorIdentification.tsx
Moved the script and meta tag to client-site to fix empty tstamp when a user visits the styleguide page.
> [React] Fix empty `tstamp` issue with VisitorIdentification control

- packages/create-sitecore-jss/src/templates/nextjs-sxa/src/components/LinkList.tsx
- packages/create-sitecore-jss/src/templates/nextjs-sxa/src/components/RichText.tsx
- packages/create-sitecore-jss/src/templates/nextjs-sxa/src/components/Title.tsx
Fix for issues caused by refactoring: SXA Title, RichText and LinkList renderings were not working properly.
> #520166: fix issues caused by refactoring

- CHANGELOG.md
- Grouped linked items together
- added a `template` prefix to the PR related to the templates. (as templates replace samples, so trying to follow the convention from previous releases)
Note: Will create a PR for `dev` branch once this is merged.
> Review/refactor `CHANGELOG.md`

- CHANGELOG.md
Updated changelog for the dev branch
> Update/Review `CHANGELOG`

- packages/create-sitecore-jss/src/templates/node-headless-ssr-proxy/index.js
- packages/sitecore-jss-proxy/src/ProxyConfig.ts
- packages/sitecore-jss-proxy/src/index.ts
* Updated link for performance/caching in headless proxy
* Export `ProxyConfig` which can be used in the typescript-based app.
* `createViewBag` returns `object` or `promise`, before it was only `promise`
> [Headless SSR Proxy] Fix shape of config object - additional fixes

- packages/create-sitecore-jss/src/templates/nextjs-styleguide/sitecore/gitignore
Added the ignore file to the styleguide template so the newly scaffolded nextjs app contains it.
> [template/Nextjs] Add gitignore

- packages/create-sitecore-jss/src/templates/angular/data/routes/styleguide/en.yml
- packages/create-sitecore-jss/src/templates/nextjs-styleguide/data/routes/styleguide/en.yml
- packages/create-sitecore-jss/src/templates/react/data/routes/styleguide/en.yml
- packages/create-sitecore-jss/src/templates/vue/data/routes/styleguide/en.yml
Just fixed a typo on the Styleguide docs comment from `data/component/content/` to `/data/component-content`
> Fix Styleguide comment path reference

- packages/create-sitecore-jss/src/templates/angular/server.bundle.ts
* Take `language` from layout data, instead of `viewBag`, it doesn't contain `language`
> [node-headless-ssr-exp-edge][Angular] Danish language is not rendered when refresh the page

- packages/create-sitecore-jss/src/templates/nextjs-styleguide/data/routes/en.yml
Update `jss create` deprecated command
> [Next.js] Update `jss create` related info on the home page

- packages/sitecore-jss-nextjs/src/services/graphql-sitemap-service.ts
Addressing issues found during QA for sitemap changes
> Fixing formatting and syntax issues with graphQL variables

- packages/create-sitecore-jss/src/templates/nextjs-sxa/src/components/Container.tsx
- packages/create-sitecore-jss/src/templates/nextjs-sxa/src/components/PageContent.tsx
- packages/create-sitecore-jss/src/templates/nextjs-sxa/src/components/PartialDesignDynamicPlaceholder.tsx
- packages/create-sitecore-jss/src/templates/nextjs-sxa/src/pages/api/sitemap.ts
- packages/sitecore-jss-nextjs/src/services/graphql-sitemap-service.ts
hotfix eslint for building nextjs-sxa
>  hotfix eslint for building nextjs-sxa

- packages/sitecore-jss-angular/package.json
> [sitecore-jss-angular] Include all files from the dist

- packages/create-sitecore-jss/src/templates/nextjs-sxa/src/Layout.tsx
>  hotfix: change name of property

- packages/sitecore-jss-angular/src/components/generic-link.directive.spec.ts
- packages/sitecore-jss-angular/src/components/router-link.directive.spec.ts
> [Angular] Cover `class overwrite` for scGenericLink and scRouterLink by unit test

- packages/sitecore-jss/package.json
- packages/sitecore-jss/src/graphql-request-client.ts
- packages/sitecore-jss/src/native-fetcher.ts
- yarn.lock
Added [AbortController](https://www.npmjs.com/package/abort-controller) to `sitecore-jss` package to get rid of the error during `next build`.
> [sitecore-jss] Undefined `AbortController`

- packages/sitecore-jss-angular/src/public_api.ts
- packages/sitecore-jss-nextjs/src/index.ts
- packages/sitecore-jss-nextjs/src/utils.ts
- packages/sitecore-jss-react-native/src/index.ts
- packages/sitecore-jss-react/src/enhancers/withEditorChromes.tsx
- packages/sitecore-jss-react/src/index.ts
- packages/sitecore-jss-vue/src/index.ts
- packages/sitecore-jss/src/utils/editing.ts
- packages/sitecore-jss/src/utils/index.ts
* Remove deprecated functionality
> Remove deprecated features

- packages/create-sitecore-jss/src/templates/nextjs-sxa/src/assets/basic/_container.scss
- packages/create-sitecore-jss/src/templates/nextjs-sxa/src/assets/basic/_footer.scss
- packages/create-sitecore-jss/src/templates/nextjs-sxa/src/assets/basic/_header.scss
- packages/create-sitecore-jss/src/templates/nextjs-sxa/src/assets/basic/_navigation.scss
- packages/create-sitecore-jss/src/templates/nextjs-sxa/src/assets/sass/_app.scss
- packages/create-sitecore-jss/src/templates/nextjs-sxa/src/assets/sass/components/_component-navigation.scss
- packages/create-sitecore-jss/src/templates/nextjs-sxa/src/assets/sass/components/index.scss
- packages/create-sitecore-jss/src/templates/nextjs-sxa/src/assets/sass/components/navigation/_navigation-main-horizontal-vertical.scss
- packages/create-sitecore-jss/src/templates/nextjs-sxa/src/assets/sass/components/navigation/_navigation-mobile.scss
cherry pick for release 20.1.0
>  #533938 [SXA] fixed styles for managed classes (#1097)

- packages/create-sitecore-jss/src/templates/nextjs-sxa/src/Layout.tsx
- packages/create-sitecore-jss/src/templates/nextjs-sxa/src/assets/basic/_container.scss
- packages/create-sitecore-jss/src/templates/nextjs-sxa/src/assets/basic/_footer.scss
- packages/create-sitecore-jss/src/templates/nextjs-sxa/src/assets/basic/_header.scss
- packages/create-sitecore-jss/src/templates/nextjs-sxa/src/assets/basic/_navigation.scss
- packages/create-sitecore-jss/src/templates/nextjs-sxa/src/assets/sass/components/_component-container.scss
- packages/create-sitecore-jss/src/templates/nextjs-sxa/src/assets/sass/components/_component-navigation.scss
- packages/create-sitecore-jss/src/templates/nextjs-sxa/src/assets/sass/components/_component-richtext-content.scss
- packages/create-sitecore-jss/src/templates/nextjs-sxa/src/components/Container.tsx
added fixes for fullwidth design
>  #533938: [SXA] added fullwidth style for basic site

- packages/create-sitecore-jss/src/templates/nextjs-sxa/src/Layout.tsx
- packages/create-sitecore-jss/src/templates/nextjs-sxa/src/assets/basic/_container.scss
- packages/create-sitecore-jss/src/templates/nextjs-sxa/src/assets/basic/_footer.scss
- packages/create-sitecore-jss/src/templates/nextjs-sxa/src/assets/basic/_header.scss
- packages/create-sitecore-jss/src/templates/nextjs-sxa/src/assets/basic/_navigation.scss
- packages/create-sitecore-jss/src/templates/nextjs-sxa/src/assets/sass/components/_component-container.scss
- packages/create-sitecore-jss/src/templates/nextjs-sxa/src/assets/sass/components/_component-navigation.scss
- packages/create-sitecore-jss/src/templates/nextjs-sxa/src/assets/sass/components/_component-richtext-content.scss
- packages/create-sitecore-jss/src/templates/nextjs-sxa/src/components/Container.tsx
added fixes for fullwidth styles
> Feature/533938 [SXA] add fullwidth styles

- packages/create-sitecore-jss/src/templates/nextjs-sxa/src/Layout.tsx
- packages/create-sitecore-jss/src/templates/nextjs-sxa/src/assets/basic/_container.scss
- packages/create-sitecore-jss/src/templates/nextjs-sxa/src/assets/basic/_footer.scss
- packages/create-sitecore-jss/src/templates/nextjs-sxa/src/assets/basic/_header.scss
- packages/create-sitecore-jss/src/templates/nextjs-sxa/src/assets/main.scss
added fix for placeholders when we use editor mode
>  #542773: [SXA] fixed EE placeholders

- packages/create-sitecore-jss/src/templates/nextjs-sxa/src/components/Container.tsx
temporary fix SXA background image
>  #hotfix: [SXA] fixed background-image

- packages/sitecore-jss-nextjs/src/services/graphql-sitemap-service.ts
This fixes some irregularities with promises in graphql-sitemap-service, so that paginated path results are retrieved properly.
> Fix paginated results retrieval in sitemap paths service

- packages/create-sitecore-jss/src/templates/nextjs-sxa/src/Layout.tsx
- packages/create-sitecore-jss/src/templates/nextjs-sxa/src/components/Navigation.tsx
fixed navigation link in editing mode
>  #539620: [SXA] fixed navigation link in editing mode

- packages/create-sitecore-jss/src/templates/nextjs-sxa/src/components/Container.tsx
- packages/create-sitecore-jss/src/templates/nextjs-sxa/src/components/Image.tsx
- packages/create-sitecore-jss/src/templates/nextjs-sxa/src/components/LinkList.tsx
- packages/create-sitecore-jss/src/templates/nextjs-sxa/src/components/Navigation.tsx
- packages/create-sitecore-jss/src/templates/nextjs-sxa/src/components/PageContent.tsx
- packages/create-sitecore-jss/src/templates/nextjs-sxa/src/components/Promo.tsx
- packages/create-sitecore-jss/src/templates/nextjs-sxa/src/components/RichText.tsx
- packages/create-sitecore-jss/src/templates/nextjs-sxa/src/components/Title.tsx
Ability to display extra attribute (`id`)
> #545618 | Add configurable identifier for components

- packages/create-sitecore-jss/src/templates/nextjs-personalize/src/lib/middleware/plugins/personalize.ts
- packages/sitecore-jss-nextjs/src/edge/personalize-middleware.ts
Laying in the groundwork for full personalize consent implementation. 
Adds a configurable function to enable/disable personalize middleware.
> personalize on-off switch via function

- packages/create-sitecore-jss/src/templates/nextjs-sxa/src/assets/basic/_container.scss
- packages/create-sitecore-jss/src/templates/nextjs-sxa/src/assets/sass/components/image/_image-banner.scss
- packages/create-sitecore-jss/src/templates/nextjs-sxa/src/assets/sass/components/image/index.scss
- packages/create-sitecore-jss/src/templates/nextjs-sxa/src/components/Container.tsx
- packages/create-sitecore-jss/src/templates/nextjs-sxa/src/components/Image.tsx
Added a new variant for Image component - Banner variant for background image
>  #545156: added a new variant of image component

- packages/create-sitecore-jss/src/templates/nextjs-personalize/src/lib/middleware/plugins/personalize.ts
- Added description about the plugin 
- Added comments for config variables
> [Personalize] Add doc comments to personalization middleware plugin

- packages/sitecore-jss/src/personalize/graphql-personalize-service.test.ts
- packages/sitecore-jss/src/personalize/graphql-personalize-service.ts
Updated friendlyId format from `<id>_<language>_<version>`  to `embedded_<id>_<language>`
> [Personalize] Update `friendlyId` format

- packages/create-sitecore-jss/src/templates/nextjs-personalize/.env
* Update CDP hostname according to the provided updates
> [Next.js][Personalize] Switchover to new CDP hostname for personalize middleware

- packages/create-sitecore-jss/src/templates/nextjs-sxa/src/assets/basic/_navigation.scss
added css fix for top menu of basic site
>  #552444: fixed a top menu of basic site

- packages/create-sitecore-jss/src/initializers/nextjs/index.ts
Just an warning on nextjs-sxa template compatibility
> Extra xm cloud warning for sxa initializer

- packages/create-sitecore-jss/src/initializers/nextjs/index.ts
- packages/create-sitecore-jss/src/templates/nextjs-personalize/.env
- packages/create-sitecore-jss/src/templates/nextjs-personalize/package.json
- packages/create-sitecore-jss/src/templates/nextjs-personalize/src/components/CdpPageView.tsx
- packages/create-sitecore-jss/src/templates/nextjs/.env
* Update nextjs add-on descriptions
* Revisit personalize environment variable defaults (set to blank)
* Update `CdpPageView.tsx` based on latest engage SDK "target" parameter (domain > URL)
* Don't send page view events in preview mode
> [Next.js][Personalize] Cumulative minor updates/fixes

- packages/create-sitecore-jss/src/templates/nextjs-sxa/src/assets/basic/_promo.scss
fixed distance between promo components
>  #554316: fixed padding between promo components

- packages/sitecore-jss/src/utils/timeout-promise.ts
Extend existing timeout error message to make it more clear for developers
>  [sitecore-jss] Error message related to timeout is not intuitive

- packages/sitecore-jss-react-forms/package.json
- packages/sitecore-jss-react-forms/src/FieldProps.ts
- packages/sitecore-jss-react-forms/tsconfig.json
- packages/sitecore-jss-react/package.json
- yarn.lock
Follow-up to [#1055](https://github.com/Sitecore/jss/pull/1055), upgrade sitecore-jss-react-forms package to React 18. Fixes React peer dependency issues with sitecore-jss-react.
> [React][Forms] Upgrade sitecore-jss-react-forms to React 18

- packages/create-sitecore-jss/src/templates/nextjs-personalize/package.json
Bump @sitecore/engage to latest version 0.3.2
> [Next.js][Personalize] Bump @sitecore/engage to latest version

- packages/create-sitecore-jss/src/templates/nextjs-sxa/src/assets/sass/components/_component-container.scss
- packages/create-sitecore-jss/src/templates/nextjs-sxa/src/components/Container.tsx
>  #554695: added fix for container component

- packages/create-sitecore-jss/src/templates/nextjs-sxa/src/components/Image.tsx
#545156: added fix for sitecore-jss and reverted fix for banner variant of image component
>  #545156: added fix for sitecore-jss and reverted fix 

- packages/create-sitecore-jss/src/templates/nextjs-sxa/src/components/Image.tsx
>  #hotfix: fixed eslint errors

- packages/create-sitecore-jss/src/templates/nextjs-sxa/src/assets/sass/components/_component-container.scss
>  #556562: fixed styles

- packages/create-sitecore-jss/src/templates/nextjs-sxa/src/assets/basic/_footer.scss
>  #556683: fixed styles of footer basic site

- packages/create-sitecore-jss/src/templates/nextjs-sxa/src/assets/basic/_footer.scss
- packages/create-sitecore-jss/src/templates/nextjs-sxa/src/assets/basic/_promo.scss
>  #554316: fixed margin bottom for promo

- packages/create-sitecore-jss/src/templates/nextjs/package.json
- packages/sitecore-jss-nextjs/package.json
- yarn.lock
Upgraded package.json for nextjs template and package.
> [Nextjs] Upgrade nextjs version to 12.3.1

- packages/sitecore-jss-angular/src/components/data-resolver-factory.spec.ts
- packages/sitecore-jss-angular/src/components/data-resolver-factory.ts
- packages/sitecore-jss-angular/src/components/guard-resolver-factory.spec.ts
- packages/sitecore-jss-angular/src/components/guard-resolver-factory.ts
- packages/sitecore-jss-angular/src/components/placeholder.component.spec.ts
- packages/sitecore-jss-angular/src/components/placeholder.component.ts
- packages/sitecore-jss-angular/src/components/placeholder.token.ts
- packages/sitecore-jss-angular/src/jss-component-factory.service.ts
- packages/sitecore-jss-angular/src/lib.module.ts
- packages/sitecore-jss-angular/src/public_api.ts
- packages/sitecore-jss-angular/src/utils.ts
* Contains changes contributed in #376 
* Added `CanActivateFn` support and type
> [Angular] Add `canActivate` `resolve` functionality

- packages/sitecore-jss-react/.nycrc
- packages/sitecore-jss-react/src/components/Image.test.tsx
- packages/sitecore-jss-react/src/enhancers/withEditorChromes.test.tsx
- packages/sitecore-jss-react/src/enhancers/withPlaceholder.test.tsx
- packages/sitecore-jss-react/src/utils.test.ts
This PR does a few things:
- modify nyc coverage rules to have a more accurate coverage statistics
- add more tests for increased coverage, where tests are missing and make sense
> Extra unit test coverage for react package

- packages/sitecore-jss-nextjs/.nycrc
- packages/sitecore-jss-nextjs/src/components/EditingComponentPlaceholder.test.tsx
- packages/sitecore-jss-nextjs/src/middleware/redirects-middleware.test.ts
This PR:
- modifies nyc rules for more accurate coverage statistics
- adds extra unit tests
> nextjs package extra unit test coverage

- packages/create-sitecore-jss/src/templates/nextjs-sxa/src/assets/basic/_header.scss
Fixed header styles.
Problem was in position of two or many components on the one row. 
This fix also fix for default headless site header styles in preview(normal) mode.
>  #552985: [SXA] fixed header styles

- packages/create-sitecore-jss/src/templates/nextjs-sxa/src/assets/sass/components/_component-container.scss
This changes need to fix showing hidden components
Problem was with not correct style for each component when we use function **Hidden components** in EE
>  #546298: [SXA]fixed style for showing hidden components

- packages/create-sitecore-jss/src/templates/nextjs-sxa/src/pages/api/robots.ts
- packages/create-sitecore-jss/src/templates/nextjs-sxa/src/pages/api/sitemap.ts
- packages/sitecore-jss-nextjs/src/index.ts
Add site resolution in API routes using dynamic SiteResolver
> [Next.js][Multi-site] Site resolution in API routes

- packages/create-sitecore-jss/src/templates/nextjs/src/lib/sitemap-fetcher/plugins/graphql-sitemap-service.ts
Fixed `siteResolver` and `siteInfo` import in `graphql-sitemap-service`
> Fix import in  `graphql-sitemap-service`

- packages/sitecore-jss-react-forms/src/components/form.tsx
* Provides `sc_lang` parameter to specify exact language
> [React] The language of the form is changed after clicking the submit button

- packages/create-sitecore-jss/src/templates/vue/vue.config.js
Refactor `HtmlWebpackPlugin` in vue config as the `minify` option was coming out undefined.
> [Vue] Fix Vue production build

- packages/sitecore-jss-nextjs/src/index.ts
- packages/sitecore-jss-react/src/index.ts
> [Next.js][React] Added exports for FEaaSComponent

- packages/create-sitecore-jss/src/templates/nextjs-sxa/src/components/FEaaSWrapper.tsx
FEaaSWrapper component has been implemented
>  #565348 FEaaSWrapper component has been implemented

- packages/create-sitecore-jss/src/templates/vue/data/routes/styleguide/en.yml
- packages/create-sitecore-jss/src/templates/vue/src/Navigation.vue
- packages/create-sitecore-jss/src/templates/vue/src/assets/app.css
- packages/create-sitecore-jss/src/templates/vue/src/components/Styleguide/Styleguide-FieldUsage-Link.vue
- packages/create-sitecore-jss/src/templates/vue/src/components/Styleguide/Styleguide-FieldUsage-Text.vue
- packages/create-sitecore-jss/src/templates/vue/src/components/Styleguide/Styleguide-Layout.vue
Fix to some minor styling errors on the Styleguide page after upgrade of `bootstrap` to version 5.
> [Vue] Fix bootstrap upgrade styling errors

- packages/create-sitecore-jss/src/templates/vue/package.json
This fixes the warnings on the console which started to appear after the 3rd party dependency upgrade also it causes the integrated mode to fail.
> [Vue] Fix prod console warnings

- packages/sitecore-jss-dev-tools/package.json
- packages/sitecore-jss-dev-tools/src/mergeFs.ts
- yarn.lock
* Applies _axios_ hotfix https://github.com/axios/axios/issues/5520
* Applies breaking changes for `js-yaml` lib
* Ran _jss deploy items -c -d_
> [sitecore-jss-dev-tools] After upgrade deploy throws 'Cannot calculate proper length in synchronous way.'

- packages/create-sitecore-jss/src/templates/nextjs-sxa/src/pages/api/sitemap.ts
* Import _axios_ from _sitecore-jss-nextjs_ since _axios_ dependency is removed from the base template
> [SXA] Import AxiosResponse from nextjs base package

- packages/sitecore-jss-rendering-host/package.json
- packages/sitecore-jss-rendering-host/src/devServer.ts
- yarn.lock
Downgrade dependency `del` to `6.1.1` as it migrated to ESM from `7.0.0`
[HERE](https://github.com/sindresorhus/del/releases#:~:text=This%20package%20is%20now%20pure%20ESM.%20Please%20read%20this.)
> [sitecore-jss-rendering-host] fix react rendering host ESM error

- packages/create-sitecore-jss/src/templates/nextjs-styleguide/src/components/fields/Styleguide-FieldUsage-Image.tsx
width/height properties not provided in a field, so can be removed
> [Nextjs] Remove not used field width/height properties

- packages/sitecore-jss-nextjs/src/components/NextImage.tsx
Excluded **fill**, **priority** props from the final EE markup, since regular _img_ tag doesn't support that
Manual testing in EE
> [Next] Exclude Image `fill` `priority` props from being added to EE markup

- .github/PULL_REQUEST_TEMPLATE.MD
This should make the PR template a bit more informative.
- [:)] Breaking change (fix or feature that would cause existing functionality to change)
> PR template refresh

- packages/create-sitecore-jss/src/templates/node-headless-ssr-experience-edge/package.json
- packages/create-sitecore-jss/src/templates/node-headless-ssr-proxy/package.json
Upgrade 3rd party dependencies for:
- node-headless-ssr-proxy
- node-headless-ssr-experience-edge
> [Other Headless Templates] Upgrade 3rd party dependencies

- azure-pipelines.yml
Upgrade nodejs version to LTS.
> Upgrade node to LTS

- packages/create-sitecore-jss/src/templates/nextjs-styleguide/src/components/styleguide/Styleguide-EditFrame.tsx
- packages/create-sitecore-jss/src/templates/vue/src/components/Styleguide/Styleguide-EditFrame.vue
> [Edit Frame] QA follow up

- azure-pipelines.yml
- package.json
- yarn.lock
* Updated lerna to latest 5.x version
* Added brackets to **scope** value argument
> Enable Azure pipelines to lint samples for PRs

- packages/sitecore-jss-proxy/package.json
- packages/sitecore-jss-proxy/src/ProxyConfig.ts
- packages/sitecore-jss-proxy/src/index.test.ts
- packages/sitecore-jss-proxy/src/index.ts
- yarn.lock
- Upgrade `http-proxy-middleware` 
- Remove `@types/http-proxy-middleware` as `http-proxy-middleware` provides its own type definitions.
> [sitecore-jss-proxy] Upgrade 3rd party dependencies

- packages/sitecore-jss-proxy/src/index.ts
Remove extra check that had to be removed
> [sitecore-jss-proxy] Revert extra isUrlIgnored check

- packages/create-sitecore-jss/src/templates/nextjs-personalize/src/components/CdpPageView.tsx
Disable personalization in development mode similar to what we have in personalize middleware.
> [Personalize] Disable page view tracking event in development

- CHANGELOG.md
- packages/create-sitecore-jss/src/templates/nextjs-personalize/src/components/CdpPageView.tsx
> [Personalize] Update doc comment

- packages/sitecore-jss-react/package.json
Hotfix following https://github.com/Sitecore/jss/pull/1413 - clientside dependency changed.
> [nextjs][feaas] Hotfix - change feaas/clientside dependency

- CHANGELOG.md
- packages/sitecore-jss-angular/src/components/image.directive.ts
- packages/sitecore-jss-angular/src/components/link.directive.ts
Full credit to @zwang-rocket for reporting and fixing the issue.
Commit cherrypicked  from https://github.com/Sitecore/jss/pull/1411 , this PR only adds a Changelog entry on top.
> [angular] Fix memory leak in image and link components

- packages/create-sitecore-jss/src/initializers/nextjs-styleguide-tracking/index.ts
- packages/create-sitecore-jss/src/initializers/nextjs-sxa-project-basic/index.ts
- packages/create-sitecore-jss/src/initializers/nextjs-sxa-project-playtravel/index.ts
- packages/create-sitecore-jss/src/initializers/nextjs-sxa/index.ts
- packages/create-sitecore-jss/src/templates/nextjs-sxa-project-basic/src/projects/basic/components/SampleComponent.tsx
- Add an empty optional basic site theme add-on which contains theme related components and assets(which will be added by the SXA team in future) to support multi-project functionality.
- This add-on can only be added on top of the nextjs-sxa add-on.
> [Nextjs][nextjs-sxa] Add `nextjs-sxa-project-basic` add-on

- CHANGELOG.md
- packages/create-sitecore-jss/src/templates/nextjs-sxa/src/pages/500.tsx
Fixed a wrong type for defines of defaultLocale
>  #584737: [templates/nextjs-sxa] fixed wrong type

- CHANGELOG.md
Update changelog for 21.0.10, 21.1.3 21.1.4 21.1.5
> [Chore] Update changelog for hotfixes

- CHANGELOG.md
- packages/sitecore-jss/src/layout/graphql-layout-service.ts
Add optional chaining to handle null items for layout service.
> [sitecore-jss] Handle layout for null items

- CHANGELOG.md
- packages/create-sitecore-jss/src/templates/nextjs-sxa/src/assets/sass/components/spacing/_indent.scss
Added fix for .indent class of components when there use column size 12
>  #575901: [nextjs-sxa] fixed style of indent for components

- packages/sitecore-jss-react/package.json
- yarn.lock
Update feaas-clientside module dependency to support BYOC components registration.
> [nextjs][react] Update feaas dependency

- CHANGELOG.md
- packages/sitecore-jss-dev-tools/package.json
Includes d.ts, js submodules as a part of npm publish
> [sitecore-jss-dev-tools] Include submodules as a part of publish

- CHANGELOG.md
This PR just adds a few missing entries to changelog ahead of the release.
> [Chore] Add missing changelog entries

- CHANGELOG.md
- packages/create-sitecore-jss/src/templates/nextjs-sxa/scripts/templates/component-src.ts
- packages/create-sitecore-jss/src/templates/nextjs-sxa/src/components/ColumnSplitter.tsx
- packages/create-sitecore-jss/src/templates/nextjs-sxa/src/components/Container.tsx
- packages/create-sitecore-jss/src/templates/nextjs-sxa/src/components/Image.tsx
- packages/create-sitecore-jss/src/templates/nextjs-sxa/src/components/LinkList.tsx
- packages/create-sitecore-jss/src/templates/nextjs-sxa/src/components/Navigation.tsx
- packages/create-sitecore-jss/src/templates/nextjs-sxa/src/components/PageContent.tsx
- packages/create-sitecore-jss/src/templates/nextjs-sxa/src/components/Promo.tsx
- packages/create-sitecore-jss/src/templates/nextjs-sxa/src/components/RichText.tsx
- packages/create-sitecore-jss/src/templates/nextjs-sxa/src/components/RowSplitter.tsx
- packages/create-sitecore-jss/src/templates/nextjs-sxa/src/components/Title.tsx
Added tabIndex attribute for each component of SXA(request our customer)
>  #586488: [templatex/nextjs-sxa] added tabindex for components of SXA

- CHANGELOG.md
- packages/create-sitecore-jss/src/templates/react/package.json
Add dependency `@babel/plugin-proposal-private-property-in-object` to fix build issue.
> [React] Fix build error

- packages/sitecore-jss-react/package.json
- yarn.lock
Bump feaas/clientside dependency version to latest in jss-react package.
> [Chore] update feaas/clientside version

- packages/sitecore-jss-react/src/components/FEaaSComponent.test.tsx
- packages/sitecore-jss-react/src/components/FEaaSComponent.tsx
This only needs a review for now - we'll cherrypick commit into release branch, then update dev.
Following changes in feaas/clientside library, we need to adjust the data we pass into 'data' prop.
> [nextjs][feaas] Adjust object type passed to data prop

- packages/sitecore-jss-react/src/components/FEaaSComponent.test.tsx
- packages/sitecore-jss-react/src/components/FEaaSComponent.tsx
Merge recent feaas changes ahead of release.
> [nextjs][feaas] Adjust object type passed to data prop (#1531)

- packages/create-sitecore-jss/src/templates/nextjs-sxa/package.json
> [nextjs-sxa] Add `@sitecore-feaas/clientside` to sxa add-on

- CHANGELOG.md
- packages/create-sitecore-jss/README.md
- packages/create-sitecore-jss/src/templates/angular/README.md
- packages/create-sitecore-jss/src/templates/nextjs/README.md
- packages/create-sitecore-jss/src/templates/node-headless-ssr-experience-edge/README.md
- packages/create-sitecore-jss/src/templates/node-headless-ssr-proxy/README.md
- packages/create-sitecore-jss/src/templates/node-headless-ssr-proxy/src/index.ts
- packages/create-sitecore-jss/src/templates/react-native/README.MD
- packages/create-sitecore-jss/src/templates/react/README.md
- packages/create-sitecore-jss/src/templates/vue/README.md
- packages/sitecore-jss-angular-schematics/README.md
- packages/sitecore-jss-angular/README.md
- packages/sitecore-jss-cli/README.md
- packages/sitecore-jss-dev-tools/README.md
- packages/sitecore-jss-forms/README.md
- packages/sitecore-jss-nextjs/README.md
- packages/sitecore-jss-proxy/README.md
- packages/sitecore-jss-react-forms/README.md
- packages/sitecore-jss-react-native/README.md
- packages/sitecore-jss-react/README.md
- packages/sitecore-jss-rendering-host/README.md
- packages/sitecore-jss-vue/README.md
- packages/sitecore-jss/README.md
Updated outdated documentation links
> [Chore] Update outdated documentation links

- CHANGELOG.md
- packages/sitecore-jss-nextjs/src/middleware/redirects-middleware.test.ts
- packages/sitecore-jss-nextjs/src/middleware/redirects-middleware.ts
There was problem with regexp. Fixed and remove smell code
> #589841 [sitecore-jss-nextjs] use token in redirects. fixed bug

- CHANGELOG.md
- packages/create-sitecore-jss/src/templates/nextjs-sxa/src/pages/api/robots.ts
related:
https://github.com/sitecorelabs/xmcloud-foundation-head-dev/pull/122
> #590086 | xmcloud-foundation-head robots.txt Content-Type is wrong

- CHANGELOG.md
- packages/sitecore-jss-nextjs/src/middleware/redirects-middleware.test.ts
- packages/sitecore-jss-nextjs/src/middleware/redirects-middleware.ts
Fixed handling token in target
> #589841: [sitecore-jss-nextjs] use token in redirects

- .github/workflows/create_jira_issue.yml
- CHANGELOG.md
- scripts/create-jira-issue.js
Introduced new github action and related script to automate our triage process
> [Chore] Automatically create a Jira Issue once a github issue/doc request/PR is created

- packages/create-sitecore-jss/src/templates/nextjs-sxa/package.json
- packages/create-sitecore-jss/src/templates/nextjs/scripts/generate-component-builder/plugins/packages.ts
- packages/create-sitecore-jss/src/templates/nextjs/scripts/scaffold-component/plugins/next-steps.ts
Short follow-up to BYOC Scaffold PR. Adds consistency to comments, fixes some bugs with implementation.
> BYOC Scaffold follow-up

- CHANGELOG.md
- packages/create-sitecore-jss/src/templates/nextjs-sxa/src/pages/api/sitemap.ts
>  #563014: [templates/nextjs-sxa] fixed open sitemap

- packages/create-sitecore-jss/src/templates/nextjs-sxa/scripts/templates/byoc-component-src.ts
Small bugfix to lint the byoc scaffold template.
> [BYOC] Scaffold follow-up - lint template

- CHANGELOG.md
- packages/create-sitecore-jss/src/templates/nextjs-sxa/src/assets/sass/_app.scss
added padding for layout - reason: when we add Container component into placeholder we can see horizontal scrollbar
>  #588462: added padding for layout

- packages/create-sitecore-jss/src/templates/nextjs/scripts/scaffold-component/index.ts
This is a small fix for test automation to allow relative paths for scaffolded components.
> [templates/nextjs] Allow relative paths when scaffolding a component

- CHANGELOG.md
- packages/create-sitecore-jss/src/templates/nextjs/src/lib/next-config/plugins/cors-header.js
This new plugin helps fix CORS issue on CM host, also when trying to use different fonts from remote sources on XMCloud.
> [template/nextjs] Next config header plugin for CORS 

- CHANGELOG.md
- packages/create-sitecore-jss/src/templates/nextjs-sxa/src/assets/basic/_component.scss
- packages/create-sitecore-jss/src/templates/nextjs-sxa/src/components/Image.tsx
Fixed highlighter(EE mode) Image component in Banner variant.
>  #562770: [templates/nextjs-sxa] fixed Image component highlighter

- packages/create-sitecore-jss/src/templates/nextjs-styleguide/scripts/scaffold-component/plugins/next-steps-styleguide.ts
Quick fix for scaffold in nextjs-styleguide apps
> [template/nextjs-styleguilde] Fix stylegide scaffold

- CHANGELOG.md
- packages/create-sitecore-jss/src/templates/angular/angular.json
- packages/create-sitecore-jss/src/templates/angular/package.json
- packages/create-sitecore-jss/src/templates/angular/src/tsconfig.server.json
Small follow up to v15 upgrade to address some warnings during build (https://github.com/ng-bootstrap/ng-bootstrap/issues/4306) and npm install.
> [Angular] Angular v15 - workaround Bootstrap warnings

- CHANGELOG.md
- packages/sitecore-jss-react-forms/src/components/form.test.tsx
- packages/sitecore-jss-react-forms/src/components/form.tsx
Ensures form is disabled until submit is complete to avoid problems.
> [sitecore-jss-react-forms] Disable form while submit is in progress

- CHANGELOG.md
- packages/create-sitecore-jss/src/templates/nextjs/package.json
- packages/sitecore-jss-react/package.json
- yarn.lock
- Update CHANGELOG
- Upgrade `@sitecore-feaas/clientside` to latest
> [Chore] Updates for release prep

- CHANGELOG.md
- packages/create-sitecore-jss/src/templates/nextjs-sxa/src/assets/sass/_app.scss
- packages/create-sitecore-jss/src/templates/nextjs-sxa/src/assets/sass/components/_component-container.scss
There was problem with shown horizontal scrollbar. Fixed the wrong padding in css
>  #598669: [templates/nextjs-sxa] fixed styles(hide horizontal scrollbar)

- CHANGELOG.md
- packages/create-sitecore-jss/src/templates/nextjs-sxa/src/assets/sass/abstracts/_mixins.scss
Fixed desktop breakpoint of bootstrap grid
>  #598669: [templates/nextjs-sxa] changed breakpoint of bootstrap grid

- CHANGELOG.md
- packages/sitecore-jss-nextjs/src/middleware/redirects-middleware.ts
There was problem with middleware of redirects - it worked every other time. Fixed it.
>  #599694: [sitecore-jss-nextjs] fixed redirects

- azure-pipelines.yml
- package.json
Small chore to enable hotfix release for 13 release branch.
Please consider the Friday review of this one "Friday, the 13th".
> [Chore] ver13 azure pipeline to be able to publish canary

- packages/create-sitecore-jss/src/templates/nextjs-xmcloud/src/lib/context/sdk/events.ts
Custom sitecoreEdgeUrl should be provided to Events SDK as well
> [Next.js][Context] Provide custom sitecoreEdgeUrl to Events sdk

- CHANGELOG.md
- packages/sitecore-jss/src/layout/content-styles.test.ts
- packages/sitecore-jss/src/layout/content-styles.ts
* Updated styles url to use file proxy path
> [sitecore-jss] Load content styles using a correct file proxy url

- CHANGELOG.md
- packages/create-sitecore-jss/src/templates/nextjs-sxa/src/components/Image.tsx
> [templates/nextjs-sxa] fixed request background image if it is empty

- CHANGELOG.md
- packages/create-sitecore-jss/src/templates/nextjs-sxa/src/assets/sass/_app.scss
- packages/create-sitecore-jss/src/templates/nextjs-sxa/src/assets/sass/abstracts/_mixins.scss
- packages/create-sitecore-jss/src/templates/nextjs-sxa/src/assets/sass/components/_component-container.scss
- packages/sitecore-jss-nextjs/src/middleware/redirects-middleware.ts
It includes two SXA fixes:
- Fix loop error in redirect middleware when the pattern of redirect has default locale.
- Fix shown horizontal scrollbar in EE mode.
> JSS 21.5.3 release fixes

- CHANGELOG.md
- packages/create-sitecore-jss/src/templates/nextjs-sxa/src/assets/sass/_app.scss
Feature `show Grid column` wasn't shown in Experience Editor. Fixed
>  [templates/nextjs-sxa]: fixed shown grid columns in EE

- CHANGELOG.md
- packages/create-sitecore-jss/src/templates/nextjs/package.json
- packages/sitecore-jss-nextjs/package.json
- yarn.lock
No breaking changes related to functionality within the upgrade
> [Next] Upgrade to version 14

- CHANGELOG.md
- packages/create-sitecore-jss/src/templates/nextjs/package.json
- packages/sitecore-jss-nextjs/package.json
- yarn.lock
Bumped Next.js to 14.1 (Follow-up to Next.js 14 upgrade)
> [Nextjs] Bump to version 14.1.0

- CHANGELOG.md
- packages/sitecore-jss-angular/src/public_api.ts
- packages/sitecore-jss-nextjs/src/index.ts
- packages/sitecore-jss-react/src/index.ts
- packages/sitecore-jss-vue/src/index.ts
- packages/sitecore-jss/src/index.ts
Export `ClientError` from base `sitecore-jss` package and re-export from RAV and nextjs package so it is available to all services.
> Export `ClientError`

- CHANGELOG.md
- packages/create-sitecore-jss/src/templates/nextjs-sxa/src/assets/basic/_container.scss
The BasicSite has own styles which conflicted with base style of SXA. The conflicted styles has been removed
>  [templates/nextjs-sxa]: base styles has been fixed

- CHANGELOG.md
- packages/create-sitecore-jss/src/templates/nextjs/src/lib/dictionary-service-factory.ts
- packages/create-sitecore-jss/src/templates/nextjs/src/lib/layout-service-factory.ts
`retries` is coming out to be of type string and number but we need it to be a number explicitly.
> Fix `retries` type

- docs/upgrades/unreleased.md
A simple adjustment to unreleased upgrade guide in regards to site query usage.
> [Chore] Prepare upgrade guide for release

- CHANGELOG.md
- packages/create-sitecore-jss/src/templates/angular/src/app/lib/client-factory.ts
- packages/create-sitecore-jss/src/templates/angular/src/app/lib/dictionary-service-factory.ts
- packages/create-sitecore-jss/src/templates/angular/src/app/lib/layout-service-factory.ts
- packages/create-sitecore-jss/src/templates/node-headless-ssr-experience-edge/src/client-factory.ts
- packages/create-sitecore-jss/src/templates/node-headless-ssr-experience-edge/src/index.ts
- packages/create-sitecore-jss/src/templates/react/src/lib/client-factory.js
- packages/create-sitecore-jss/src/templates/react/src/lib/dictionary-service-factory.js
- packages/create-sitecore-jss/src/templates/react/src/lib/layout-service-factory.js
- packages/create-sitecore-jss/src/templates/vue/src/lib/client-factory.js
- packages/create-sitecore-jss/src/templates/vue/src/lib/dictionary-service-factory.js
- packages/create-sitecore-jss/src/templates/vue/src/lib/layout-service-factory.js
- packages/sitecore-jss-angular/src/public_api.ts
- packages/sitecore-jss-nextjs/src/components/Link.tsx
- packages/sitecore-jss-nextjs/src/components/NextImage.tsx
- packages/sitecore-jss-nextjs/src/components/RichText.tsx
- packages/sitecore-jss-react/src/components/Date.tsx
- packages/sitecore-jss-react/src/components/Image.tsx
- packages/sitecore-jss-react/src/components/Link.tsx
- packages/sitecore-jss-react/src/components/RichText.tsx
- packages/sitecore-jss-react/src/components/Text.tsx
- packages/sitecore-jss-react/src/index.ts
- packages/sitecore-jss-vue/src/index.ts
* Updated RAV/node samples to use _clientFactory_
* Removed deprecated _defaultProps_ react component property
> [Chore] Removed deprecated props, updated samples to use clientFactory

- CHANGELOG.md
- packages/sitecore-jss-react/src/components/ErrorBoundary.test.tsx
- packages/sitecore-jss-react/src/components/ErrorBoundary.tsx
This PR is a follow up to #1786 and updates the default error message that shows in production mode when ErrorBoundary catches an error.
> [sitecore-jss-react] Update the default error message for ErrorBoundary

- CHANGELOG.md
- packages/sitecore-jss-react/src/components/Placeholder.test.tsx
- packages/sitecore-jss-react/src/enhancers/withPlaceholder.test.tsx
- packages/sitecore-jss-react/src/enhancers/withPlaceholder.tsx
- packages/sitecore-jss-react/src/test-data/metadata-data.ts
* Refactored unit tests for _withPlaceholder_ HOC, since initially they were validating a wrong use case
* Added support for Metadata Edit Mode
> [Editing Integration] withPlaceholder support for Metadata Mode

- packages/create-sitecore-jss/src/templates/react/package.json
Follow up to https://github.com/Sitecore/jss/pull/1804  to address issues found in testing of the upgrades.
- Remove `url-parse` dependency from react sample to avoid npm conflicts with webpack.
> [react][nextjs] Extra upgrade hotfix prep

- CHANGELOG.md
- packages/create-sitecore-jss/src/templates/nextjs-sxa/src/components/Image.tsx
- packages/create-sitecore-jss/src/templates/nextjs-sxa/src/components/Promo.tsx
For optimization SXA components there were changed Image to NextImage component from JSS
>  [templates/nextjs-sxa]: Image and Promo components has been changed #SXA-2126

- CHANGELOG.md
- packages/create-sitecore-jss/src/templates/nextjs/next.config.js
Follow-up to https://github.com/Sitecore/jss/pull/1843. Added Next.js image optimization remote pattern for XM Cloud CM/preview images.
> [Next.js] Image optimization remote pattern for XM Cloud CM/preview images

- CHANGELOG.md
- packages/create-sitecore-jss/src/templates/angular-xmcloud/src/assets/styles/sass/components/_component-image.scss
- packages/create-sitecore-jss/src/templates/nextjs-sxa/src/assets/sass/components/_component-image.scss
The caption of Image component was rendering incorrect.
>  [templates/nextjs-sxa]: Rendering caption of image component has been fixed #SXA-7413

- CHANGELOG.md
- packages/create-sitecore-jss/src/templates/angular-xmcloud/src/app/jss-link.service.ts
- packages/create-sitecore-jss/src/templates/angular-xmcloud/src/app/routing/layout/layout.component.html
- packages/create-sitecore-jss/src/templates/angular-xmcloud/src/app/routing/layout/layout.component.ts
- packages/create-sitecore-jss/src/templates/angular/src/app/JssState.ts
- packages/create-sitecore-jss/src/templates/angular/src/app/app.module.ts
- packages/create-sitecore-jss/src/templates/angular/src/app/routing/layout/layout.component.ts
- packages/create-sitecore-jss/src/templates/angular/src/app/routing/routing.module.ts
- Fix build issues
- Fix console errors
> [template/angular-xmcloud] Fix angular layout component

- CHANGELOG.md
- packages/create-sitecore-jss/src/templates/angular-xmcloud/.env
Fix proxy build path to copy build artifacts to proxy app properly.
> [angular-xmcloud] Fix proxy build path

- packages/sitecore-jss-nextjs/src/editing/constants.ts
Remove unneeded origins from default editing origins list.
Merge after future change to deploy procedure.
> [sitecore-jss-nextjs] Cleanup default origins for editing

- CHANGELOG.md
- packages/sitecore-jss-nextjs/src/middleware/redirects-middleware.test.ts
There was missed unit test for redirects
>  [sitecore-jss-nextjs] The unit test of redirects has been added

- CHANGELOG.md
- packages/create-sitecore-jss/src/templates/angular-xmcloud/src/app/components/row-splitter/row-splitter.component.html
- packages/create-sitecore-jss/src/templates/angular-xmcloud/src/app/components/row-splitter/row-splitter.component.ts
Adds RowSplitter SXA component
> [angular-xmcloud] Introduce RowSplitter SXA component

- CHANGELOG.md
- packages/create-sitecore-jss/src/templates/angular-xmcloud/src/app/components/app-components.shared.module.ts
- packages/create-sitecore-jss/src/templates/angular-xmcloud/src/app/components/image/image.component.html
- packages/create-sitecore-jss/src/templates/angular-xmcloud/src/app/components/navigation/navigation-item.component.html
- packages/create-sitecore-jss/src/templates/angular-xmcloud/src/app/components/navigation/navigation-item.component.ts
- packages/create-sitecore-jss/src/templates/angular-xmcloud/src/app/components/navigation/navigation.component.html
- packages/create-sitecore-jss/src/templates/angular-xmcloud/src/app/components/navigation/navigation.component.ts
Introduce SXA Navigation component
> [angular-xmcloud] Introduce angular SXA navigation component

- CHANGELOG.md
- packages/create-sitecore-jss/src/templates/angular-xmcloud/src/app/components/title/title.component.html
- packages/create-sitecore-jss/src/templates/angular-xmcloud/src/app/components/title/title.component.ts
- packages/sitecore-jss-angular/src/components/rendering-field-sxa.ts
- packages/sitecore-jss-angular/src/components/rendering-field.ts
- packages/sitecore-jss-angular/src/public_api.ts
Title component and related types added
> [angular-xmcloud] Introduce SXA Title component

- CHANGELOG.md
- packages/create-sitecore-jss/src/templates/angular-xmcloud/src/app/components/page-content/page-content.component.html
- packages/create-sitecore-jss/src/templates/angular-xmcloud/src/app/components/page-content/page-content.component.ts
Add SXA PageContent component to angular-xmcloud
> [template/angular-xmcloud] Introduce SXA PageContent component

- CHANGELOG.md
- docs/upgrades/unreleased.md
- packages/create-sitecore-jss/src/templates/angular/src/environments/gitignore
- packages/create-sitecore-jss/src/templates/node-headless-ssr-experience-edge/gitignore
- packages/create-sitecore-jss/src/templates/node-headless-ssr-proxy/gitignore
- packages/create-sitecore-jss/src/templates/node-xmcloud-proxy/gitignore
Adds gitignore files for:
- node-xmcloud-proxy
- node-headless-ssr-proxy
- node-headless-ssr-experience-edge
Adjusts gitignore for angular base template.
> [Chore][Angular] gitignores for angular and proxies

- packages/create-sitecore-jss/src/templates/nextjs-sxa/src/assets/sass/components/common/_alignment.scss
There was an issue with the alignment of elements when components used both the `me-auto` and `ms-md-auto` classes.
> [templates/nextjs-sxa]: The component aligment has been fixed #SXA-6539

- CHANGELOG.md
- packages/sitecore-jss-angular/src/public_api.ts
- packages/sitecore-jss-nextjs/src/index.ts
- packages/sitecore-jss-react/src/index.ts
- packages/sitecore-jss-vue/src/index.ts
- packages/sitecore-jss/src/index.ts
Exports `CacheClient`, `CacheOptions`, `MemoryCacheClient` classes to be used in JSS applications.
> [sitecore-jss] Export cache-client functionality

- CHANGELOG.md
- packages/create-sitecore-jss/src/templates/nextjs-sxa/src/assets/sass/components/common/_alignment.scss
There was an issue with the alignment of elements when components used both the `me-auto` and `ms-md-auto` classes. Additionally, the `mx-{breakpoint}-auto` class has been added.
>  [templates/nextjs-sxa]: The component alignment has been fixed #SXA-6539

- CHANGELOG.md
- scripts/samples.json
- scripts/utils.js
> [Chore] New Angular add-on's are not scaffolded within build pipeline

- CHANGELOG.md
- packages/create-sitecore-jss/src/templates/angular-xmcloud/package.json
- packages/create-sitecore-jss/src/templates/nextjs-xmcloud/package.json
- packages/sitecore-jss-nextjs/package.json
- packages/sitecore-jss-proxy/package.json
- packages/sitecore-jss-react/package.json
- packages/sitecore-jss-react/src/components/BYOCComponent.test.tsx
- packages/sitecore-jss-react/src/components/BYOCComponent.tsx
- yarn.lock
Fixed failing Form submission. Updated @sitecore-feaas/clientside, @sitecore-cloudsdk to the latest versions
> [BYOC] Form's submission is failing. Updated @sitecore-feaas/clientside to v0.5.19. Updated @sitecore-cloudsdk to v0.4.1.
